### ISSUE TITLE
Strip whitespace in the scheme too

### ISSUE THREAD

**Issue by annevk** [whatwg/url#101]
See https://github.com/whatwg/html/issues/823 for context.

@valenting does this basically mean stripping \r\n\t from the input to the URL parser? Seems like it would be the easiest if we go down this route. Still not entirely happy as it makes it easier to sneak unsafe URL schemes past broken URL checks, but if you're not using safelists it's unsafe anyway I suppose.

**Comment by valenting** [comment]
Yes, after bug 241788 we strip \r\n\t from the URL parser's input.
If the checks are done on a URL object, not on the input string, this shouldn't make things more unsafe.

**Comment by zcorpan** [comment]
WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=143381

**Comment by zcorpan** [comment]
web-platform-tests PR: https://github.com/w3c/web-platform-tests/pull/2662
