### ISSUE TITLE
File names in application/x-www-form-urlencoded serializer

### ISSUE THREAD

**Issue by SimonSapin** [whatwg/url#109]
b174f8f2170a4ce6fd4031206e0490eff2b0aa02 added

> Otherwise, if tuple has a type, and tuple’s type is "file", set outputPair’s value to tuple’s value’s filename.

Contrary to the general case, a filename here does not go through the "byte serializer" (or character encoding). This means that any `&` or `=` character in the name will be serialized as-is, incorrectly creating new name/value pairs when the serialized string is parsed again. Is this really intended?

It’s also not clear from https://html.spec.whatwg.org/#concept-input-type-file-selected what the type of a file name is supposed to be in the first place. (Bytes vs Unicode vs WTF-16/DOMString.)

**Comment by annevk** [comment]
Yeah, that should probably be clarified. I'm guessing the input is typically WTF-16. Not sure if we can require anything specific.

**Comment by SimonSapin** [comment]
Why not percent-encode `&` and other characters (non-ASCII, controls, …) in a file name?

**Comment by annevk** [comment]
We should require that, sure, I was just wondering about the other part of your feedback. What type a filename is.

**Comment by annevk** [comment]
I'm going to assume a filename is a JavaScript string for now. If someone wants to put effort into standardizing how it becomes a JavaScript string, please go ahead and do so.
