### ISSUE TITLE
Percent-encode 0x0D and 0x0A to "%0D%0A" in the application/x-www-form-urlencoded byte serializer?

### ISSUE THREAD

**Issue by ziyunfei** [whatwg/url#120]
Browsers escape CR/LF to "%0D%0A" when form submitting ([test](http://output.jsbin.com/cajidibuci)), so should we make `new URLSearchParams("\r=\n").toString()` return `"%0D%0A=%0D%0A"`?

**Comment by ziyunfei** [comment]
but `location.search="?foo=\r&bar=\n"` behaves differently

**Comment by ziyunfei** [comment]
Turn out this is because of 
[![image](https://cloud.githubusercontent.com/assets/1276859/15207416/af8aa25c-1858-11e6-9129-8d8402d33764.png)](https://html.spec.whatwg.org/multipage/forms.html#constructing-form-data-set:concept-fe-value-2)

**Comment by annevk** [comment]
Okay, I think we should close this then and not make it part of the format. That also will make it easier to align the format with the way query state works in URLs. Agreed?
