### ISSUE TITLE
incorrect definition of ASCII hex digits

### ISSUE THREAD

**Issue by ben-page** [whatwg/url#121]
https://url.spec.whatwg.org/#infrastructure

> The ASCII hex digits are ASCII digits, code points in the range U\+0041 to U\+0046, inclusive, and code points in the range U\+0061 to U\+0066, inclusive\.

In definition above, shouldn't ASCII hex digits include U\+0030 to U\+0039 (0-9)?

Based on usage in the document, it does not appear to be referring to only a-f and A-F. For example:

> A percent\-encoded byte is "%", followed by two ASCII hex digits\. Sequences of percent\-encoded bytes, after conversion to bytes, should not cause UTF\-8 decode without BOM or fail to return failure\.

**Comment by tml** [comment]
There are 3 categories called out there:
1)  ASCII digits
2) code points in the range U+0041 to U+0046, inclusive
3) code points in the range U+0061 to U+0066, inclusive

I think that covers all of hex, does it not?

**Comment by annevk** [comment]
Yeah it does. I suspect @ben-page forgot to follow the "ASCII digits" link. Closing for now. Let me know if you disagree @ben-page. Happy to reconsider if there's anything @tml and I missed.

**Comment by ben-page** [comment]
Yes, not sure how I missed that. Thanks.
