### ISSUE TITLE
Section 3 (Hosts) should be non-normative

### ISSUE THREAD

**Issue by wanderview** [whatwg/url#122]
We noticed today that this section:

https://url.spec.whatwg.org/#hosts-%28domains-and-ip-addresses%29

Contradicts the URL spec parsing a bit.  The RFC for domains does not allow characters like `&`, but the URL spec parsing does allow it.

So section 3 should probably be marked non-normative.

**Comment by annevk** [comment]
So the reference is already marked informative. The concepts explained are normative though. I mean, that's what a host is for the purposes of this document. I guess I could add a clarifying note.
