### ISSUE TITLE
Allow for a URL record's object to be a MediaSource or MediaStream

### ISSUE THREAD

**Issue by foolip** [whatwg/url#126]
https://url.spec.whatwg.org/#concept-url-object

`URL.createObjectURL` can create `blob:` URLs for two non-Blob objects, MediaSource and MediaStream:
https://w3c.github.io/media-source/#url
https://www.w3.org/TR/mediacapture-streams/#change-log (removed, don't know where it went)

This is needed for https://github.com/whatwg/html/pull/1037 to really work.

**Comment by annevk** [comment]
Yeah I think  the point was to stop spreading this pattern, but I guess that didn't happen...

So they all use the "blob" URL scheme?

**Comment by foolip** [comment]
I thought it was all "blob", but I was wrong:
https://software.hixie.ch/utilities/js/live-dom-viewer/saved/4261

Gecko uses "mediasource" and "mediastream" here. Chromium is all "blob", I assume WebKit does the same, and Edge does for the first two at least. (There's an error for getUserMedia in Edge that I haven't debugged.)

Not sure what to do with that, aligning on using the "blob" scheme everywhere seems like the simplest?

**Comment by annevk** [comment]
Yeah, probably. What a mess.

**Comment by annevk** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1279493 against Gecko.

**Comment by annevk** [comment]
Hopefully this is what you're looking for by the way 😊. Thanks for reporting.

**Comment by foolip** [comment]
Thanks, spec change LGTM!
