### ISSUE TITLE
Basic URL Parse point 1

### ISSUE THREAD

**Issue by alv-c** [whatwg/url#130]
At [Basic URL Parse](https://url.spec.whatwg.org/#concept-basic-url-parser) 

> 1. If url is not given:
>    1. Set url to a new URL.
>    1. If input contains any leading or trailing C0 controls and space, syntax violation.
>    1. Remove any leading and trailing C0 controls and space from input.

Shouldn't 1.2 and 1.3 be independent on if *url* was given?

**Comment by annevk** [comment]
I don't think so. At least, from what I remember setting `pathname` to " " is not identical to setting it to "".

**Comment by alv-c** [comment]
Oh, I see.
So this is implicitly checking if *state override* was given?

From my understanding it currently works like this

Call `basic URL parse` with `input`
> * `url` is a new URL since `url` was not given

> * Removes invalid leading/trailing characters on input

> * (...) (parsing)

> * returns the new `url`

Call `basic URL parse` with `input` and `url`
> * `url` given so don't remove invalid leading/trailing chars wether *state override* was given or not

> * (...) (parsing)*

> returns the modified `url`

Basically, if you pass an `url` to the `basic URL parser` it won't remove leading/trailing characters
even if *state override* was not given.

Correct me if I'm wrong

**Comment by annevk** [comment]
You are not wrong, but the underlying assumption is that url and state override are always passed together.

**Comment by alv-c** [comment]
I see.

That's okay with me then!
