### ISSUE TITLE
Which reality should location.pathname setter match?

### ISSUE THREAD

**Issue by phistuck** [whatwg/url#133]
`location.pathname = "?"`

Results -
Chrome - `%3F`
Firefox - `?`
Internet Explorer 11 (sorry, no Edge here) - throws "The URL is invalid" exception.

Looks like Chrome changed to match the specification only recently, so Chrome and Firefox used to result in `?`.

**Comment by annevk** [comment]
I'm not sure what the result indicates here. Getting the value? If so, Chrome would be correct.

**Comment by phistuck** [comment]
Setting the value.

**Comment by phistuck** [comment]
Setting the value and what it causes to the URL, that is.

**Comment by annevk** [comment]
I think in other browsers this is a difference between `new URL()` / `<a>` and `Location`. I'd prefer keeping the Chrome behavior.

**Comment by annevk** [comment]
@domenic do you happen to know if this is covered in WPT?

**Comment by domenic** [comment]
It doesn't appear to be covered in WPT, but it'd be easy to add such a test: https://github.com/w3c/web-platform-tests/blob/master/url/setters_tests.json#L907-L977

**Comment by annevk** [comment]
@domenic those tests are run for `location`, `<a>`, `<area>`, and `URL` somehow?

**Comment by domenic** [comment]
It looks like only for `URL` currently.

**Comment by annevk** [comment]
Created https://github.com/w3c/web-platform-tests/pull/4036 to also test `<a>` and `<area>`.

**Comment by annevk** [comment]
https://github.com/w3c/web-platform-tests/pull/4038 for setting to "?". Still doesn't test `location` though.

**Comment by annevk** [comment]
I wrote a test for `location.pathname = "?"` and no browser (did not test Edge) appears to be doing a request for `/?`. They all request `/%3F`. I doubt this changed since July so I wonder how OP tested this. In any event, this issue will be closed once that test lands.

**Comment by phistuck** [comment]
1. I went to `http://example.com`
2. Opened the respective Developer Tools feature
3. Entered -
`location.pathname = "?"`
4. Pressed Enter.

Chrome 55 -
`http://example.com/%3F`

Firefox 50.1.0 -
`http://example.com/?`

Internet Explorer 11 -
Exception - `The URL is invalid.`

I double checked (using Fiddler) that it is not a user interface issue, but really what Firefox 50.1.0 sends on the wire. See the attached screenshot.
![image](https://cloud.githubusercontent.com/assets/184400/21642299/fb148e04-d289-11e6-81ed-89b8d6453d1e.png)

**Comment by annevk** [comment]
Hmm yeah, an older Firefox I have does indeed navigate to `/?` too, but Firefox Nightly does not. Guess that was fixed then. So adding the test seems good then.
