### ISSUE TITLE
Url definition should define the fragment as optional

### ISSUE THREAD

**Issue by AutomatedTester** [whatwg/url#134]
Currently it defines that `#` is required while everything else after it is optional in https://url.spec.whatwg.org/#syntax-url

We should make the `#` optional too.

cc @sideshowbarker

**Comment by sideshowbarker** [comment]
@annevk https://github.com/whatwg/url/commit/aedbc12af363c01018d1ab36046bccd74b775104#diff-03b21320f26423640f89c447968191e5L884 seems to be where “optionally” for fragment got dropped. The commit message cites https://github.com/whatwg/url/issues/33 but I don’t see anything there about fragments specifically, I do not recall myself every commenting specifically about it.

**Comment by annevk** [comment]
Thanks! (I thought at some point you needed a separate definition for "absolute URL" that did not include fragments. Either way, I think this is clearly the right fix.)
