### ISSUE TITLE
// in path

### ISSUE THREAD

**Issue by stevenvachon** [whatwg/url#138]
Shouldn't:
```
http://domain.com/path/to//something
```
be normalized to:
```
http://domain.com/path/to/something
```
?

**Comment by domenic** [comment]
Not seeing that behavior in Firefox, Chrome, or Edge: http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=4364

Also a server could serve different contents for the two different URLs, so it seems like it would be bad to perform this kind of normalization. That's normally reserved for DNS-level hostname stuff, from what I understand.

**Comment by stevenvachon** [comment]
Yeah, I can't remember where I'd seen it normalized that way, which is why I'd asked. Perhaps it was Node's `url`.

**Comment by annevk** [comment]
Yeah, that should not happen as those are different URLs.
