### ISSUE TITLE
empty username?

### ISSUE THREAD

**Issue by stevenvachon** [whatwg/url#139]
```
http://:pass@domain/
```
is invalid. These are valid, however:
```
http://user:@domain/
http://user@domain/
http://@domain/
```

**Comment by annevk** [comment]
I don't understand the feedback.

**Comment by stevenvachon** [comment]
I gave examples of valid and invalid URL strings. The ones that are accepted as valid appear to be forgiveness/convenience support while the one rejected as invalid appears to be a valid use case of an empty username and populated password.

**Comment by annevk** [comment]
Credentials are by definition non-conforming per the syntax section. We don't want to spread their use. I don't think we want to do anything here that deviates from what implementations do today, but I'm not sure why you conclude that `:pass@domain` would not parse. Seems that https://url.spec.whatwg.org/#authority-state handles that just fine.

**Comment by stevenvachon** [comment]
I have difficulty reading specifications, including this one. "It's not you, it's me". As a result, I had assumed that the issue was caused by the spec and not [the implementation](https://npmjs.com/whatwg-url).

**Comment by stevenvachon** [comment]
I'm just retarded.

**Comment by annevk** [comment]
@stevenvachon no worries, we're all here to learn. 😊
