### ISSUE TITLE
Convenience method to return an Object

### ISSUE THREAD

**Issue by timruffles** [whatwg/url#143]
People who write Javascript mostly manipulate key-value data via `Object` instances, using their enumerable properties as keys. See lodash (`_.mapKeys`, support in `_.map` etc), jQuery (`$.ajax({ url: "c2.com", method: "get" })`) etc.

Adding `toObject()` as below would make this feel like a natural part of the JS ecosystem:

```
class URLSearchParams {  
  toObject() {
    const o = {};
    for(const [k,v] of this.values()) o[k] = v;
    return o;
  }
}
```

This'd allow for idiomatic composition with other core JS APIs, making for a pleasant developer experience:

```
const queries = ["?name=grace","?name=sussman"]

const hackers = queries
  .map(s => new URLSearchParams(s).toObject())
  .map(q => q.name)
```

The alternative is everyone having to add this boiler-plate in their project, which'd be a shame.

**Comment by annevk** [comment]
This does not handle duplicate keys though.

**Comment by timruffles** [comment]
I'd suggest transforming duplicated values into arrays?

**Comment by timruffles** [comment]
Sorry - fat fingered enter before I'd finished.

I think something like the below would be unsurprising to people:

1. each key value component will be transformed into properties and values of a plain `Object`, `o`
1. if a duplicate key, `K`, is encountered, the current value `V1` of `K` will be replaced with `[V1, V2]`, where `V2` is the second encountered values.
1. if `K` is encountered again, the value array for `K` will be expanded
1. `o` is returned

The returned object will therefore be an object with string keys, and values which are either single strings or arrays of strings, ordered by their position in the query string: `[V1, ... Vn]`.

If there's anything else I can do to help on this issue (Web IDL?) please let me know.

**Comment by timruffles** [comment]
In code:

```
class URLSearchParams {  
  toObject() {
    const o = {};
    for(const [k,v] of this.values()) {
        const currentValue = o[k];
        if(currentValue != null) {
           if(typeof currentValue === 'string') {
             o[k] = [currentValue, v];
           } else {
             currentValue.push(v);
           }
        } else {
            o[k] = v;
        }
    }
    return o;
  }
}
```

**Comment by domenic** [comment]
Part of the whole point of URLSearchParams, ES6 Map, etc. is to move *away* from using objects as maps. I don't think we should make it easy to get back to that error-prone style of programming.

**Comment by timruffles** [comment]
@domenic seems paternalistic? The community knows and loves the object-as-map idiom, and so much of the ecosystem is built around it.

There parts of JS that trip people up, but after teaching 50+ in-person JS classes over the last 4 years I am happy to report object-as-map is nowhere near the top of the list.

**Comment by domenic** [comment]
That's great, in that case you can publish such a library. We shouldn't put it in the standard and ship it with browsers though.

**Comment by timruffles** [comment]
Trying to fight the grain of the community on objects is sad.

Object literals are extremely convenient and will not stop being so because `Map` exists. Therefore 99.9% of JS APIs will accept `Object` *forever*. From that we know that passing the data from `URLSearchParams` into these object-accepting APIs is going to be extremely common.

In addition, your answer above may be a model of concision, but it didn't deign to address any of the points I made:

1. Every JS developer knows how to use objects-as-maps
2. All library APIs expect it - Express, Angular, Ember, Lodash, Underscore etc - and will continue to accept them because of the literal syntax
3. It is not error prone. Citation needed? How many times do people hit a bug with `$.ajax({ ... })`? How many bugs in node core, Angular, etc are around objects-as-maps? Why do smart people write and continue to use libraries like lodash and underscore productively?

Why not simplify the use-case most people will be hitting - `URLSearchParams -> jQuery|Angular|React|Ember` - rather than mandating years of hand-written conversion?

**Comment by annevk** [comment]
@timruffles how about using the iterator that is already exposed?

**Comment by annevk** [comment]
@timruffles I think the other point is that if there are many libraries that offer such an abstraction on  top of `URLSearchParams` we might want to offer it directly, but until such a time it's better for us to wait. All the APIs we add that don't expose something fundamentally new are costly to support over a long period of time, so we need to be a little careful and move more slowly than the library ecosystem can.

**Comment by ersagunkuruca** [comment]
The problem with using objects as maps is, JavaScript objects have special keys. It would be too easy for an attacker to write something like &__prototype__=null or &then=0 to force a certain behaviour. And JS objects will not stop getting more magical properties, because they are not maps already, it won't hurt to add another shiny feature with another magical property.

**Comment by timruffles** [comment]
@annevk iterator is fine, it's just everyone will need to write the content of `toObject()` above.

If API minimisation is the goal here, why is this modelled as a mutable object? Why not just `URLSearchParams.parse` and `URLSearchParams.format`, each expecting/returning `[string, string][]` to make the ordered and potentially duplicated nature of query strings explicit?

**Comment by domenic** [comment]
Yeah, exposing object conversion APIs can be a security risk here, as @ersagunkuruca points out. That was what I was alluding to, but I guess I didn't make it clear enough.

**Comment by domenic** [comment]
Also,

> How many bugs in node core, Angular, etc are around objects-as-maps?

There have been a number of notable security advisories in Node core (not sure if they are public yet) around objects as maps in the HTTP and URL-parsing stacks...

**Comment by timruffles** [comment]
@domenic OK, let me know when you've filed the issue on NodeJS, as it exposes this [precise pattern](https://nodejs.org/api/querystring.html#querystring_querystring_parse_str_sep_eq_options). The Node Security Project probably needs to know too! Here's the [code in question](https://github.com/nodejs/node/blob/a1d3a8db50fcbb3fb0639cb1bd8077d2c290a21b/lib/querystring.js#L221).

**Comment by domenic** [comment]
Yeah, they are already aware.

**Comment by timruffles** [comment]
Righty. I'm happy to close this as I'm sure we'll get the lovely object-literal creation and serialising APIs I suggested in #141 and #142. No user-data danger there! :)

**Comment by jasnell** [comment]
In Node.js core, we are currently looking at moving away from dictionary objects towards using Map now that the perf of Maps has been optimized by v8. The reason is specifically because of the special properties problem. One approach we are investigating to address the object problem is to wrap the Map in a Proxy that would make it act like a dictionary object but there are a number of obvious perf issues with that approach since Proxy objects are not yet fully optimized.

**Comment by timruffles** [comment]
@jasnell interesting - and I assume you're still going to design APIs with `Object`s being passed in. e.g nobody is going to be forced to `fs.newApiForRead("foo.csv", new Map([["encoding", "utf8"]]))` :)?
