### ISSUE TITLE
Doesn't describe how to process url as 'http:///google.com'

### ISSUE THREAD

**Issue by miherlosev** [whatwg/url#145]
There is an url as `scheme:<more than two slashes>/hostname/path`
Example: `http:///google.com`.

Chrome, Firefox, MS Edge can open this url.
IE11, Safari 9 - not.

It is valid url? If ok, then it should be described.

**Comment by annevk** [comment]
It's not a valid URL, but the parser does handle it (normalizes it to `http://google.com` iirc). What makes you think processing is not defined?

**Comment by miherlosev** [comment]
Parsing of `http:///google.com` (as described in https://url.spec.whatwg.org/#url-parsing):
1)scheme state (buffer - `http`)
2)path or authority state
3)authority state
> then decrease pointer by the number of code points in buffer plus one, set buffer to the empty string, 
Maybe it should be `increase`?
`c` now is '/' and if I will descrease the ponter then I get ':' symbol again.

**Comment by annevk** [comment]
It seems like you missed step 2.3 of https://url.spec.whatwg.org/#scheme-state at least?

**Comment by miherlosev** [comment]
Ok
