### ISSUE TITLE
UTF-16 queries

### ISSUE THREAD

**Issue by achristensen07** [whatwg/url#149]
Currently in query state we see this:
"If url is not special or url’s scheme is either "ws" or "wss", set encoding to UTF-8."
WebKit also uses UTF-8 if the encoding is UTF-7, UTF-16, or UTF-32 (big-endian or little-endian).  I verified existing behavior in Safari, Chrome, and Firefox for UTF-16.  I verified existing behavior in Safari and Chrome for UTF-32.  
I think we should add "...or encoding is UTF-7, UTF-16, or UTF-32..."

**Comment by annevk** [comment]
UTF-7 and UTF-32 don't exist per https://encoding.spec.whatwg.org/ and most implementations are aligned with that now. Turning UTF-16 into UTF-8 happens per step 7 of https://url.spec.whatwg.org/#concept-basic-url-parser which invokes https://encoding.spec.whatwg.org/#get-an-output-encoding.

So I think this is already good as-is.

**Comment by achristensen07** [comment]
I agree.  I had overlooked that
