### ISSUE TITLE
How should URLs containing unicode zero width spaces be treated?

### ISSUE THREAD

**Issue by dd8** [whatwg/url#151]
URLs containing zero width spaces result in very hard to track down problems, because the zero width spaces are not displayed in Unicode confirming tools (you need a hex editor or similar to see the zero width spaces)

For example, these two URLs are different, although they're displayed identically:

https://github.com/whatwg/url/commits
https://github.com/what​wg/url/commits

The second one has a zero width space between what and wg and gives a 404

**Comment by dd8** [comment]
There's been a bit of mangling by the Markdown editor when this was saved - the ZWSP has been converted to the UTF-8 sequence %e2%80%8b, though the two URLs display identically in Chrome. You can reproduce in a text editor on Windows by copy and pasting the U+200B character from the Character Map applet into the middle of a URL in an HTML file.

**Comment by annevk** [comment]
Converting it to `%e2%80%8b` is what's supposed to happen per the specification. It doesn't really special case this one way or another. https://url.spec.whatwg.org/#security-considerations has some advice on rendering and some have suggested we should expand that, but there's not much interest in that thus far.

**Comment by annevk** [comment]
Going to close this issue since zero width spaces are not unique in presenting a challenge when displaying URLs.
