### ISSUE TITLE
Disambiguate URL strings and records more

### ISSUE THREAD

**Issue by annevk** [whatwg/url#157]
@domenic how about we suffix all syntax-related terms with "string"? We can also start using "URL string" as the `for=""` value.

I also want to change `<dfn for=url>URL</dfn>` to `<dfn>URL</dfn>` and `<dfn for=urlsyntax>URL</dfn>` to `<dfn>URL string</dfn>` together with this, as it doesn't make much sense bikeshed-wise for the main term to have a `for=""` attribute value as I understand things today. (I didn't really get the whole setup initially.)

That might cause some downstream pain.

**Comment by domenic** [comment]
That sounds super-great!
