### ISSUE TITLE
Encode curly braces in path

### ISSUE THREAD

**Issue by valenting** [whatwg/url#16]
Most UAs seem to encode curly braces in the URLs path.
https://bugzilla.mozilla.org/show_bug.cgi?id=1152455#c6

Moreover, the reference implementation at http://intertwingly.net/projects/pegurl/liveview.html#http%3A%2F%2Fhost.com%2Fpath{} also seems to indicate that curly braces should be encoded.

**Comment by annevk** [comment]
I got confused because that bug was closed WONTFIX. But the distinction is that browsers do it for path, but not for query, and we'd like the latter to not be affected.

So it seems all browsers except for Safari encode `{` and `}`. Makes sense to copy that I suppose.

**Comment by annevk** [comment]
So as far as I can tell this also applies to the username/password components so we should just add these to the default encode set.
