### ISSUE TITLE
path /.

### ISSUE THREAD

**Issue by nlevitt** [whatwg/url#161]
Surprised to see the reference implementation leaves the trailing dot here. Conflicts with chromium and my expectation. Is it correct?
![screen shot 2016-11-03 at 17 56 45](https://cloud.githubusercontent.com/assets/423176/19991024/62cb98c4-a1ef-11e6-8db7-d736617e2b37.png)

**Comment by domenic** [comment]
It appears the reference implementation deployed to that URL is outdated. Per spec (and verified with jsdom/whatwg-url) the trailing dot is removed.

**Comment by nlevitt** [comment]
Thanks! It'd be nice to have the latest deployed, needless to say :)

**Comment by annevk** [comment]
Duplicating this to #162.

The main problem here is that we don't really do a reference implementation anymore. Perhaps the best I can do is to just 410 that URL space.
