### ISSUE TITLE
SIngle quotes in queries should be percent encoded?

### ISSUE THREAD

**Issue by Manishearth** [whatwg/url#172]
Both Firefox and Chrome produce `"http://foo.bar/?%27"` on `(new URL("http://foo.bar/?\'")).href`. Spec does not include single quotes in the encode set used for queries.

Chrome additionally encodes single quotes within hostnames, but Firefox does not.

Should we update the spec here?

cc @annevk @SimonSapin @domenic

**Comment by Manishearth** [comment]
Firefox and Chrome also consistently percent-encode the whitespace in

```js
u = new URL("http://foo.bar?query")
u.search = "qu\r\n\tery";
console.log(u.href);
// "http://foo.bar/?qu%0D%0A%09ery"
```

though the spec does not ask us to do this.

There is a test for this at https://github.com/w3c/web-platform-tests/blob/be5820ecd36650bff4728208629553931fd42ec2/url/setters_tests.json#L1053 which both presumably fail.

**Comment by Manishearth** [comment]
Looks like Safari/Edge agree with the spec for the single quote.

For whitespace, Safari agrees with the spec. Edge just includes the whitespace unencoded into the url.

Edge seems to be completely broken wrt to setters like `url.search`. As far as I can tell it just does a string substitution there. For example, `u.search = "#"` will work, but if you try to view the url it will throw an error (unlike other browsers which set the search to the percent encoded form of the hash).

Since there's no cross browser agreement here I guess Firefox and Chrome should be updated to follow the spec here?

**Comment by Manishearth** [comment]
Gecko bug for single quotes at https://bugzilla.mozilla.org/show_bug.cgi?id=1324246 , and for whitespace at https://bugzilla.mozilla.org/show_bug.cgi?id=1324247

**Comment by Manishearth** [comment]
We also have `new URL("file:///c|/")` percent encoding the pipe instead of treating it as a colon based on https://url.spec.whatwg.org/#windows-drive-letter. This is agreed upon across browsers

(gecko bug at https://bugzilla.mozilla.org/show_bug.cgi?id=1324251)


Overall I would like to know if any of these mismatches merit a spec fix. It seems like the drive letter thing is deliberate and the browsers should just update, but I'm not sure.

**Comment by annevk** [comment]
Spaces is #125.

What should be encoded in query is also #18.

File URLs are rather tricky and in contemporary browsers the parser switches on the platform (i.e., Windows and macOS will produce different results).

There's no good rule for what should change to what unfortunately.

**Comment by annevk** [comment]
Going through this again I don't really see anything actionable. Is there something you want me to look into, taking my previous comment into account?

**Comment by Manishearth** [comment]
Nah, mostly wanted to point out that there's a lot of discrepancy in what browsers do and perhaps we should change the spec.
