### ISSUE TITLE
empty auth vs no auth -- same?

### ISSUE THREAD

**Issue by stevenvachon** [whatwg/url#181]
`http://:@domain/` (empty username and password)
vs
`http://domain/`

Are they the same?

**Comment by Khaledrahat** [comment]
Awesome and nice work

**Comment by Khaledrahat** [comment]
Who to   Easy to earn

**Comment by annevk** [comment]
@stevenvachon the former sets the password to the empty string. Which means it serializes differently. What's the context for the question?

**Comment by stevenvachon** [comment]
If they are the same, should they not serialize the same? Just as these two do:
```
http://domain/?va r=va+lue
```
```
http://domain/?va%20r=va lue
```

I'm writing a library that, among other things, provides a means of [comparing URLs for relation](https://github.com/stevenvachon/specurl#relationurl1-url2).

**Comment by stevenvachon** [comment]
With the current public API of this standard, having no username and password is the same as having an empty username and password.

```js
url = new URL("http://domain.com/")
url.username==="" && url.password===""  //-> true
```

```js
url = new URL("http://:@domain.com/")
url.username==="" && url.password===""  //-> true
```

**Comment by domenic** [comment]
> We could maybe also normalize the serialization, but that would require impl changes.

Hmm, would it? Assuming `new URL("http://:@domain.com/").href` is the correct test, that yields:

- Firefox: TypeError
- Chrome: "http://domain.com/"
- Edge: Error

**Comment by annevk** [comment]
Thanks for checking. It does seem like the standard is bogus.
