### ISSUE TITLE
Splicing URLSearchParams?

### ISSUE THREAD

**Issue by stevenvachon** [whatwg/url#183]
Is there an official proposed way of doing this? So far, I'm doing this:
```js
const url = new URL("http://domain?var=1&var=2&var=3");
const params = Array.from(url.searchParams);

// There is no `.clear()`
for (let param of url.searchParams) {
  url.searchParams.delete( param[0] );
}

params.forEach( function(param) {
  if (someFilter(param)) {
    url.searchParams.append( param[0], param[1] );
  }
});
```

**Comment by annevk** [comment]
There is not.

**Comment by stevenvachon** [comment]
Ok. Should there be?

**Comment by annevk** [comment]
That depends on whether the pattern is common. But you can simplify the above quite a bit:
```js
const url = new URL("http://domain?var=1&var=2&var=3");
url.searchParams.forEach((value, name) => {
  url.searchParams.delete(name);  
  if(someFilter(name, value)) {
    url.searchParams.append(name, value);
  }
})
```
It's a little unclear to me why the `forEach()` callback gets the arguments in such a weird order though.

**Comment by stevenvachon** [comment]
Thank you. We cannot use that code yet in Node.js, though, because of https://github.com/nodejs/node/issues/10481

Also, `URLSearchParams.prototype.forEach` is probably following `Array.prototype.forEach` which has `value, i, array` arguments.

**Comment by annevk** [comment]
My simplification doesn't work since what you iterate over is live per https://heycam.github.io/webidl/#es-forEach. But you could build up a new object or some such and then use it after the loop.

**Comment by annevk** [comment]
In any event, I don't think this warrants a special API.
