### ISSUE TITLE
URLSearchParams delete and iterator ambiguity

### ISSUE THREAD

**Issue by jasnell** [whatwg/url#188]
The appears to be a slight ambiguity in the API for `URLSearchParams` as reported in Node.js issue https://github.com/nodejs/node/issues/10481.

Specifically, given the following test case:

```js
const url = new URL("http://domain.com/?var1=value&var2=");
const params = Array.from(url.searchParams);

// There is no `.clear()`
for (let param of url.searchParams) {
  console.log( param[0] );
  url.searchParams.delete( param[0] );
}
```

In Node.js, the iterator that is created is live... meaning that the call to `url.searchParams.delete()` modifies the iterator itself and the only key that is output to the console is `var1`. This behavior *matches* the behavior implemented in Firefox.

Chrome, on the other hand, appears to copy the data on creation of the iterator, causing both `var1` and `var2` to be output to the console (which, I believe, is what users would most often expect to happen).

Unless I'm simply not seeing something in the URL spec, it does not appear to be clear which is the correct behavior.

**Comment by annevk** [comment]
Should be covered by IDL. Seemed live last I looked. @tobie?

**Comment by jasnell** [comment]
That was my assumption when reading through the first few times while implementing but it would be good to get clarification :-)

**Comment by domenic** [comment]
In particular see https://heycam.github.io/webidl/#es-iterators and https://heycam.github.io/webidl/#dfn-default-iterator-object

It looks like step 7 of the next() method re-fetches the list of values each time so live does indeed seem more correct.

I'll report a Chrome bug.

**Comment by sleevi** [comment]
Yeah, Chrome's making an explicit copy ( https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/dom/URLSearchParams.cpp?rcl=0&l=16 ), so it'd be good to file a Chrome bug.

**Comment by jasnell** [comment]
Thank you all for the clarification! I'll update the Node.js issue accordingly! Will close this issue!
