### ISSUE TITLE
internal class (or type) "URL"

### ISSUE THREAD

**Issue by stevenvachon** [whatwg/url#191]
```js
Object.prototype.toString.call( new URL("http://domain.com/") )
//-> [object URL]
```

Related: https://github.com/nodejs/node/issues/10554

**Comment by domenic** [comment]
What is the issue here?

**Comment by stevenvachon** [comment]
It was suggested in the linked Node.js issue that the type be defined in the spec. Currently, Node.js is the only one that returns `[object Object]` with the above code.

**Comment by domenic** [comment]
This is already defined in the spec, because the spec uses Web IDL.

**Comment by stevenvachon** [comment]
Thank you.
