### ISSUE TITLE
Maybe ensure there is a path item after the Windows drive letter path item

### ISSUE THREAD

**Issue by zcorpan** [whatwg/url#193]
https://url.spec.whatwg.org/commit-snapshots/26caf4927f6c95ba4f56d701ecd8a52fdb664982/#path-state

> Otherwise, if buffer is not a single\-dot path segment, run these subsubsteps:​
> 
> If url’s scheme is "file", url’s path is empty, and buffer is a Windows drive letter, run these subsubsubsteps:​
> 
> If url’s host is non\-null, syntax violation\.
> 
> Set url’s host to null and replace the second code point in buffer with ":​"\.
> 
> This is a \(platform\-independent\) Windows drive letter quirk\.
> 
> Append buffer to url’s path\.

From https://github.com/w3c/web-platform-tests/pull/4382#discussion_r94379014

Parsing `//d:` with base `file:///C:/a/b` (or just parsing `file:///d:`) currently gives a single string "d:" in the path, so serializing does not include a trailing slash. Maybe it should?

http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4769

<dl>
<dt>No trailing slash:</dt>
<dd>Edge 13 and IE 9..11, Safari 9.1 and TP (WebKit 12603.1.16), Firefox Nightly 52.0a1 (2016-11-14) and 53.0a1 (2017-01-02) on Mac OS X, Chrome Canary 57.0.2970.0 on Mac OS X</dd>
<dt>With trailing slash:</dt>
<dd>Chrome 50.0 on Windows 10, Firefox 44.0 on Windows 10</dd>
</dl>

(I don't know if there is a difference between platforms here for Chromium and Gecko, or if it changed between recent versions.)

**Comment by annevk** [comment]
Aligning with Edge seems good. Let's close this.
