### ISSUE TITLE
search params preference for "+" over "%20"

### ISSUE THREAD

**Issue by stevenvachon** [whatwg/url#198]
... since they're easier to read.

```
http://domain/dir name/?va r=va lue
```
should parse as:
```
http://domain/dir%20name/?va+r=va+lue
```
instead of:
```
http://domain/dir%20name/?va%20r=va%20lue
```
by default

**Comment by annevk** [comment]
This is a duplicate of #18. I don't disagree that it would be nice if they worked the same way, but I doubt we're going to get convergence there.
