### ISSUE TITLE
"." and ".." filenames stripped

### ISSUE THREAD

**Issue by stevenvachon** [whatwg/url#208]
```
http://domain/.
http://domain/asdf/..
```
currently parse to:
```
http://domain/
http://domain/
```
but the `.` and `..` filenames/dirnames should be preserved as it's possible for them to exist. `./` and `../` are different.

**Comment by annevk** [comment]
https://quuz.org/url/liveview.html#http://x/.
https://quuz.org/url/liveview.html#http://x/..

I can't find a browser that agrees with you.

**Comment by stevenvachon** [comment]
That doesn't mean that the browsers are correct, especially when they're already inconsistent. It's very possible for files and directories to have these names, and should be left up to the server to decide what to do.

**Comment by domenic** [comment]
The details of URLs mapping to filenames on the server is not governed by the URL standard. The point of the URL standard is to determine what URL gets sent to the server, and as @annevk points out, no browser will send those to the server.

If you want to request a file named . or .. on the server, you can use some other kind of system besides the naive one (e.g., `?filename=.`).

**Comment by stevenvachon** [comment]
the file might be ".filename", not just "."
