### ISSUE TITLE
What is a globally unique identifier?

### ISSUE THREAD

**Issue by SimonSapin** [whatwg/url#21]
https://url.spec.whatwg.org/#origin says, in some cases, to:
> return a new globally unique identifier

What does this mean? Is it a string with randomly-generated hexadecimal digits like `{21EC2020-3AEA-4069-A2DD-08002B30309D}`? https://en.wikipedia.org/wiki/Globally_unique_identifier Either way the spec should define this, or refer to something that does.

**Comment by annevk** [comment]
It's one of the possible values of an origin per the HTML Standard which defines the origin concept. I assume @Hixie would describe it as a term of art.

**Comment by SimonSapin** [comment]
I think the part I was missing is that "globally unique identifier" seems to be (is it?) the same as "opaque identifier", that HTML defines as:

>    Internal values, with no serialisation, for which the only meaningful operation is testing for equality.

**Comment by tml** [comment]
Pardon me for jumping in, but I believe that the normative reference here is RFC 6454 ("The Web Origin Concept"), section 2.3:

   A globally unique identifier is a value that is different from all
   other previously existing values.  For example, a sufficiently long
   random string is likely to be a globally unique identifier.  If the
   origin value never leaves the user agent, a monotonically increasing
   counter local to the user agent can also serve as a globally unique
   identifier.

**Comment by annevk** [comment]
The RFC is slowly being phased out as it doesn't deal well with URLs and has an outdated definition of the header.

@SimonSapin no, opaque identifier is a type, not a value.

**Comment by SimonSapin** [comment]
> @SimonSapin no, opaque identifier is a type, not a value.

I don’t understand what *being a type* or *being a value* means in this context. And which one is *globally unique identifier*?

**Comment by Hixie** [comment]
A globally-unique identifier is just that. An identifier that's globally unique. There's no deep meaning here. It's opaque, in that you can't see its actual value. When in doubt, assume that the text means what it says, and that's there's no magical words being used. :-)

**Comment by annevk** [comment]
@SimonSapin it seems like your issue is with the HTML Standard. URL is just using HTML's terminology to define the origin of a URL.
