### ISSUE TITLE
Is failure ever not a syntax violation?

### ISSUE THREAD

**Issue by domenic** [whatwg/url#219]
Some recent patches have changed "return failure" to "syntax violation, return failure". Wouldn't it be simpler to just say that failure is always a syntax violation?

**Comment by annevk** [comment]
I kinda like that this is more explicit. But maybe after we reduced the confusion a bit we can figure out how to get there.

**Comment by annevk** [comment]
FWIW, I consider this addressed by #228, but will leave it open for now since it seemed you might disagree still.

**Comment by domenic** [comment]
Right. So for example https://url.spec.whatwg.org/#concept-ipv4-parser step 9 will cause failure, but not a validation error. Keeping these two in sync is frustrating for implementations (that track conformance checking) and makes the spec harder to read. It would be much better IMO if all "validation error, return failure" steps were turned into simply "return failure". Then "validation error" would be reserved for situations that are invalid but do not cause parsing failures, allowing people to more easily distinguish what such situations are. Right now mostly it looks redundant with failure; you have to really search to find instances where there's a validaiton error but no failure.

**Comment by annevk** [comment]
Then you could no longer use "validation error" as a signal for all invalid input. When the parser returns failure, it's also technically a validation error.

**Comment by domenic** [comment]
Yes. I think that should be part of the definition of when validation error occurs, and not sprinkled throughout the parser explicitly.

**Comment by annevk** [comment]
I'm not sure I understand.

**Comment by domenic** [comment]
So for example, https://url.spec.whatwg.org/#url-parsing step 2 could be modified to add "validation error".

Or, you could just redefine "validation error" like

> A validation error indicates a non-fatal mismatch between input and valid input. Along with parser failures, it it helps define the valid URL string concept.

or similar

**Comment by annevk** [comment]
I didn't add it to step 2 since I assumed it would have already been flagged by then. And there's places that invoke the base URL parser directly so it's not like we can have a catch-all.

**Comment by domenic** [comment]
The entire point of this issue is to remove the need to flag it everywhere and keep it in sync. If we can do that in any way, then I'm happy. Otherwise it's just buggy, as I pointed out in the IPv4 parser case, and I'm going to need to make whatwg-url depart from the spec to avoid the maintenance cost.

Another example solution would be to define "fail" to mean "validation error, return failure" and then use that everywhere you currently use "return failure".

**Comment by achristensen07** [comment]
I think we should just define a "syntax violation" as when the canonicalized URL string is not exactly equal to the input and leave it to implementers to figure out how they want to check that.  Right now the spec is missing mentioning many syntax violations.  I implemented a parser that has 67 references to syntaxViolation in https://trac.webkit.org/browser/trunk/Source/WebCore/platform/URLParser.cpp because I wanted to be efficient and use the same ref-counted immutable String object if I can, but a valid parser could parse into a different structure and have the serialization always create a string of some sort.  Such a parser would not need to worry about syntax violations unless the user agent wanted to report syntax violations, and many user agents don't.

**Comment by annevk** [comment]
@achristensen07 that would mark something like `https://example.com/test/../` as invalid, or even `..` against a base URL of sorts.

**Comment by achristensen07** [comment]
https://example.com/test/../ wouldn't be invalid, it would just need to be serialized to a different string than the input, https://example.com/ and I don't think that needs to be explicitly stated in the spec containing the parsing and serializing algorithms.
Maybe we are misunderstanding each other.

**Comment by annevk** [comment]
You said above that you think that it's a "syntax violation" when the canonicalized URL does not match the input. I gave a counter example where that should not be the case.

The URL Standard defines parsing and serialization, but it also defines valid URL strings. Whenever the parser parses something that is not a valid URL string, that's signified through a "validation error" (renamed recently from "syntax violation"). A couple reasons why we do that are outlined here: https://url.spec.whatwg.org/#writing.

**Comment by achristensen07** [comment]
Ok, I guess a user agent wouldn't report ".." as invalid input, but it would require a different string when canonicalized.  Makes sense.  My user agent doesn't report invalid input, so I didn't notice the difference.

**Comment by annevk** [comment]
@domenic I looked at your claim that the IPv4 parser case didn't report a validation error for the case mentioned in step 9, but it does so in step 8. I don't see the problem.

**Comment by zcorpan** [comment]
So in https://url.spec.whatwg.org/#ipv4-number-parser step 5 returns failure but does not set *validationErrorFlag* (when *R* is 10). Which is intentional, right? Since host parsing `example.org` will also parse as an IPv4 address, and then https://url.spec.whatwg.org/#concept-ipv4-parser step 6.3 returns *input* in that case.

Within the basic URL parser, steps that return failure but do not say "validation error":

https://url.spec.whatwg.org/#hostname-state

2.3 and 3.4:
> If host is failure, then return failure.

Host parsing seems to take care of validation error for any failure.

https://url.spec.whatwg.org/#file-host-state

1.3.2

> If host is failure, then return failure.

Same.

**Comment by annevk** [comment]
Yeah, that is why the validationErrorFlag was introduced. To avoid flagging errors in non-IPv4 input.

**Comment by domenic** [comment]
I guess I am not making any progress here. In the end what this means is that implementing validation errors is too much of a maintenance burden (because of all the duplication with parse failures) so probably we will just not implement them in whatwg-url. The support is already spotty because of problems like these so probably best to just remove them. Happy to close this issue since I'm not changing any minds.

**Comment by annevk** [comment]
I don't see how it's a maintenance burden. It's pretty clear when you need to flag them. The only feedback I got at some point was that we should maybe expose them API-wise (if I wanted to implement URL validation through whatwg-url), but I'm not sure that's something everyone wants to do.

(It would be a shame if you removed them though and implementing a URL validator in JavaScript required a fork.)

**Comment by domenic** [comment]
If I were implementing a JS URL validator I would use the grammar in the writing section anyway.

**Comment by annevk** [comment]
Sigh.
