### ISSUE TITLE
URLSearchParams constructor test has a bug

### ISSUE THREAD

**Issue by annevk** [whatwg/url#220]
See https://github.com/w3c/web-platform-tests/pull/4523#pullrequestreview-18979383.

**Comment by TimothyGu** [comment]
WebKit, which has already implemented the new constructor, also shows this issue in their [test suite expected file](https://trac.webkit.org/browser/trunk/LayoutTests/imported/w3c/web-platform-tests/url/urlsearchparams-constructor-expected.txt?rev=210946):

```
18	FAIL Construct with object with + assert_array_equals: property 0, expected " " but got "+"
```
