### ISSUE TITLE
Empty hashes

### ISSUE THREAD

**Issue by stevenvachon** [whatwg/url#221]
```
http://domain/path/to/file#
```
is not any different from
```
http://domain/path/to/file
```
according to this spec, since both have an empty string value for the `hash` key.

**Comment by annevk** [comment]
They are. URL's fragment is the empty string for the former, and null for the latter. The `hash` API doesn't expose the difference due to legacy compatibility.

**Comment by stevenvachon** [comment]
Doing this sucks, though:
```js
const hash = url.href.indexOf("#")===url.href.length-1 ? "#" : url.hash;
```

**Comment by annevk** [comment]
Yeah, do you hit this a lot? It's a problem with `search` too. I suppose we could offer a simple boolean API for both that exposes the remaining differences. `hasHash` and `hasSearch` that operate on the nullness of the underlying primitives.

**Comment by stevenvachon** [comment]
Empty `search` is less of a problem for me. Empty fragments, however, are often used in `<noscript>` situations to produce interactive content.

`hasHash` seems like bloating of the API, but I realize that I'm not as well versed in all of the edge cases.

**Comment by annevk** [comment]
I think it's either something like that or nothing.

**Comment by stevenvachon** [comment]
Ok. Well, it may not be important enough to add something that looks a bit weird if it is rarely used. I've gotten by in the past using HTML `id` attributes and/or checking if `getAttribute("href") === "#"`. My code above is for a pretty specific URL optimization library.

This issue is here for a future user search.
