### ISSUE TITLE
Setting path to base's path seems wrong

### ISSUE THREAD

**Issue by domenic** [whatwg/url#231]
When reviewing https://github.com/whatwg/url/pull/225 I noticed this, and I imagine it's widespread:

> Set url’s host to base’s host, **url’s path to base’s path**, and url’s query to base’s query.

A strict reading of this is that it sets url's path to the same list as base's path, so any future modifications to url's path get reflected in the base URL. That seems pretty bad. It should instead be a copy, right?

**Comment by annevk** [comment]
Yeah.

**Comment by annevk** [comment]
It seems hard to test since we always pass the base URL using a copy.
