### ISSUE TITLE
Explicitly list non-goals

### ISSUE THREAD

**Issue by gsnedders** [whatwg/url#233]
There still seems to be a fair bit of confusion as to what the goals are, and whether they cover things like the address bar. It'd be good to at least explicitly call out the address bar, and maybe one or two other things too?

**Comment by annevk** [comment]
What are the other things? I'm surprised folks still think the address bar has influence one way or another.

**Comment by annevk** [comment]
@gsnedders ping!

**Comment by gsnedders** [comment]
Uh, good question. Pretty sure I had some other part of UI in mind, but I've forgotten now.

**Comment by annevk** [comment]
So also, I had a conversation the other day that suggests there might be interest in standardizing display of domain names, as it affects both the browser but also applications that run on top of it. So not everything from the address bar is necessarily out-of-scope (and we already have some display guidelines).

If we have a good way to say it though mentioning how URL parsing as seen in the address bar has no influence on the URL parser might be worth doing.

**Comment by gsnedders** [comment]
> What are the other things? I'm surprised folks still think the address bar has influence one way or another.

I guess I was thinking about any means of navigating the document, which is more an HTML concern than URL (e.g., back/forward, bookmarks, etc.)
