### ISSUE TITLE
IDNA Nontransitional_Processing

### ISSUE THREAD

**Issue by annevk** [whatwg/url#239]
@achristensen07 in https://github.com/whatwg/url/issues/110#issuecomment-261694624 you mention that WebKit uses Nontransitional_Processing (URL Standard currently requires Transitional_Processing).

However, it appears that this is not universally done:
```
const url = new URL("https://x/")
url.host = "faß.de"
url.host // fass.de (Transitional) rather than xn--fa-hia.de (Nontransitional)
```
That's a bug then I assume?

I have tests at https://github.com/w3c/web-platform-tests/pull/4504 but there's too many of them to easily digest (or run quickly). I haven't really figured out a strategy yet for how to tackle that problem.

In any event, with both WebKit/Safari and Firefox wanting Nontransitional_Processing, I think we should go for it and change that in the standard. And at least test faß.de for now in a less convoluted way.

**Comment by annevk** [comment]
I also noticed that Safari applies some IDNA logic to hosts of non-special URL setters.

Firefox returns the ToUnicode result unfortunately.

Chrome fails badly. Didn't test Edge. I suspect all four browsers will need bugs for this one.

**Comment by jasnell** [comment]
The Node.js implementation is using nontransitional also...

```js
> var u = new url.URL('https://x/');
undefined
> u.host = 'faß.de'
'faß.de'
> u.host
'xn--fa-hia.de'
>
```

**Comment by annevk** [comment]
@sleevi @jungshik could you comment with regards to Chrome whether this is a change you'll make given that Firefox and Safari appear to have done so successfully?

@travisleithead could you comment with regards to Edge? (Or suggest someone else?)

**Comment by sleevi** [comment]
@annevk This is another one where @jungshik is better qualified to speak to any plans to move, and what any (internal to Chrome) risks there may be.

**Comment by annevk** [comment]
* https://bugs.webkit.org/show_bug.cgi?id=168591
* Firefox returning ToUnicode is a known bug
* https://bugs.chromium.org/p/chromium/issues/detail?id=694157
* https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11009037/
