### ISSUE TITLE
Typo in file state

### ISSUE THREAD

**Issue by std4453** [whatwg/url#246]
https://url.spec.whatwg.org/commit-snapshots/97563cb4e6430883ca3538def339282d77989ece/#url-parsing

> c and the first code point of remaining are not a Windows drive letter

Shouldn't it be "c and the first two code points of remaining are not a Windows drive letter"? Since a Windows drive letter is consisted of two code points.

**Comment by annevk** [comment]
No worries, thanks for stopping by. 😊
