### ISSUE TITLE
Provide means to "strip query"

### ISSUE THREAD

**Issue by marcoscaceres** [whatwg/url#247]
I find code like the below around the place: 

```JS
function stripQuery(url) {
  return url.split("?")[0];
}
```

I'm wondering if the spec could just provide a means to get a URL without query params (and I guess the same for hash).

**Comment by annevk** [comment]
Would you want a string as return value? How do libraries encode this typically? In a way this seems like something you would pass to `toString()` as argument, but maybe that's only logical for numbers?

**Comment by annevk** [comment]
By the way, you can just set search and hash to the empty string if you have an actual URL object. So given that I'm not actually sure this needs addressing.

**Comment by felixfbecker** [comment]
Why not simply do
```ts
Object.assign(new URL('http://github.com/hello/world?q=v'), { search: '' }).href
"http://github.com/hello/world"
```
it's a one-liner, I don't think options for stripping various components should be added when all you need to do is assign the component you want to strip an empty string.

**Comment by marcoscaceres** [comment]
Sure, that strips the query - but that looks like quite a hack, which doesn't work for other cases, like:

```JS
Object.assign(new URL('http://github.com/hello/world?q=v'), { search: 'test' }).href
"http://github.com/hello/world" // 0_o
```
Which might catch people out.

**Comment by felixfbecker** [comment]
Uhm, why does it look like a hack? Assigning a different string to `search` modifies the query, that is clearly speced. Your example works totally fine (Chrome):
```js
Object.assign(new URL('http://github.com/hello/world?q=v'), { search: 'test' }).href
"http://github.com/hello/world?test"
```

**Comment by marcoscaceres** [comment]
My bad, must have screwed something up when I tested it in Firefox. You are right, it works.

**Comment by annevk** [comment]
So can this be closed or is there a case that isn't addressed still?

**Comment by marcoscaceres** [comment]
I think it's fine to close - unfortunately, I don't have time rn to do the research that's needed to see if we actually need something standard (plus there are plenty of simple work arounds).
