### ISSUE TITLE
Large ports of non special urls

### ISSUE THREAD

**Issue by achristensen07** [whatwg/url#257]
Old safari would allow large ports, and URL.port of urls like nonspecial://host:65537/ would be capped at 65535, but toString would return the initial given string. I admit this was strange, but changing it found somebody who was relying on our strange behavior, as all URL changes do. I'm curious to know other browsers' views on large ports of custom schemes.

**Comment by annevk** [comment]
I think the problem is that non-Safari doesn't support username/password/host/port for non-special URLs (yet). They parse all those components as part of the path.

How in particular did they rely on this? Did they rely on `port` returning something or the URL not resulting in failure?

**Comment by achristensen07** [comment]
They were not using URL.port, relying on the parsing not failing, and they must have been re-parsing the string themselves to get the numeric identifier after the colon

**Comment by annevk** [comment]
Okay, that sounds like another case of relying on the non-Safari way of parsing which is much less useful overall and less aligned with RFC 3986. Sigh.

Is this something we need to fix?

One possible option is that we use a "BigInt" for non-special URL ports and only cap to 16-bit for special URLs.

@SimonSapin might have thoughts too.

**Comment by SimonSapin** [comment]
Is it only Safari doing this? Is only one site known to rely on it?

**Comment by achristensen07** [comment]
The compatibility issue was from only one company's web content ecosystem used by a few apps, but they're changing their content.  I think we should keep the port as conceptually limited to 16-bit integers and fail to parse any ports larger than 65535, regardless of scheme.  This way non-JavaScript URL implementations can do something reasonable with the port.  Mine returns std::optional<uint16_t>, but other languages have similar constructs.  So I think we should keep the spec as-is and add a test verifying that parsing asdf://host:65536/ fails.

**Comment by annevk** [comment]
I created a web-platform-tests PR.
