### ISSUE TITLE
Empty or null host when scheme is "file:"?

### ISSUE THREAD

**Issue by rmisev** [whatwg/url#258]
In the ["file host state"](https://url.spec.whatwg.org/#file-host-state) there are steps where <var>host</var> is set to the empty string, but in the ["path state"](https://url.spec.whatwg.org/#path-state) at some step <var>host</var> is tested for null (and also set to null).

Because of this difference parser will report [validation error](https://url.spec.whatwg.org/#validation-error) for such valid URL:
`file:///C:/path`
In the ["file host state"](https://url.spec.whatwg.org/#file-host-state) <var>host</var> is set to empty string, but in the ["path state"](https://url.spec.whatwg.org/#path-state): "If url’s host is non-null, validation error."

So I think, <var>host</var> must be set to (and tested for) the same value in both cases; Maybe this value must be null?

**Comment by annevk** [comment]
Making it consistently the empty string would be best I think, though in theory it does not matter much for file URLs since they don't have the serialization difference.

**Comment by rmisev** [comment]
I think by definition empty host is a [valid opaque host string](https://url.spec.whatwg.org/#valid-opaque-host-string), used for non-special schemes. So I guessed null. But maybe I am wrong?

**Comment by annevk** [comment]
@rmisev I mostly see it as empty meaning the URL starts with // after the scheme and null meaning the URL starts with a path. I guess we should update https://url.spec.whatwg.org/#scheme-relative-file-url-string to also allow the empty string.

**Comment by rmisev** [comment]
It makes sense to use an empty string (also used in RFC 3986). But I don't think https://url.spec.whatwg.org/#scheme-relative-file-url-string must be changed, because second item allows empty host, i.e.:
> must be "//", followed by ... a path-absolute-URL string.

I think must be changed URL's host definition https://url.spec.whatwg.org/#concept-host (or maybe https://url.spec.whatwg.org/#concept-url-host). Currently this definition allows empty host but only as opaque host, but opaque host is for non-special URLs (see note at https://url.spec.whatwg.org/#opaque-host). So changed definition:
- A <b>host</b> is a domain, an IPv4 address, an IPv6 address, <del>or</del> an opaque host, <ins>or an empty host</ins>. Typically a host serves as a network address, but it is sometimes used as opaque identifier in URLs where a network address is not necessary.

A term <b>empty host</b> can be used for non-special and file URL's; then empty string (zero URL units) can be excluded from opaque host definition https://url.spec.whatwg.org/#valid-opaque-host-string  - so opaque host means not empty.

What do you think about such changes?

**Comment by annevk** [comment]
That sounds reasonable.
