### ISSUE TITLE
Sort URLSearchParams prior to stringification

### ISSUE THREAD

**Issue by jeffposnick** [whatwg/url#26]
Inspired by [this tweet](https://twitter.com/igrigorik/status/605766338687016960), I'd argue that the specified behavior for the [`URLSearchParams` stringifier](https://url.spec.whatwg.org/#urlsearchparams) should be changed to either automatically sort by default (unlikely, due to @annevk's [objections](https://twitter.com/annevk/status/605887980570411008)), or alternatively to support some sort of boolean opt-in to enable sorting.

I'd imagine that sorting based on parameter names, falling back to parameter values in the case of repeated parameters, would make the most sense.

**Comment by pornel** [comment]
I suggest [allowing constructor to take an `Object`](./27) and set names/values from object's **sorted** properties.

I think this would be a nice and convenient opt-in.

**Comment by domenic** [comment]
Since URLSearchParams with a different order is actually different semantically, it would make more sense to have something like `usp.sorted()` that returns a new `URLSearchParams` object with the order re-shuffled.

**Comment by annevk** [comment]
@domenic should that be similar to `Array.prototype.sort()`? If we add it here I guess we'd want it for `FormData` and `Headers` too? And `Map` objects? Not sure if this really needs to be standard library yet since it's quite trivial to write I think (have not attempted).

**Comment by domenic** [comment]
Hmm I'm not sure. If you did want to allow a custom comparator, I'd imagine something like this?

```js
const newUsp = usp.sorted(([k1, v1], [k2, v2]) => v1.localeCompare(v2)); // sort by values
```

You could start with just a no-arg `usp.sorted()` that returns them sorted by key, then by value.

**Comment by domenic** [comment]
> If we add it here I guess we'd want it for FormData and Headers too?

Yeah probably.

> And Map objects?

Less clear to me, as there's no good default unless you just assume all keys can be converted to strings.

> Not sure if this really needs to be standard library yet since it's quite trivial to write I think (have not attempted).

Yeah, it would be good to see some library code with at least moderate use before we try to bake this in...

**Comment by annevk** [comment]
So looking at this somewhat fresh and rereading the tweet thread it seems this is actually specific to URLSearchParams since it affects cache interactions. Neither Headers nor FormData encounter such a scenario. It also seems that a simple lexical sort should be sufficient here and that you actually do want to affect the current instance.

@igrigorik does that sound about right?

If that is correct, just adding a `sort()` member which uses lexical sort to sort the existing items in the list (using name is the sort key) seems like the way to go.

**Comment by annevk** [comment]
@igrigorik @jeffposnick ping.

**Comment by jeffposnick** [comment]
👍  to the suggestion at https://github.com/whatwg/url/issues/26#issuecomment-267978678

**Comment by jasnell** [comment]
If this were to happen, having the new `sort()` operate the same basic way as `Array.prototype.sort()` would be ideal, I think. Sort in place with the default sorting on the Unicode codepoint of the keys without value sorting, but allowing a `compareFunction` to be passed in. The function should sort in place and not be stable.

The reason for the default sort not affecting the value order is that ordering of the values can be significant. We should not assume that it's ok to move the order of the values around.

**Comment by igrigorik** [comment]
@annevk yep, another 👍 for https://github.com/whatwg/url/issues/26#issuecomment-267978678.

**Comment by annevk** [comment]
@jasnell I was hoping to go with the minimum viable solution here. If you need a callback, you might as well write a quick `forEach()` or some such. Only sorting keys seems reasonable though.

**Comment by jasnell** [comment]
I can live with that

**Comment by pornel** [comment]
Please make sure the sort is stable, so that the pseudo-array format `foo[]=1&foo[]=2&foo[]=3` preserves order of items in the "array".

**Comment by annevk** [comment]
@pornel are you saying that the proposed language fails to capture that? Also, if you have good tests, they'd be appreciated.

**Comment by jasnell** [comment]
I just realized that in my first comment I'd said the the sort need not be stable, that was a typo. I meant that it should. The language in the pr looks good to me.

**Comment by pornel** [comment]
Ah, the PR is fine.

**Comment by domenic** [comment]
How do people feel about my suggestion of a `.sorted()` that returns a new instance, instead of a `.sort()` that mutates the URLSearchParams instance? I guess maybe `.sort()` is more what JavaScript programmers expect. You can do a non-destructive sort via

```js
const sorted = (new URLSearchParams(usp)).sort();
```

I suppose.

**Comment by annevk** [comment]
@domenic I think one big problem with that is that it doesn't work well if you got to the `URLSearchParams` object through `new URL()`. It wouldn't be reflected back to the URL (other than through setting `.search` to the stringification).

**Comment by domenic** [comment]
Yeah, I guess that makes sense; I forgot there wasn't a `searchParams` setter.

**Comment by domenic** [comment]
Maybe just include an example in the spec of how to do a non-destructive sort like my above.

**Comment by annevk** [comment]
* No bug against Edge because it lacks the entire feature.
* https://bugs.chromium.org/p/chromium/issues/detail?id=682143
* https://bugzilla.mozilla.org/show_bug.cgi?id=1331864
* https://bugs.webkit.org/show_bug.cgi?id=167154

So close to all ending in 4.
