### ISSUE TITLE
fix broken links to [RFC3986] [RFC3987]

### ISSUE THREAD

**Issue by samuelweiler** [whatwg/url#264]
The "go away kid, you're bothering me" version of:  https://www.w3.org/TR/url-1/

has broken references to the cited RFCs.

**Comment by annevk** [comment]
@dontcallmedom is that something you can fix?

@samuelweiler for future reference, WHATWG can't really fix w3.org publications, just whatwg.org publications.

**Comment by dontcallmedom** [comment]
yes, I should be able to fix it (and sorry for the mistake in the first place, I missed this when preparing the document); will report back here once done

**Comment by dontcallmedom** [comment]
now fixed

**Comment by annevk** [comment]
Thanks!

**Comment by samuelweiler** [comment]
@annevk I was wondering about who could fix it, but the doc does explicitly direct issues here.  Should that be changed, too?

@dontcallmedom thank you!

**Comment by annevk** [comment]
I guess it's fine, if we start getting an issue a week from that document here we might have to reconsider, but this was the first.
