### ISSUE TITLE
Perhaps do not apply ToASCII for ASCII-only input

### ISSUE THREAD

**Issue by domenic** [whatwg/url#267]
See https://lists.w3.org/Archives/Public/www-archive/2017Feb/0006.html

The possible solutions are:

- Browsers get stricter and apply ToASCII anyway
- ToASCII's definition changes to not do any validation on ASCII-only input
- This spec only invokes ToASCII on on non-ASCII input

**Comment by TimothyGu** [comment]
FYI, Node.js after https://github.com/nodejs/node/pull/11549 errors out on all test cases in https://annevankesteren.nl/2017/02/idna-toascii-differences.

**Comment by annevk** [comment]
FYI: @rmisev discovered some issues with ASCII fast paths: https://github.com/whatwg/url/pull/309#issuecomment-301405332. An ASCII fast path is probably still an acceptable intermediate solution though, but I'd rather define something better in the standard.

**Comment by annevk** [comment]
So my recommendation is that we go with a fourth solution:

* ToASCII definition changes to do less validation on all input

In particular make use of the new CheckHyphens proposed in http://www.unicode.org/reports/tr46/tr46-18.html#ToASCII. I'm not entirely sure how to update the standard though potentially we could refer to the proposed version. I think we've done that in the past as well.

I filed these bugs (I hope someone can help with Node.js, they seem well represented):

* https://bugzilla.mozilla.org/show_bug.cgi?id=1365893
* https://bugs.chromium.org/p/chromium/issues/detail?id=724018
* https://bugs.webkit.org/show_bug.cgi?id=172282
* https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12059095/

I wrote these tests (quite a few from @rmisev): https://github.com/w3c/web-platform-tests/pull/5976.

**Comment by TimothyGu** [comment]
> I hope someone can help with Node.js, they seem well represented

Sure 😆

To be clear, am I correct in saying this decision means:

```diff
  <li><p>Let <var>result</var> be the result of running <a abstract-op lt=ToASCII>Unicode ToASCII</a> with
  <i>domain_name</i> set to <var>domain</var>, <i>UseSTD3ASCIIRules</i> set to false,
- <i>processing_option</i> set to <i>Nontransitional_Processing</i>, and <i>VerifyDnsLength</i> set
- to false.
+ <i>processing_option</i> set to <i>Nontransitional_Processing</i>, <i>VerifyDnsLength</i> set
+ to false, and <i>CheckHyphens</i> set to false.
```

If so, we have https://github.com/nodejs/node/pull/12966 already which would fulfill this.

**Comment by annevk** [comment]
Yeah, we might also make CheckJoiners false, but that's a separate discussion.
