### ISSUE TITLE
Switching from "file" to special scheme when host is empty

### ISSUE THREAD

**Issue by rmisev** [whatwg/url#270]
Sample:
```
var url = new URL('file:///path');
url.protocol = 'http:';
```
Current result: `http:///path` (with empty host); but after re-parse `host` gets "path" value.

I see two variants how to resolve this issue:
1. Change `host` to "localhost"
2. Or disallow such switch

Related to #259 / #269

**Comment by annevk** [comment]
I clearly didn't think hard enough. I will try to add this to the current PR. My tentative plan is to no-op for this case.

**Comment by annevk** [comment]
Done, added tests too.
