### ISSUE TITLE
Unclear behavior of path scheme for special URL

### ISSUE THREAD

**Issue by watilde** [whatwg/url#275]
From these lines: [w3c/web-platform-tests/url/setters_tests.json](https://github.com/w3c/web-platform-tests/blob/17966a23f1a561e5e0cd86232b3655c47240c9d5/url/setters_tests.json#L229-L236). On Chrome, the pathname displays `//example.com`, but `whatwg-url` displays empty, and `node` displays `/`. 
```js
var url = new URL('ssh://example.com')
console.log(url.pathname)
``` 

What should we expect as a spec? I think it should be `/` as like the other scheme.

**Comment by TimothyGu** [comment]
AFAICT Node.js' implementation is currently outdated. Specifically, I don't think whatwg/url#213 has been implemented yet.

**Comment by domenic** [comment]
You should expect an empty string per the spec as discussed in #213.

**Comment by annevk** [comment]
Yeah, closing this.

**Comment by watilde** [comment]
Thanks for pointing that!
