### ISSUE TITLE
Update structured cloning for recent HTML changes

### ISSUE THREAD

**Issue by domenic** [whatwg/url#277]
https://github.com/whatwg/html/commit/97d644c97335956610a31e8ad98d1a388c063e84 changed structured cloning significantly. I am not sure what the correct changes are here myself; it will likely require coordination with the File API folks.

**Comment by annevk** [comment]
So now `close()` is gone we might be able to not clone at all and just pass the reference from the blob store along since code can no longer change the state of a blob object.

Should maybe make sure File API keeps that invariant alive though.

**Comment by domenic** [comment]
Oh interesting. If so also let's be sure to revise the two notes in the HTML Standard about how URL parsing uses StructuredSerialize.

**Comment by annevk** [comment]
So as long as blob URLs also work for MediaStream and MediaSource this is not going to work, since those two objects are mutable.

**Comment by annevk** [comment]
However, those two objects cannot be serialized/deserialized (though MediaStream can be cloned through a locally defined operation). Good times. Per https://github.com/w3c/mediacapture-main/issues/404 blob URLs might go away for MediaStream.

I guess we should just accept that those objects are mutable and what you get depends on when you start reading them...
