### ISSUE TITLE
mailto special cases

### ISSUE THREAD

**Issue by stevenvachon** [whatwg/url#280]
`mailto:` should have the port stripped similar to `file://`, instead of including it as part of the hostname.

Perhaps strip the hash off too.

```
mailto:user@domain:110?subject=hi#hash
```

**Comment by annevk** [comment]
I think that should happen above the URL parser. File URLs cannot be handled at a layer above the URL parser due to how special they are, but for mailto it seems doable.

**Comment by stevenvachon** [comment]
"Above the URL parser" as in, after it's been parsed? How can `file://` URLs not be handled at that point?

**Comment by annevk** [comment]
Because of backslash handling for instance. I mean, if you have a way...

**Comment by stevenvachon** [comment]
Backslashes are converted to forward slashes. I'm still confused.

**Comment by annevk** [comment]
Yes, by the parser, for file URLs. If we just encoded them as we do for other URLs we couldn't distinguish between \ and its percent-encoded form.

**Comment by zcorpan** [comment]
Not just for file but for all special schemes. But mailto: is not [special](https://url.spec.whatwg.org/#special-scheme).

**Comment by stevenvachon** [comment]
Maybe mailto: should be special, since it's a popular scheme and has no use for a port.

**Comment by annevk** [comment]
It might be reasonable to define how to extract a mailto URL from a URL record, but I don't see why we need to change the parser for it.

**Comment by stevenvachon** [comment]
`ws:` and `wss:` were added as special schemes. For the same reason, I think `mailto:` should be added.

**Comment by annevk** [comment]
ws/wss parse in a special way, that's why they're there. (They should never have been added to the platform though; they're redundant with http/https.)
