### ISSUE TITLE
Behaviour with URIs / URNs

### ISSUE THREAD

**Issue by felixfbecker** [whatwg/url#289]
The spec only talks about URLs. I have a use case where resources are identified by URIs, so identifiers I receive could also be a URN. Testing in Chrome, the parser doesn't seem to break when you pass a URN:

![image](https://cloud.githubusercontent.com/assets/10532611/24577560/3fc56598-16d0-11e7-9062-80de9adf3cd1.png)

It parses `protocol` and `pathname` correctly. Is this guaranteed for all implementations? Or just happens to work in Chrome? A URN is not a URL, so I wouldn't expect a `URL` parser to necessarily parse URNs. I might even expect an implementation to throw an error.

**Comment by annevk** [comment]
A URN is a URL. Also, I believe URNs have to use the urn scheme. What you have above is just a generic URL.

**Comment by felixfbecker** [comment]
That is not true. In the most general sense, the URIs are a superset of URLs, meaning every URL is a URI, but not every URI is a URL, and especially not every URN.

![image](https://cloud.githubusercontent.com/assets/10532611/24590287/cefa8c28-17ea-11e7-99f3-2bf4a3f3ea49.png)

**Comment by annevk** [comment]
You need to cite your sources then (and note that the URL Standard obsoletes some of them).

**Comment by annevk** [comment]
I'm going to close per https://url.spec.whatwg.org/#goals. Let me know if you have more concerns.
