### ISSUE TITLE
there can be more than one Blob URL Store

### ISSUE THREAD

**Issue by isonmad** [whatwg/url#290]
[URL parsing](https://url.spec.whatwg.org/#url-parsing) refers to looking up a path in '[the blob URL store](https://w3c.github.io/FileAPI/#BlobURLStore)', but the File API spec defines one Blob URL Store per global object, so there are as many BUSes as there are global objects. You'd have to attempt lookup in all of them one by one, with the current spec language.

**Comment by annevk** [comment]
See also #127. 

Also, it's not clear the model defined by the File API specification is correct, but I can't find a current issue. @inexorabletash?

**Comment by inexorabletash** [comment]
Passing the buck to @mkruisselbrink

**Comment by mkruisselbrink** [comment]
Yes, properly specifying the blob URL store and how the URL spec refers to it is somewhere on my todo list... Probably ending up with both one true blob URL store, as well as a per-global blob URL revocation list or something like that...
