### ISSUE TITLE
"base URL" should be exported

### ISSUE THREAD

**Issue by domenic** [whatwg/url#293]
https://url.spec.whatwg.org/commit-snapshots/703fcd0b92053345582a36b2e4a642ab65df076e/#url-miscellaneous

> A URL can be designated as base URL

This is useful so you can do things like

```
Let |manifestURL| be the result of [=basic URL parser|basic URL parsing=]
|manifestURLString| with [=base URL=] given by |identifierResponse|'s [=response/url=].
```

Currently `[=base URL=]` does not work.

**Comment by annevk** [comment]
That's not quite what it was meant for, but I agree that it should probably be exported. (In other contexts where we invoke the URL parser we don't write it out like that.)

**Comment by domenic** [comment]
Oh, I assumed that was how it was supposed to work, given the definition:

> The URL parser takes a string input, with an optional base URL base and an optional encoding encoding override, and then runs these steps: 

(here "base URL" links to that definition)

**Comment by annevk** [comment]
I usually introduce the type of arguments when defining a "spec function", but I don't expect callers to list them as well. You also didn't write "string manifestURLString". 😉
