### ISSUE TITLE
authority state limits passwords outside of percent encoding

### ISSUE THREAD

**Issue by Thomspoon** [whatwg/url#294]
In `authority state`, the pointer is specified to decrement, and only change state on:

- EOL

- U+002F (/)

- U+003F (?)

- U+0023 (#)

I'm wondering why the symbols `/`, `?`, and `#` are used in this section because the symbols `?` and `#` can be used in passwords.

For the implementation of the `authority state`, a url such as: 

`scheme://root:pass#word@example.com`

Would result in undefined behavior, as the octothorp should not move the parser into the fragment state.

**Comment by annevk** [comment]
Could you clarify what exactly is ambiguous? And how you'd even end up in "relative state" with that URL as input?

**Comment by Thomspoon** [comment]
Hey, sorry about the state issue. I've corrected the issue to what state the problem, or maybe misunderstanding, lies.

The current algorithm expects a url such as:

`a://b:c#d@e` 

To be finished with `b` as the username, no password (I assume), and `c` as the domain. I don't believe this to be a correct use-case.

In order for the original example to pass the parser, you would have to just percent encode the password yourself to:

`scheme://root:pass%23word@example.com` in order for the parser implementation to not resolve the `#` as a switch to the hostname state.

**Comment by annevk** [comment]
`a://b:c#d@e` would fail parsing without a base URL due to the slashes.

But yes, you have to encode some characters in URLs when you want to put them in certain positions. We can't really change how URLs are parsed retroactively.

**Comment by Thomspoon** [comment]
Isn't this a limitation of the URL itself though? You can have any ascii character in your username/password except the fragment, query, or path characters, as they would have to be encoded by hand. This seems painful.

**Comment by annevk** [comment]
Well, per the URL Standard you shouldn't be producing such URLs anyway as URLs leak and therefore usernames and passwords would too, so that concern is not super important. Besides, no client parses URLs the way you seem to want so we can't change this anyway.
