### ISSUE TITLE
Make property accessors into owned properties, or at least enumerable

### ISSUE THREAD

**Issue by JamesMGreene** [whatwg/url#301]
I'd like to see `URL` objects' main data properties all become owned properties (or at least enumerable), i.e. `origin`, `protocol`, `username`, `password`, `host`, `hostname`, `port`, `pathname`, `search`, `hash`, and maybe `href` and `searchParams`.

Without that nature, it makes these `URL` objects extremely frustrating to work with as they do not fit well semantically in normal object models due to their lack of owned properties, e.g. when comparing 2 `URL` objects:
 - https://github.com/JamesMGreene/chai-deep-match/issues/2
 - https://github.com/lodash/lodash/issues/3121
 - https://github.com/debitoor/chai-subset/issues/60

**Comment by domenic** [comment]
They already are enumerable.

They're not own properties, or data properties, however. This is the same as every other web platform object, and unlikely to change. I'd suggest that if those frameworks want to work with web platform objects in general, they need updates; URL is not a special case.

**Comment by JamesMGreene** [comment]
I see that the https://github.com/jsdom/whatwg-url implementation conveniently represents them as objects with owned properties. 😍

**Comment by domenic** [comment]
That's just... not true...

**Comment by JamesMGreene** [comment]
Ah, sorry, that's in the `URLStateMachine#url` bit.

**Comment by stevenvachon** [comment]
https://www.npmjs.com/package/object.getownpropertydescriptors

**Comment by annevk** [comment]
I don't understand "normal object models" as defined in OP. Surely the "normal" one is the one defined by JavaScript, which puts things on the prototype for all its objects?

What are you trying to accomplish that works with say Map, but not URL?

**Comment by JamesMGreene** [comment]
> I don't understand "normal object models" as defined in OP. Surely the "normal" one is the one defined by JavaScript, which puts things on the prototype for all its objects?

I would say that JavaScript's basic object model is to store data in owned properties, and only put functions ("methods") on its prototypes.  In a sense, `URL` complies with that concept because all of its public properties are essentially functions in that they are getters and setters but from an outside perspective they would likely be considered simple data properties if it weren't for their computed nature [if one of them were to be updated].

> What are you trying to accomplish that works with say Map, but not URL?

Yes, I guess `Map` is similar.


Again, the main frustration is that they are not possible to compare on a property level with typical object comparison functions without adding custom code specific to handling `URL` objects, or without also iterating through all potentially inherited properties (i.e. with `for...in`).

```js
const URL_KEYS = Object.keys( URL.prototype );

function urlToPlainObject( url ) {
  var urlObj = url ? {} : null;
  URL_KEYS.forEach(function( URL_KEY ) {
    if ( typeof url[ URL_KEY ] === 'string' ) {
      urlObj[ URL_KEY ] = url[ URL_KEY ];
    }
  });
  return urlObj;
}


var url = new URL('http://example.com/path/to/somewhere?curious=yes#sir');

console.log( JSON.stringify( url ) );
// => {}

console.log( JSON.stringify( urlToPlainObject( url ) ) );
// => {"href":"http://example.com/path/to/somewhere?curious=yes#sir","origin":"http://example.com","protocol":"http:","username":"","password":"","host":"example.com","hostname":"example.com","port":"","pathname":"/path/to/somewhere","search":"?curious=yes","hash":"#sir"}
```

**Comment by annevk** [comment]
If you want to use a URL as data, I recommend just passing it around as a string.

**Comment by domenic** [comment]
See also https://url.spec.whatwg.org/#url-apis-elsewhere to backup @annevk's last point.

I also disagree with that notion of JavaScript's object model; it sounds like you're making inferences based on deficient tools ("typical object comparison functions") that are meant for dealing with "records" (things created via object literals or JSON or similar), and fail on true instances of classes.

**Comment by JamesMGreene** [comment]
@annevk: Yeah, I understand that its `href` string value is essentially its serialized form and that is indeed valuable.

The frustration comes when someone wants to find out why 2 URLs are different.  Viewing a difference comparison of strings can be nearly incomprehensible for some people, depending on the number of and types of differences.  The fact that you can break them down into URL objects is fantastic but the fact that those objects are then not easily comparable via normal comparison methods is not so fantastic.  The data is right there waiting to be used but requires custom code, or comparison methods that may be undesirable and inefficient in other situations (i.e. I definitely do not want to compare prototype properties of any plain Array, Object, or primitive data type).

**Comment by annevk** [comment]
If you solve the problem of making it comprehensible how two string values are different you will also have solved it for URLs. And it's less of a problem for URLs since you'll have much less characters to deal with.

**Comment by JamesMGreene** [comment]
> I also disagree with that notion of JavaScript's object model; it sounds like you're making inferences based on deficient tools ("typical object comparison functions") that are meant for dealing with "records" (things created via object literals or JSON or similar), and fail on true instances of classes.

Yes, your point is well taken, and I can agree that this is the distinction between what I've been incorrectly calling "un-semantic" here.

I would definitely love for there to be an easy way to convert a `URL` object (and other such WebAPI objects, I suppose, like `Map`) to a "record" object for easier comparisons and potentially serializations without so much custom code.

**Comment by JamesMGreene** [comment]
> If you solve the problem of making it comprehensible how two string values are different you will also have solved it for URLs. And it's less of a problem for URLs since you'll have much less characters to deal with.

Granted, but I also know that we can do better since a URL string in particular (vs. free form text) also has a known logical data breakdown/structure that we can use to focus the comparisons and differences down.

**Comment by annevk** [comment]
Is there a generic definition of this ToRecord operation? Has anyone attempted to write a library for it? It sounds reasonable in principle, but someone will have to do some work and prove it (widely used, utility, benefits from standardization).

**Comment by JamesMGreene** [comment]
That would be amazing to have. :+1:

**Comment by stevenvachon** [comment]
> The frustration comes when someone wants to find out why 2 URLs are different. Viewing a difference comparison of strings can be nearly incomprehensible for some people, depending on the number of and types of differences.

[url-relation](https://npmjs.com/url-relation)

**Comment by JamesMGreene** [comment]
@stevenvachon: Very cool but still obviously specific to `URL` objects vs. some more generic way of comparing them like records (as you yourself are essentially hoping to do with your requests at JamesMGreene/chai-deep-match#2 and debitoor/chai-subset#60 😄 ).

**Comment by stevenvachon** [comment]
Yes, I'm just stating that there're easy ways to do things. I've also written [isur](https://npmjs.com/isurl) to handle expected properties:
```js
if (isURL.lenient(url1) && isURL.lenient(url2)) {
  return url1.href === url2.href;
}
```

I can understand where you're coming from with this, though, as you want:
```js
o={}; Object.defineProperty(o, 'p', { get:()=>'v', enumerable:true }); Object.keys(o)
//-> ['p']
```

... which ES2015 classes do not do. I think that your issue may need to be brought up with ECMA and not WHATWG?

**Comment by domenic** [comment]
I think it's safe to close this as we're not likely to make the URL class unlike all other classes on the web platform.
