### ISSUE TITLE
Drive letters get duplicated when resolving Windows file: URL with base

### ISSUE THREAD

**Issue by felixfbecker** [whatwg/url#303]
It seems like it's impossible to resolve a Windows file:/// URI with a base.

Expected (as implemented Chrome):
```js
new URL('/c:/foo/bar', 'file:///c:/baz/qux').href
"file:///C:/foo/bar"
```

Actual (as implemented in jsdom/whatwg-url, NodeJS 7, Edge):
```js
new URL('/c:/foo/bar', 'file:///c:/baz/qux').href
'file:///c:/c:/foo/bar'
```

**Comment by annevk** [comment]
Windows drive letters are somewhat magical (and act like hosts) so that's somewhat to be expected.

**Comment by felixfbecker** [comment]
Why do they act like hosts? A file: URI can have a host before the path, the path starts with a leading slash just like on other OS. It's just like a mounted drive on Linux.

The drive letter definitely is not shown as a host in any implementation I tested:
```js
new URL('/c:/foo/bar', 'file:///c:/baz/qux').host
''
```

Is this behaviour defined in the current spec?

**Comment by annevk** [comment]
Act like host doesn't mean exposed as one. It just means that when resolving URLs they act like a base.

```new URL('test', 'file:///c:/x').href
"file:///c:/test"```

**Comment by rmisev** [comment]
I think a drive letter must act like "host" in the *input* as well. I.e. if *input* has a drive letter, then don't copy the drive letter from *base*. Because the same is done with hosts: if *input* contains a host, then host isn't copied from the *base*.

So I think @felixfbecker is right. It looks like spec. bug.
