### ISSUE TITLE
remaining variable ambiguity

### ISSUE THREAD

**Issue by TimothyGu** [whatwg/url#308]
> The [EOF code point](https://url.spec.whatwg.org/#eof-code-point) is a conceptual code point that signifies the end of a string or code point stream.
>
> [*remaining*](https://url.spec.whatwg.org/commit-snapshots/fe6b251739e225555f04319f19c70c031a5d99eb/#remaining) references the substring after *pointer* in the string being processed.
>
> …
>
> [File state](https://url.spec.whatwg.org/commit-snapshots/fe6b251739e225555f04319f19c70c031a5d99eb/#file-state): … *remaining* consists of zero code points

My understanding is that this condition in file state really covers two cases:

* when *c* is the last code point of *input*
* when *c* is the EOF code point

Is this understanding correct?

(I know in this case it doesn't really matter, as the case when *c* is the EOF code point will take a different switch-case above, but I just wanted to make sure *remaining* is properly understood and spec'd if necessary.)

**Comment by annevk** [comment]
Yeah, I think that's correct.

**Comment by annevk** [comment]
I wouldn't mind figuring out a better way to write this down though, eventually. It's not the best algorithm style.

**Comment by rmisev** [comment]
I think we should add a note stating, that the [**remaining**](https://url.spec.whatwg.org/#remaining) is accessed (used) only when [**c**](https://url.spec.whatwg.org/#c) isn't [**EOF**](https://url.spec.whatwg.org/#eof-code-point).
I checked, this satisfies the current specification.

I think, that such or similar note clarifies the definition and can be valuable for developers.

**Comment by annevk** [comment]
Sounds reasonable.

**Comment by GPHemsley** [comment]
I think it's also important to define the behavior of _c_ when the pointer is less than 0.

This scenario happens during the transition between "scheme start state" and "scheme state" at the beginning of the string, where the pointer is set to -1 for the rest of the run. Though _c_ is not checked during this time, it should be clear what would happen if it were.

Should it just act as if it were 0 and point to the first code point? Or should it not reference any code point?

Similarly, if pointer is incremented past the EOF, what does _c_ represent? Does the string end in an infinite number of EOFs? Or just one, with any pointer value after that not referencing any code point?

**Comment by rmisev** [comment]
All your mentioned cases are the access of _c_ when _pointer_ is out-of-bounds. The behaviour is described for lists here: https://infra.spec.whatwg.org/#list

> An indexing syntax can be used by providing a zero-based index into a list inside square brackets. The index cannot be out-of-bounds, except when used with exists.

I think the same must be defined for strings with only **EOF code point** exception (when _pointer_ = string._length_). So any attempt to access _c_ then _pointer_ is out-of-bounds (_pointer_ < 0 or _pointer_ > string._length_), must be considered a bug.

**Comment by GPHemsley** [comment]
I agree that the definitions should be analogous, though I don't know if I would call out-of-bounds a "bug" so much as undefined or similar.

And the existence _remaining_ further complicates the issue: what if _pointer_ is out of bounds but _pointer_ + 1 isn't? Or vice versa? Does the definition of _remaining_ require that _c_ be defined?

**Comment by rmisev** [comment]
Well, what you think about following explanation:

**c** is defined and accessed only when _pointer_ is within bounds of the string or points to the **EOF code point**.

**remaining** is defined and accessed only when _pointer_ is within bounds of the string.

**Comment by GPHemsley** [comment]
That appears to be exactly what I've implemented since your previous comment:

* _pointer_ points to the **EOF code point** if _pointer_ equals the length of _string_
* **c** is undefined if _pointer_ is less than 0 or greater than the length of _string_
* **remaining** is undefined if _c_ is undefined or if _pointer_ points to the _EOF code point_

**Comment by GPHemsley** [comment]
To get back to the original question: if _c_ points to the last code point in the string, _remaining_ necessarily consists of only the _EOF code point_. Once _c_ points to the _EOF code point_, _remaining_ becomes undefined.
