### ISSUE TITLE
Should the legacy alias webkitURL be defined in the Compat Standard instead?

### ISSUE THREAD

**Issue by simevidas** [whatwg/url#314]
Apologies for my ignorance, but regarding https://github.com/whatwg/url/commit/c643963adaf99100d21d3bfb5969783b551b5150, shouldn’t vendor-prefixed APIs be specified in the [Compat Standard](https://compat.spec.whatwg.org/) instead?

**Comment by domenic** [comment]
No. The Compat Standard is only for monkey-patching specs which aren't willing to take on the burden of defining web-compatibility themselves. (Mostly unmaintained specs, or CSSWG specs since they have... different... policies.)

**Comment by simevidas** [comment]
I see 👍
