### ISSUE TITLE
"shorten a url's path" does not return a value

### ISSUE THREAD

**Issue by GPHemsley** [whatwg/url#316]
> To shorten a url’s path:
> 1. Let path be url’s path.
> 1. If path is empty, then return.
> 1. If url’s scheme is "file", path’s size is 1, and path[0] is a normalized Windows drive letter, then return.
> 1. Remove path’s last item.

Since all the operations are done on the variable _path_, rather than on _url_'s path, the results get thrown away.

**Comment by domenic** [comment]
That's intentional; it mutates the path list.

**Comment by GPHemsley** [comment]
@domenic Hit enter by accident before I was finished. See my actual comment above.

**Comment by GPHemsley** [comment]
Is it specified anywhere that variables work that way?

Infra only says:
> A variable is declared with "let" and changed with "set". 

Not everyone is implementing this in JavaScript. 😉

**Comment by domenic** [comment]
No, I guess not. It's just implied by usage everywhere else. See e.g. https://html.spec.whatwg.org/#create-an-element-for-the-token step 1 (or many other step 1s); we're certainly not going to make copies of the whole document each time you create an element during parsing.

**Comment by GPHemsley** [comment]
Alright, I've filed whatwg/infra#139 to have that clarified somewhere. Feel free to close this if the algorithm will remain as-is.

**Comment by domenic** [comment]
Sounds good, let's get this clarified in Infra :)

**Comment by GPHemsley** [comment]
testing 123 - sorry for the spam (if any!)
