### ISSUE TITLE
IDNA: possibly use "domain to Unicode" in "valid domain"?

### ISSUE THREAD

**Issue by domenic** [whatwg/url#317]
In https://github.com/whatwg/url/pull/309 @rmisev noted that the extra flags were not set in the "valid domain" algorithm's call to ToUnicode. I pushed a fixup that adds them. But maybe it would be better to deduplicate the calls to ToUnicode, similar to what is already done for the calls to ToASCII.

This is not obviously straightforward since I am not sure who uses "domain to Unicode", and I'm not sure why it doesn't return failure on errors.

**Comment by annevk** [comment]
We don't have any users of "domain to Unicode" in the platform currently (after I removed origin to Unicode). #288 proposes to change that, but some at Chrome voiced concerns.

**Comment by annevk** [comment]
I ended up doing this in https://github.com/whatwg/url/commit/08951233c9e36ffe19c6d530a533a05f1272d181. The one call we have now is from the i18n address bar considerations, which seems okay.
