### ISSUE TITLE
"Forbidden host code point" should be defined without U+0025

### ISSUE THREAD

**Issue by GPHemsley** [whatwg/url#319]
The term "forbidden host code point" is used exactly twice within this spec, and in one case it excludes U+0025 (%):

> If asciiDomain contains a forbidden host code point, validation error, return failure.

> If input contains a forbidden host code point excluding U+0025 (%), validation error, return failure.

I think it is easier for implementations to add to a definition rather than take away from it, so I propose removing U+0025 from the definition and special-casing it where it is _included_:

> If asciiDomain contains a forbidden host code point or U+0025 (%), validation error, return failure.

> If input contains a forbidden host code point, validation error, return failure.

Or else creating a second definition that relates to the existing one.

**Comment by annevk** [comment]
It's also used in https://url.spec.whatwg.org/#valid-opaque-host-string now and I think that indeed argues for changing this as it's a bit ambiguous (to me).

**Comment by alwinb** [comment]
Something similar happens with [URL-path-segment strings] which uses the phrase:

> zero or more URL units excluding U+002F (/) and U+003F (?), that together are not a single-dot path segment or a double-dot path segment.

What do you think about rephrasing things to use sets of _allowed_ codepoints for each of username, password, opaque-host, path-segment, query, and fragment instead?

[URL-path-segment strings]: https://url.spec.whatwg.org/#url-path-segment-string

**Comment by annevk** [comment]
That might be reasonable, though I'd rather approach it in small incremental steps as each of those has the potential for regressions.
