### ISSUE TITLE
"IPv6 serializer" does not define an algorithm for longest sequence of IPv6 pieces that are 0

### ISSUE THREAD

**Issue by GPHemsley** [whatwg/url#321]
Similar to #318, the "IPv6 serializer" requires determining the longest sequence of 0s for IPv6 compression without specifying an algorithm for doing that:

> Let compress be an index to the first IPv6 piece in the first longest sequences of address’s IPv6 pieces that are 0.
> Example: In 0:f:0:0:f:f:0:0 it would point to the second 0.
> If there is no sequence of address’s IPv6 pieces that are 0 that is longer than 1, then set compress to null.

It would be better for implementors if the procedure for doing so were made explicit, as this is another seemingly non-trivial task.

**Comment by annevk** [comment]
Per https://github.com/jsdom/whatwg-url/pull/150 it does not seem that tricky, but happy to write that out in prose (after confirming my modifications are indeed correct).
