### ISSUE TITLE
Setting scheme should set port to null if it matches the default port

### ISSUE THREAD

**Issue by broofa** [whatwg/url#327]
When setting port state, https://url.spec.whatwg.org/#port-state says:

> 3. Set url’s port to null, if port is url’s scheme’s default port, and to port otherwise

However no corresponding verbiage is included in the process for setting a url scheme.  This leads to inconsistent URL states, as illustrated in node.js's current implementation of this standard:

```
> u1 = new URL('https://foo.com:80')
URL {...}
> u2 = new URL('http://foo.com:443')
URL {...}
> u1.protocol = 'http:'
'http:'
> u2.port = 80
80
> String(u1)
'http://foo.com:80/'
> String(u2)
'http://foo.com/'
```

`u1` and `u2` both represent the same URL (scheme, host, port), but u1's port is set to 80, while u2's port is null.

The spec should dictate that when the scheme state is set, the port should be set to null if it matches the default port for that scheme.

**Comment by broofa** [comment]
Note that Chrome's implementation has what I would argue is the correct behavior: 
![image](https://user-images.githubusercontent.com/164050/27562653-5be77d1a-5a82-11e7-8557-296532714c5a.png)

**Comment by GPHemsley** [comment]
Confirmed Firefox does the same:

![image](https://user-images.githubusercontent.com/376064/27570579-44ba705c-5acd-11e7-8284-20c737e8a06b.png)

**Comment by TimothyGu** [comment]
Newly added WPT passes on [Safari](https://travis-ci.org/w3c/web-platform-tests/jobs/247364796#L847), and [Edge](https://travis-ci.org/w3c/web-platform-tests/jobs/247364803#L861) but only for `<a>` and `<area>`; `URL` follows the current spec behavior.

**Comment by GPHemsley** [comment]
Making this change would make the spec more internally consistent (this seems like a simple oversight), and would bring the spec in line with the apparent browser consensus (minus `URL` in Edge).

👍 from me.

**Comment by annevk** [comment]
Thanks for reporting this @broofa! Could you please confirm that you'd be okay with being added to the acknowledgments? I regrettably forgot that during review, but it's an easy fix.

**Comment by broofa** [comment]
Confirmed ![image](https://github.com/ermanc/cultofthepartyparrot.com/blob/master/parrots/shuffleparrots.gif?raw=true)

**Comment by annevk** [comment]
Thanks, done!
