### ISSUE TITLE
Is there a handy way to stringify with a leading '?' only if not empty?

### ISSUE THREAD

**Issue by caub** [whatwg/url#329]
Currently I'd have to do `sp.toString() && '?'+sp`

ideally, .toString() would behave similarly to `URL#search`, so like this: 
```js
var sp = new URLSearchParams('');
sp+'' == '' // like now

var sp = new URLSearchParams('?x');
sp+'' == '?x=' // with a leading ?

var sp = new URLSearchParams('?');
sp+'' == '' // like now
```
but it's too late

Should it be a new method?

**Comment by annevk** [comment]
The idea is that you'd set `url.search` or some such. But yeah, this would require a new API and I'm not sure that's worth it really.

**Comment by caub** [comment]
At least could `.size` be exposed? like for a Map

**Comment by annevk** [comment]
`size` is #163.

**Comment by caub** [comment]
Thanks, and yes setting .search is smart too
