### ISSUE TITLE
Setting a port on a URL that cannot have a username/password/port should return the set value

### ISSUE THREAD

**Issue by GPHemsley** [whatwg/url#330]
Currently, the spec says the following in the setter for `port`:
> If context object’s url cannot have a username/password/port, then return.

However, this does not match the behavior of Firefox or Chrome, which both return the _given value_ even though no change is made to the URL's port:

![image](https://user-images.githubusercontent.com/376064/27777734-7a7602be-5f83-11e7-8539-04bf6f3b4fff.png)

![image](https://user-images.githubusercontent.com/376064/27777749-a1390644-5f83-11e7-9967-29d9fa8f0f6f.png)

The WPT setter tests don't appear to test this behavior, caring only about what `port` is set to after the call to the setter.

**Comment by domenic** [comment]
You're just seeing the console output. If you actually test them, e.g. `assert_equals(url.port = 123, undefined)`, you'll find it's undefined.

It's actually impossible for setters in JavaScript to return values.

**Comment by GPHemsley** [comment]
I take it you're referring to the `assert_equals` function defined in W3C's testharness.js?

I was under the impression that console output was the return value of an executed expression.

Tracing language-specific semantics is difficult, because it usually winds up back in ECMAScript, which itself has many layers of nested definitions of behavior. The way I've implemented it is for the setter to fall through to the getter code and return the value from that, unless explicitly told to return early. I guess that's incorrect?

**Comment by domenic** [comment]
Yes, or any other thing that asserts if things are equal.

Consoles don't always output the return value, especially if the return value is undefined.

That does sound incorrect to me, at least if you're trying to copy ECMAScript semantics. I'd suggest going with whatever semantics are conventional in your language for setters/getters, however.

**Comment by annevk** [comment]
Sounds like there's no problem with the specification here. Let me know if I missed something.
