### ISSUE TITLE
New URLSearchParams algorithm does not check if optional init variable is set

### ISSUE THREAD

**Issue by GPHemsley** [whatwg/url#333]
The algorithm definition begins:
> To create a **new** URLSearchParams object, optionally using _init_, run these steps: 

However, the algorithm itself doesn't check to see if _init_ is given before operating on it, going so far as identify its default case as being a string:
> 4. Otherwise, _init_ is a string, then set _query_’s list to the result of parsing _init_.

Steps 2, 3, and 4 should be enclosed in a check for whether _init_ is actually given before attempting to operate on it.

**Comment by rmisev** [comment]
It looks like <var>init</var> is the empty string then, see declaration https://url.spec.whatwg.org/#interface-urlsearchparams:

```js
[Constructor(optional (sequence<sequence<USVString>> or record<USVString, USVString> or
USVString) init = ""), Exposed=(Window,Worker)]
```

**Comment by GPHemsley** [comment]
Hmm... but isn't that for the constructor call?

The constructor, incidentally, _does_ check whether _init_ is given (twice!):
> 1. If init is given, is a string, and starts with U+003F (?), remove the first code point from init.
> 2. Return a new URLSearchParams object, using init if given.

**Comment by rmisev** [comment]
Yeah, now I see. It seems these checks aren't required.

**Comment by annevk** [comment]
Thanks, posted a fix.

**Comment by GPHemsley** [comment]
Ah, that wasn't the direction I was expecting, but it does appear to resolve the issue.

**Comment by annevk** [comment]
As far as I can tell there's no callers that need this to be optional. That was from before.
