### ISSUE TITLE
Unused "local scheme" and "is local" definitions

### ISSUE THREAD

**Issue by SimonSapin** [whatwg/url#34]
https://url.spec.whatwg.org/#local-scheme and https://url.spec.whatwg.org/#is-local don’t seem to be used anywhere in the URL spec. Are they intended for use from other specs? If so, perhaps a note linking to the relevant documents could be added. If not, these definitions could be removed.

**Comment by annevk** [comment]
Step 2 of https://fetch.spec.whatwg.org/#concept-main-fetch uses it, there's also a specification by @mikewest, but I forgot which one.

**Comment by mikewest** [comment]
https://w3c.github.io/webappsec/specs/referrer-policy/

also the as-yet-unwritten CSP3.
