### ISSUE TITLE
Consider percent-encoding more characters in "fragment state"

### ISSUE THREAD

**Issue by mikewest** [whatwg/url#344]
Currently, https://url.spec.whatwg.org/#fragment-state requires that we percent-encode characters in a URL's fragment using the [C0 control percent-encode set](https://url.spec.whatwg.org/#c0-control-percent-encode-set). Firefox currently encodes more than that, which I think actually makes a good deal of sense.

How would y'all feel about shifting fragment state encoding to match query state? That is, encoding "less than 0x21 (!), greater than 0x7E (~), or is 0x22 ("), 0x23 (#), 0x3C (<), or 0x3E (>)"?

**Comment by annevk** [comment]
See also https://github.com/whatwg/url/issues/18#issuecomment-269649720 and https://github.com/whatwg/url/issues/291.

cc @achristensen07 @jasnell

**Comment by annevk** [comment]
cc @valenting

**Comment by valenting** [comment]
> How would y'all feel about shifting fragment state encoding to match query state? That is, encoding "less than 0x21 (!), greater than 0x7E (~), or is 0x22 ("), 0x23 (#), 0x3C (<), or 0x3E (>)"?

That sounds good. It would be nice to converge onto something clear.
Firefox also escapes ` in the fragment, but I don't know if we want to keep it that way.

**Comment by jasnell** [comment]
I'd be good with this. (ping @TimothyGu)

**Comment by TimothyGu** [comment]
Sounds good to me.

**Comment by achristensen07** [comment]
What is the motivation for this change?  I wouldn't oppose encoding more characters, but I would oppose using the query encoding set as a model.

**Comment by mikewest** [comment]
@achristensen07: @annevk linked to some related conversations that discuss motivations (@bzbarsky's discussion of `<>` in #291 is compelling, for instance). I'm hopping on this due to some marginal risk of code injection when developers reflect `url.hash` into their pages: that risk would be mitigated if we were a little more strict about encoding these characters.

Based on some spot-checking, Firefox encodes at least `"`, ``` ` ```, `<`, and `>` in addition to everything above 0x7E, which is an indication that we can tighten things up here while maintaining compatibility with the web.

Do you have a set of characters you'd prefer to use instead of the query encoding set? As long as the set includes `<` and `>`, I'll be happy. :)

**Comment by rmisev** [comment]
> Do you have a set of characters you'd prefer to use instead of the query encoding set? As long as the set includes < and >, I'll be happy. :)

I'll prefer to encode "less than 0x21 (!)" and `"` also:

Code&nbsp;point | Why encode?
-|-
0x20 (SP) | See https://github.com/whatwg/url/issues/150#issuecomment-255160894 and https://bugzilla.mozilla.org/show_bug.cgi?id=1148861
0x22 (") | For safe copy/paste into `<a href="http://example.com#with%22quote">` vs `<a href="http://example.com#with"quote">`

**Comment by mikewest** [comment]
I'm fine with https://url.spec.whatwg.org/#path-percent-encode-set, FWIW.

**Comment by achristensen07** [comment]
I’m fine with using the path set for the path and fragment.

**Comment by mikewest** [comment]
Any objections to the path set? If not, I'll put together a PR and tests.

**Comment by rmisev** [comment]
It seems a bit stricter set than in RFC 3986, which allows U+003F (?) in non-encoded form.
See https://tools.ietf.org/html/rfc3986#section-3.5

**Comment by bzbarsky** [comment]
Yes, I'm pretty worried about `'?'` there in compat terms, esp given it being explicitly called out as allowed in the RFC.  Actually somewhat worried about `'#'` and `'{'` and `'}'` too, if no one escapes those right now...  How many people pass JSON in fragments, for example?

The actual set of chars the RFC allows in fragments, just for reference, is:

      fragment    = *( pchar / "/" / "?" )

where `pchar` is the set of characters allowed in path segments.  So basically, "everything allowed in paths, plus '?'".  Which is definitely more restrictive than what UAs do.

**Comment by mikewest** [comment]
@bzbarsky: Firefox encodes `"` right now, which would probably make it difficult to put valid JSON in fragments. Is there a subset of characters that you'd be more comfortable encoding? Are you happy with Firefox's current behavior?

**Comment by bzbarsky** [comment]
> which would probably make it difficult to put valid JSON in fragments.

Well, without escaping the `"`, right.  I guess at that point you're unescaping, so even if the `{` and `}` were escaped they'd get unescaped.  I did check that encode/decodeURIComponent escape/unescape those bits.

As for comfort... Basically, I'm comfortable encoding anything that at least one major browser encodes.  I'm a little worried about encoding things that none of them encode.  I'm very worried about `?`, given that it's long been explicitly specced as OK in fragments.

**Comment by mikewest** [comment]
> Basically, I'm comfortable encoding anything that at least one major browser encodes.

Ok. Would coalescing around Firefox's current encoding make sense? As noted above, that includes at least  `"`, ``` ` ```, `<`, and `>` in addition to everything above 0x7E (maybe you could point me to the right spot? My searchfox foo is poor. :( ).

**Comment by rmisev** [comment]
Yes. I tested the Firefox Nightly: it percent encodes: 0x20 (SP) and below, 0x22 (`"`), 0x3C (`<`), 0x3E (`>`), 0x60 (`` ` ``), and code points above 0x7E.

I think it is reasonable to standardize this percent encoding set.

_[My testing code.](https://rmisev.github.io/web-browser-tests/url/url-percent-encoding-test.html)_

FYI: Safari only encodes code points below 0x20 and above 0x7E; Chrome - code points below 0x20; Edge does not encode at all.

**Comment by bzbarsky** [comment]
> Ok. Would coalescing around Firefox's current encoding make sense?

I don't know, honestly.  At some point it would be good to involve someone from Firefox's networking team here.  Maybe @mcmanus knows who would be a good contact for that.

> maybe you could point me to the right spot?

I believe the right spot is as of today http://searchfox.org/mozilla-central/rev/a4702203522745baff21e519035b6c946b7d710d/xpcom/io/nsEscape.cpp#259-271

That table has, for each ASCII char, a bitmask indicating where it does NOT need to be escaped.  The bit for fragments is `1<<9`, so they get escaped for all the entries in the table that are < 512 (hey at least this one is easy to skim for...).

That looks like 0x00-0x20 (control chars and space), 0x22 (`"`), 0x25 (`%`), 0x3C (`<`), 0x3E (`>`), 0x60 (<code>`</code>) and anything above 0x7E.  Which I guess is what @rmisev got via his testing, good.

**Comment by mcmanus** [comment]
@valenting is the goto here and he seems ok with this.

**Comment by mikewest** [comment]
Uploaded a PR at https://github.com/whatwg/url/pull/347 and tests at https://github.com/w3c/web-platform-tests/pull/7641. Feedback welcome!

**Comment by annevk** [comment]
@bzbarsky also mentioned U+0025 (%), though @rmisev did not. Did anyone look into that difference?

**Comment by rmisev** [comment]
There is a comment about the U+0025 (%): http://searchfox.org/mozilla-central/rev/a4702203522745baff21e519035b6c946b7d710d/xpcom/io/nsEscape.cpp#344-345
```c++
// Also the % will not be escaped until forced
// See bugzilla bug 61269 for details why we changed this
```
I guess it answers your question.

**Comment by valenting** [comment]
I'll file a bug to stop escaping %.
I'm pretty sure we don't need that anymore.

**Comment by reschke** [comment]
If you don't escape "%", how do you reliably remove percent-encoding???? 

This is a violation of the rule "you have to escape the escape character", no?

**Comment by annevk** [comment]
I don't think you can reliably remove it for all URLs, in practice. I'm pretty sure I looked into that and it falls down for the query due to compatibility and maybe also for the path.

**Comment by reschke** [comment]
So what is code that does percent decoding supposed to do with:

  %2525

?

The answer is clear for RFC 3986. If it's not clear for this spec this hints at a problem of this spec, no?

**Comment by annevk** [comment]
@reschke percent-decoding isn't something that needs to be interoperable per se. In any event, we're getting off-topic. It would be best to discuss this in a separate issue. An example of where this becomes problematic would also help.

**Comment by reschke** [comment]
I'm not going to explain why removing of escaping needs to predictable in general, sorry.

For browser, the relevant question would be where to navigate to when somebody navigates to
  
  http://example.com/#x%2525

and the HTML document contains elements with the IDs "x%25" and "x%2525".

**Comment by annevk** [comment]
It would go to the latter per https://html.spec.whatwg.org/#the-indicated-part-of-the-document. Only if that's not there would it go the former. Pretty sure that matches implementations.

**Comment by reschke** [comment]
OK, so this might "work" for HTML. But not every fragment identifier is resolved in the context of HTML, not even in browsers.

**Comment by annevk** [comment]
> I'm not going to explain why removing of escaping needs to predictable in general, sorry.

It needs to be predictable where it can be observable, but, e.g., whether a server errors on `/%` or allows it doesn't matter much.

**Comment by annevk** [comment]
FWIW, thanks to @reschke's comments I had a closer look and discovered a whole bunch of issues around fragments: https://github.com/whatwg/html/pull/3111. None really about the percent decoding aspect itself (other than applying it to strings rather than bytes), but more about encodings.
