### ISSUE TITLE
Inconsistency between Chrome/Node.js in url parsing spec

### ISSUE THREAD

**Issue by bcoe** [whatwg/url#345]
I was digging into a [Windows bug in Node](https://github.com/nodejs/node/pull/15490) and found an inconsistency between Chrome's implementation of the URL spec and what's written in the [file-slash-state](https://url.spec.whatwg.org/#file-slash-state) spec.

Reading the spec, it sounds like if I resolve:

```bash
new URL('/C:/foo', 'file:///D:/bar')
```

I would expect the URL to resolve as:

```bash
/D:/foo
```

## Chrome's Parse:

```js
new URL('/C:/foo', 'file:///D:/bar')
URL {href: "file:///C:/foo", origin: "file://", protocol: "file:", username: "", password: ""}
```

## Firefox's Parse

```js
new URL("/C:/a/b/c/module.mjs", "file://D:/foo/bar")
URL { href: "file:///C:/a/b/c/module.mjs", origin: "null", protocol: "file:", username: "", password: "", host: "", hostname: "", port: "", pathname: "/C:/a/b/c/module.mjs", search: "" }
```

## Node's Parse

```js
new URL('/C:/foo', 'file:///D:/bar')
{
  href: file:///D:/C:/foo
  protocol: file:
}
```

_wow, that's really wrong definitely should be fixed._

## Path Forward

It feels to me like Chrome's implementation is the most reasonable; if I resolve a URL `C:/foo/bar` it doesn't really make sense to me that I'd end up with a URL `D:/foo/bar` this is almost surely pointing to an invalid file path.

It might be worth updating this section of the spec to reflect Chrome's implementation (it might just be that myself and @bmeck are reading it wrong).

CC: @bmeck, @TimothyGu, @domenic @annevk, @jasnell 

_UPDATE: it looks like both Safari and Firefox parse the same as Chrome, this seems to point towards Brad and I misreading the spec?_

**Comment by rmisev** [comment]
This bug already fixed in the spec, see https://github.com/whatwg/url/pull/343.

**Comment by bcoe** [comment]
@rmisev wonderful -- if I'm reading the new instructions properly, we now _only_ set the drive section from the `base` if there's no drive section in the `path`; matching the behavior we're seeing in Chrome, Firefox, etc?
