### ISSUE TITLE
why are backslashes accepted for slashes?

### ISSUE THREAD

**Issue by bagder** [whatwg/url#346]
I've recently learned that several modern browsers accept backslashes in the URL and treat them as if they are slashes. `Location: http:\\\\\\\\\\\\\\\\\\example.com` is considered a fine absolute URL in an HTTP response and will redirect to `http://example.com`.

Can you please point out where it says that's how WHATWG URL parsers should act? I can't find it.

**Comment by TimothyGu** [comment]
For this particular case (after the scheme), it is [special authority *ignore* slashes state](https://url.spec.whatwg.org/#special-authority-ignore-slashes-state). For all other cases, go to [basic URL parser](https://url.spec.whatwg.org/#concept-basic-url-parser) and <kbd>Ctrl</kbd>+<kbd>F</kbd> "U+005C (\\)".

**Comment by TimothyGu** [comment]
Note, backslashes are not considered to be "valid", only "accepted", since a validation error is fired in [special authority slashes state](https://url.spec.whatwg.org/#special-authority-slashes-state) before going to special authority ignore slashes state.

**Comment by annevk** [comment]
Thanks @TimothyGu. I hope that answer helps @bagder, let me know if you need this reopened.

**Comment by bagder** [comment]
> Note, backslashes are not considered to be "valid", only "accepted"

But for a user that's effectively the same thing. The parser eats them and treats the string as if it was a valid URL.

It helped me understand that your spec says this is a fine URL. As you know, I protest against this (as well). Thanks for clarifying!

**Comment by domenic** [comment]
I know @bagder was already involved in the conversation, and doesn't find the distinction convincing, but for anyone else watching, here are some reasons behind the distinction between "valid" and "accepted": https://github.com/whatwg/url/issues/118#issuecomment-276290654. (The TL;DR is it's similar to how we distinguish between valid HTML, which a validator says is OK, and the fact that browsers will accept any sequence of bytes as a parsed HTML document.)

**Comment by timmc** [comment]
Here's a fun example of what happens when some people implement RFC 3986 and some follow WHATWG's "loose" definition: <https://bugs.xdavidhu.me/google/2021/12/31/fixing-the-unfixable-story-of-a-google-cloud-ssrf/>. Not my story, but I ran across it today, then ended up here after trying to figure out why WHATWG is including this character.
