### ISSUE TITLE
Need more changes for common deploy

### ISSUE THREAD

**Issue by annevk** [whatwg/url#353]
https://github.com/whatwg/url/commit/3b6b0b4b4d2857df06b4414dc47d6ff22622ef08 didn't include everything https://github.com/whatwg/fetch/commit/948505d35344cd99599f52458ad8898e99ce2afc did. In particular .gitignore, Makefile, and README.md changes are still needed.

cc @foolip

**Comment by domenic** [comment]
This has since been taken care of except for deploy.sh in gitignore. Since that's not crucial let's close this. (Or reopen if you disagree.)
