### ISSUE TITLE
case-insensitive domain names

### ISSUE THREAD

**Issue by aaronpk** [whatwg/url#357]
I was expecting to find some mention of domain names being case insensitive in https://url.spec.whatwg.org/#valid-domain, but couldn't find any trace of a mention of it.

**Comment by annevk** [comment]
"domain to ASCII" does that (through the lookup table bit, which requires some digging to find).

**Comment by aaronpk** [comment]
Yeah, that's buried enough that I'm going to make an explicit mention of it in a spec I'm writing that references this URL spec. I don't think that anyone following my reference to the URL spec would find that when reading through the references.

**Comment by annevk** [comment]
I'll leave this open as I might add a note here as well. This isn't the first question we had about it.

**Comment by annevk** [comment]
Merging this into #245. (No real progress here unfortunately.)
