### ISSUE TITLE
Clarify status of empty path segments

### ISSUE THREAD

**Issue by mithrandi** [whatwg/url#358]
4.5.6 says "Otherwise, then for each string in url’s path, append U+002F (/) followed by the string to output.", referencing 4.1 which gives "A URL’s path is a list of zero or more ASCII strings **holding data**, usually identifying a location in hierarchical form. It is initially empty." (emphasis mine). An empty (zero length) path segment does not hold data… but then 4.3 mentions that a path segment can have "zero or more URL units".

Is 4.3 (URL writing) meant to be prescriptive over 4.5 (URL serialization)? That is, should the URL `https://example.com/foo//bar` be considered equivalent to or distinct from `https://example.com/foo/bar`?

The spec seems to be laid out in a way that makes this confusing, and I see that the earlier language in 4.5.6 about empty path segments [was deleted](https://github.com/whatwg/url/pull/213/files#diff-03b21320f26423640f89c447968191e5L2144). On the other hand, I found [this test case](https://github.com/w3c/web-platform-tests/blob/4ea8eae2fd807ffd22e84f3c2f2ca12f798f8206/url/urltestdata.json#L2100-L2114) that suggests empty path segments should be allowed in a normalized URL.

**Comment by TimothyGu** [comment]
> An empty (zero length) path segment does not hold data

In the spec’s sense, it does. But I can see how that can be confusing, and “holding data” should probably just be removed.

> Is 4.3 (URL writing) meant to be prescriptive over 4.5 (URL serialization)?

No; the algorithm in 4.5 is prescriptive, while 4.3 is more of a set of guidelines for writing valid URLs than actual specification.

**Comment by domenic** [comment]
https://url.spec.whatwg.org/#urls tries to clarify the relationship between 4.3 and 4.5, based on historical confusion. Maybe it still isn't enough...

**Comment by annevk** [comment]
@mithrandi do you still think some kind of clarification is warranted here?

FWIW, personally I think the empty string still counts as holding data. It also affects how it's serialized so it's not a no-op or some such.

**Comment by mithrandi** [comment]
I agree with @TimothyGu that "holding data" should be deleted from that sentence in that case. I don't mind considering an empty string to "hold data", but then the phrase adds nothing to the description, and I think trying to figure out what it might add introduces potential confusion.

Would it be reasonable to add an example of `http://example.org//` to the examples at https://url.spec.whatwg.org/#example-url-parsing ? I guess this _almost_ overlaps the `https://////example.com///` example, but that URL is invalid whereas this one would be valid.

**Comment by annevk** [comment]
The purpose of "holding data" which we use in several places is mostly since the current text tries to identify a purpose for each of the parts of a URL.
