### ISSUE TITLE
"Let ipv4Host be the result of IPv4 parsing asci..."

### ISSUE THREAD

**Issue by cpacejo** [whatwg/url#367]
https://url.spec.whatwg.org/commit-snapshots/5fc4c4c17f3077beda5e3647df73f4b1b0ba7084/#host-parsing

> Let ipv4Host be the result of IPv4 parsing asciiDomain\.

This algorithm differs in a dangerous way from that in RFC 3986, in that it percent-decodes the host *before* determining if it is an IPv4 literal.  RFC 3986 dictates that percent-decoding must not occur until AFTER the host has been parsed.  So by RFC 3986, a percent-encoded IPv4 literal is to be treated as a "regname".

This means that a RFC 3986 WAF would pass such percent-encoded literals, which a WHATWG-URL application would then interpret as an IPv4 address.

The algorithm should be changed to match the behavior of RFC 3986, or (better yet) to explicitly disallow hosts which are valid IPv4 addresses after percent-decoding.

**Comment by annevk** [comment]
RFC 3986 does not reflect how (major) implementations behave. That's the whole reason why we have this standard...

**Comment by cpacejo** [comment]
Have you surveyed WAFs, proxies, etc., to determine that they also follow this broken behavior?  Because in a security context, that's what matters.

Documenting broken behavior doesn't make it correct or safe.  It's good that you've discovered this discrepancy, but the correct thing to do from a "specification" standpoint is to disallow inconsistently-implemented, unnecessary corner cases.  (And the correct thing to do as the representatives of said "(major) implementations" which the WHATWG is, is to fix the broken behavior of the unused corner cases.)

Permitting incompatible behavior in what amounts to an unauthoritative spec (there are many many other users of URIs than those represented by the WHATWG) serves only to promulgate security issues and ecosystem fragmentation.

**Comment by annevk** [comment]
I agree that parsing differences can/have lead to security issues. But it's also pretty clear to me that clients cannot align with RFC 3986 due to deployed content that needs to continue working. Therefore it seems best for all software to align on the URL Standard and thereby remove the parsing differences.

Having said that, it might be worth investigating if this can be changed, but even if it could, it doesn't really address the fundamental problem which is diverging URL implementations.

**Comment by annevk** [comment]
Per https://jsdom.github.io/whatwg-url/#url=aHR0cHM6Ly8xMjMlMmUxMjMv&base=YWJvdXQ6Ymxhbms= all browsers are aligned on this. Closing this therefore.
