### ISSUE TITLE
"For each code point in input, UTF-8 percent enc..."

### ISSUE THREAD

**Issue by cpacejo** [whatwg/url#368]
https://url.spec.whatwg.org/commit-snapshots/5fc4c4c17f3077beda5e3647df73f4b1b0ba7084/#host-parsing

> For each code point in input, UTF\-8 percent encode it using the C0 control percent\-encode set, and append the result to output\.

Why are we percent-*encoding* during the host *parsing* algorithm?  Maybe I'm misunderstanding something but I think this should be percent-*decoding*.

**Comment by annevk** [comment]
Because that is how non-special schemes works, effectively, e.g., `new URL("test://†/").href` === `test://%E2%80%A0/`.

**Comment by annevk** [comment]
Note that we do percent-decode for HTTP URLs.

**Comment by domenic** [comment]
Closing as this appears to be addressed. Let us know if it wasn't clear in some way :).

Stated another way, the canonical form (i.e. the form stored in the URL record) of non-special-scheme hosts is the percent-decoded form.
