### ISSUE TITLE
Qualify exported URL terms that are too generic

### ISSUE THREAD

**Issue by fantasai** [whatwg/url#375]
https://url.spec.whatwg.org/commit-snapshots/5fc4c4c17f3077beda5e3647df73f4b1b0ba7084/#url-representation

The URL spec is exporting a bunch of terms relating to parts of a URL. This is fine, but some of them are a bit too generic and end up creating auto-linking conflicts. It would be helpful if e.g. `A URL’s <dfn export>fragment</dfn>` were written as `A URL’s <dfn lt="URL fragment" local-lt="fragment" export>fragment</dfn>` so that the exported term includes the word “URL”. (The local-lt attribute allows the unqualified term to be used within the URL spec itself.)

**Comment by annevk** [comment]
It's already qualified using the `for` attribute, which I think is the recommended route for namespacing. If you have a fragment, you likely want to qualify it with a `for` attribute too, to indicate what the fragment is part of.

**Comment by fantasai** [comment]
Whatever you're doing as far as namespacing goes, it's hijacking `<a>fragment</a>` in all the CSS specs. Where it's used as a noun, I can disambiguate it as “box fragment” at the cost of a little wordiness, but there isn't much I can do where it's used as a verb, other than put in an explicit override to link it to css-break-3.  Which I'd be willing to live with if I didn't think that you shouldn't be exporting the term “fragment” when “URL fragment” would be a better term for cross-linking anyway. :)

> If you have a fragment, you likely want to qualify it with a `for` attribute too, to indicate what the fragment is part of.

`<dfn for="CSS">fragment</dfn>`? I mean, at that rate, I should have a `for` attribute on every exported term in the entire CSS specification corpus... Not that it'll help anything--afaict, the `for` attribute only works on syntactic constructs like methods, attributes, and property values, not regular terms. https://tabatkins.github.io/bikeshed/#autolinking

CC @tabatkins

**Comment by annevk** [comment]
I want to export this the way I do, since the way this would be used is

> _someURL_'s fragment

not

> _someURL_'s URL fragment

But also, yeah, `for` is pretty important and using it is not too bad.

**Comment by tabatkins** [comment]
"fragment" is a really generic term no matter what; that sort of thing really should have a `for` value, no matter where it shows up.  URL fragment should have `for=URL` (which it does), box fragment should have `for=CSS` or something.  I do the same thing for "parse" in css-syntax; it's too generic of a term to just leave unadorned.

URL isn't "hijacking" anything here; `<a>fragment</a>` causes Bikeshed to properly emit a Link Error (because it can't decide between `css-break-3` and `url`), and it then makes an "arbitrary choice" between the two references ("arbitrary" because it's dependent on dict iteration order in Python).

(Adding a `for=CSS` won't change this behavior, btw.  The two references will still be ambiguous given that autolink.)

You can specify a link default for this in a given spec, or specify the `for` value directly on the link; if you're using the link shorthand, it's just `[=CSS/fragment=]`.

> Not that it'll help anything--afaict, the for attribute only works on syntactic constructs like methods, attributes, and property values, not regular terms. 

No, it works on everything.  (It's treated as a completely opaque namespace identifier.)

**Comment by fantasai** [comment]
@annevk within the URL spec, I'd expect using the first formulation (hence the local-lt), but outside of it I think writing the second one makes it clear you're talking about a URL fragment and not something else. Similar reason to why in the grid spec I might use grid terms without “grid” written in front of them, but I export them with “grid” included, e.g. “grid track” or “grid row”--even if another spec (like css-align) is in a paragraph very clearly about grids, since it's not all about grids, it's clearer (and not painfully redundant, as it would be in the grid spec) to use “grid row” instead of just “row”... If in a particular sentence I want to use just “row” (since I already listed, e.g. “grid column” earlier in the sentence), I can use `lt=` to shorten it.

@tabatkins If the new plan is to have every instance of a cross-linked term in every CSS spec explicitly namespaced to CSS, lmk and I'll set aside some time to write a preprocessor for your preprocessor. :) That way we'll have a cross-module concept of local terms for the full set of CSS specs, which is another way of solving the immediate problem here.

I still think making the «URL» “namespace” explicit in the term, rather than hiding it as metadata, would be an improvement to the set of exported terms here, though. It may be possible to namespace prose terms with Bikeshed, but relying on that is not imho as straightforward as relying on property-value/interface-method/element-attribute relationships--which, unlike hidden Bikeshed namespaces, are self-evident to the reader as well as inherent to the spec regardless of tooling. It's not just “fragment” (which happens to be what brought me here): “username” and “password” are very generic concepts that I don't think should be representing such a specific, localized concept in the global pool of exported vocabulary if we can so easily avoid it by localizing it. (Ditto “parse”, but I'll file that in the CSSWG repo.)

It helps both reduce tooling conflicts and encourage precision in wording (which helps the reader, who no longer needs to click through as often) to export terms that are more specific. In cases where the specificity is awkward, the editor of the incoming reference can always modulate it with `lt`, but it means the default cross-spec linking text is more specific.

**Comment by annevk** [comment]
I think it'd be a lot worse if, e.g., Fetch had to write `<a for=URL lt="URL fragment">fragment</a>` rather than `<a for=URL>fragment</a>`. And you do actually want that term since as I showed in my example above it's clear from context what the fragment belongs to.

**Comment by domenic** [comment]
I really like the current system because all you have to do is add one line to link-defaults and you get to set the default namespace as appropriate for your spec. Making it part of the term, instead of using the existing namespace mechanism, would require per-usage translation as @annevk demonstrates; the current system's per-document choice is great.

**Comment by tabatkins** [comment]
> If the new plan is to have every instance of a cross-linked term in every CSS spec explicitly namespaced to CSS, 

Don't be hyperbolic; as I explicitly said in my response, "fragment" is a very generic word and could use a `for`; most CSS terms have no such need.  (As evidenced by the fact that most definitions only appear once in the database.)
