### ISSUE TITLE
Don't coerce numbers to strings for port checking

### ISSUE THREAD

**Issue by benjamingr** [whatwg/url#377]
Following discussion from https://github.com/nodejs/node/issues/19595 cc @annevk @nodeav 

At the moment `URL`s convert ports passed as numbers to strings in order to get the port number (specified in https://url.spec.whatwg.org/#port-state ). This is like the `parseInt` algorithm in that it ignores things after the first dot - which enables the following behavior:

```js
var port = readPort(); // attacker returns 30 ** 30, , which gets coerced to 2.05891132094649e+44
// our validation: don't allow opening a connection to a lower-than 1024 port to the server.
if (typeof port !== 'number' || port < 1024) { 
  return false; 
}
serverUrl.port = port; // port set to 2
download(serverUrl); // user connected to port we didn't mean them to be able to connect to
```

This is a feature request to validate and ignore passed numbers to the port setter.

**Comment by annevk** [comment]
So this would mean changing the type from `USVString` to `([EnforceRange] unsigned short or USVString)` although then it would end up throwing.

If we want to ignore out-of-band values something like `(double or USVString)` is probably the way to go.

Either way, prose will need to be adjusted as well to deal with the fact that it can now receive a number.

**Comment by domenic** [comment]
Why include USVString in the type? I guess for the return value :-/. Unfortunate IDL limitation...

Alternately you could modify the parser to fail to parse such ports instead of gobbling up as much as it can?

**Comment by annevk** [comment]
I think we also want to keep `ToString()` for any objects passed to the setter (I haven't verified how IDL deals with number or string though, perhaps it does the wrong thing).

We could also modify the parser or perhaps the setter to terminate early if the value contains a "." or "e" or some such. Maybe that's easier.

**Comment by TimothyGu** [comment]
I think modifying the parser will be easier, but we have to make sure not to change how the parser works for non-state-overridden usage (i.e., full URL parses).

**Comment by benjamingr** [comment]
What would it take to move forward on this?

**Comment by annevk** [comment]
A concrete proposal for what exactly the change ends up looking like (perhaps even in the form of a PR) would be good. Then we'll have to convince at least one browser to implement it to see if it's actually feasible, update and add tests, and then get everyone else along too.

**Comment by annevk** [comment]
See also https://whatwg.org/working-mode#changes.

**Comment by benjamingr** [comment]
> A concrete proposal for what exactly the change ends up looking like (perhaps even in the form of a PR) would be good. Then we'll have to convince at least one browser to implement it to see if it's actually feasible, update and add tests, and then get everyone else along too.

Some _very general_ questions: 

 - Would Node qualify as an implementor?
 - Is Node a member of WHATWG? 

We've been integrating web APIs (like URL) and are looking into integrating more WHATWG APIs where it makes sense to improve browser <-> node compatibility.

**Comment by benjamingr** [comment]
Thanks a lot! I'll take this up internally in Node first and if I have any more questions I'll open a meta issue.

**Comment by annevk** [comment]
Closing this as there hasn't been movement here for quite a while suggesting the need has gone away. If this remains a common need I'm happy to reconsider though.
