### ISSUE TITLE
IPv4 serializer should use floor(n / 256), not n/256

### ISSUE THREAD

**Issue by domenic** [whatwg/url#39]
Otherwise you get some pretty strange IPs with long decimal portions.

**Comment by annevk** [comment]
Isn't `/` operating on integers doing that automatically?

**Comment by annevk** [comment]
I.e. integer division.

**Comment by domenic** [comment]
In C I guess,  but not in JavaScript or in math.



On Thu, Jul 9, 2015 at 11:24 PM -0700, "Anne van Kesteren" <notifications@github.com<mailto:notifications@github.com>> wrote:


I.e. integer division.

-

**Comment by SimonSapin** [comment]
https://encoding.spec.whatwg.org/#terminology has a paragraph that defines math operators. URL could do the same.

**Comment by domenic** [comment]
I think it would be simpler to just use normal math terminology and put a floor() around it.

**Comment by annevk** [comment]
floor() is defined as a thing?

**Comment by domenic** [comment]
I would think it's defined in the same way that other math is, like plus or minus. But I guess https://people.mozilla.org/~jorendorff/es6-draft.html#sec-algorithm-conventions defines it.

**Comment by annevk** [comment]
Given that this is likely implemented in terms of integers (including in JS once JS gets integers), it's still not entirely clear to me that pretending all numbers are floating points is really a viable strategy long term.

**Comment by domenic** [comment]
Well, all mathematical numbers are ... not floating points, but infinite precision. And whenever a spec does arithmetic, I assume it's doing it using math, not computers, unless otherwise stated. (Nobody thinks that when a spec does `0.1 + 0.2` you're supposed to get `0.30000000001`, or worse, that when a spec does `0.1 + 0.2` you're supposed to get `0`.)

**Comment by annevk** [comment]
Math has a concept of integer division: https://en.wikipedia.org/wiki/Division_%28mathematics%29#Of_integers

**Comment by domenic** [comment]
Yes, but it is not the conventional division (e.g. is not closed, and its output is two-part: quotient and remainder). If you're really set on division in this spec meaning integer division then I guess you could define it. That just seems obtuse to me though.

**Comment by annevk** [comment]
Sorry for being stubborn.
