### ISSUE TITLE
What is the correct value that should be passed for processing_option?

### ISSUE THREAD

**Issue by TRowbotham** [whatwg/url#400]
In the [domain to ASCII](https://url.spec.whatwg.org/#concept-domain-to-ascii) algorithm, it is explicitly stated that processing_option should be set to Nontransitional_Processing. However, the [domain to Unicode](https://url.spec.whatwg.org/#concept-domain-to-unicode) algorithm does not explicitly state whether Transitional or Nontransitional processing should be used. Am I correct to assume that Transitional processing should be used here?

> Let result be the result of running Unicode ToUnicode with domain\_name set to domain, CheckHyphens set to false, CheckBidi set to true, CheckJoiners set to true, and UseSTD3ASCIIRules set to false\.

The steps in [valid domain](https://url.spec.whatwg.org/#valid-domain) also don't explicitly state which processing_option should be used. Am I correct to assume that Transitional processing is also used here?
> Set result to the result of running Unicode ToUnicode with domain_name set to result, CheckHyphens set to false, CheckBidi set to true, CheckJoiners set to true, and UseSTD3ASCIIRules set to true.

**Comment by annevk** [comment]
I suspect this should be Nontransitional as well. The main problem with this algorithm in general is that it isn't exposed to script at the moment and what browsers implement is more complicated. See #274 for some past discussion.

**Comment by TRowbotham** [comment]
Thanks for the clarification. I had read through all the idna labeled issues previously, but didn't really find an answer in them.

**Comment by TimothyGu** [comment]
How interesting, the Transitional flag for ToUnicode was added in the most recent update. [Previously](https://www.unicode.org/reports/tr46/tr46-19.html#ToUnicode), ToUnicode always used Nontransitional. We should replicate that behavior.
