### ISSUE TITLE
Authority State of URL Parser has Unconditional Validation Error?

### ISSUE THREAD

**Issue by SethMichaelLarson** [whatwg/url#408]
I'm having a hard time implementing the Authority state section of the URL parser. The rest of the state machine seems so straightforward and my implementation works properly for every section except Authority. Here's an example scenario my current implementation arrives on with a starting input of `https://foo:bar@www.google.com`:

```json
{
    "url": {
        "scheme": "https",
        "host": null,
        "port": null,
        "username": null,
        "password": null,
        "query": null,
        "fragment": null,
        "path": []
    },
    "base": null,
    "state": "authority",
    "buffer": "foo:bar",
    "c": "@",
    "remaining": "www.google.com"
}
```

From the spec it seems that because `c` is `@` we would receive a validation error?  I also don't see how the username and password can be set without hitting a validation error? What am I missing about this section?

Makes me wonder if Authority state section 1.1 is actually supposed to be a part of section 1.2?

https://url.spec.whatwg.org/commit-snapshots/6800342832fdf99caa265d0106cf984123716d9d/#url-parsing

**Comment by sideshowbarker** [comment]
> From the spec it seems that because `c` is `@` we would receive a validation error?

Yes, it triggers a validation error. But that doesn’t mean parsing fails, and that step in the algorithm doesn’t fail. So your implementation  moves on to parse the username and password and set them.

See https://url.spec.whatwg.org/#validation-error:

> A **validation error** indicates a mismatch between input and valid input. User agents, especially conformance checkers, are encouraged to report them somewhere.
> **Note:** A validation error does not mean that the parser terminates. Termination of a parser is always stated explicitly, e.g., through a return statement.
> It is useful to signal validation errors as error-handling can be non-intuitive, legacy user agents might not implement correct error-handling, and the intent of what is written might be unclear to other developers.

So if your implementation eports validation errors, then you just report the validation error and keep parsing. There’s no failure. Or if instead implementation doesn’t report validation errors, then the validation error is just a noop — and again in that case, you just keep parsing.

> I also don't see how the username and password can be set without hitting a validation error?

The username and password can’t be set without hitting a validation error. But setting the username and password is orthogonal to reporting the validation error. The validation error doesn’t cause failure.

**Comment by SethMichaelLarson** [comment]
Sure, I guess it just stood out to me as all other "sections" of a URL were parsable without receiving a validation error. Okay, thanks!
