### ISSUE TITLE
Reject extra leading zeroes in IPv4 addresses?

### ISSUE THREAD

**Issue by SimonSapin** [whatwg/url#41]
IPv4-in-IPv6 does it. The step “*Otherwise, if value is 0, parse error, return failure.*” rejects addresses like `::01.0.0.0`.

Should IPv4 do the same? A single leading zero there indicates an octal component, but the input could have more: `000010.0.0.0`. Or there could be leading zeroes after the hexadecimal indicator: `0x00010.0.0.0`.

**Comment by annevk** [comment]
We could make it a conformance error perhaps. Implementations support leading zeros just fine for IPv4.

**Comment by SimonSapin** [comment]
Ok. I don’t care too much.
