### ISSUE TITLE
Clarify query state percent-encoding (parsing)

### ISSUE THREAD

**Issue by mkgl** [whatwg/url#411]
Hi,

I've been scratching my head trying to figure out where do square brackets (e.g. U+005B) get exempted from [percent-encoding](https://url.spec.whatwg.org/#percent-encode), in the [query state](https://url.spec.whatwg.org/#query-state).

To compare with the [path state](https://url.spec.whatwg.org/#path-state):

> 3. [UTF-8 percent encode](https://url.spec.whatwg.org/#utf-8-percent-encode) [c](https://url.spec.whatwg.org/#c) using the [path percent-encode set](https://url.spec.whatwg.org/#path-percent-encode-set), and append the result to _buffer_.

I understand that—since U+005B ([) is not present in that set—it is returned _as is_ (as per [UTF-8 percent encode](https://url.spec.whatwg.org/#utf-8-percent-encode)). 

In the [query state](https://url.spec.whatwg.org/#query-state), encoding is expressed on a _byte_ basis:

> 1. If one of the following is true
>     * _byte_ is less than 0x21 (!)
>     * _byte_ is greater than 0x7E (~)
>     * _byte_ is 0x22 ("), 0x23 (#), 0x3C (<), or 0x3E (>)
>     * _byte_ is 0x27 (') and url is special
>
>     then append _byte_, [percent encoded](https://url.spec.whatwg.org/#percent-encode), to _url_’s [query](https://url.spec.whatwg.org/#concept-url-query).
> 
> 2. Otherwise, append a code point whose value is _byte_ to _url_’s [query](https://url.spec.whatwg.org/#concept-url-query).

Wouldn't it be equivalent to express a query percent-encode set as follows? That would make it much less convoluted imho.

> 💡 The **query percent-encode set** is the [C0 control percent-encode set](https://url.spec.whatwg.org/#c0-control-percent-encode-set) and U+0020 SPACE, U+0022 ("), U+0023 (#), U+003C (<), and U+003E (>).

Only the [special](https://url.spec.whatwg.org/#is-special) case about U+0027 (') would have to remain, not sure what to do about that.

Any thoughts?

Secondary question: in various states there is early validation:

> If [c](https://url.spec.whatwg.org/#c) is not a [URL code point](https://url.spec.whatwg.org/#url-code-points) and not U+0025 (%), [validation error](https://url.spec.whatwg.org/#validation-error).

U+005B ([) doesn't fall into the definition of [URL code points](https://url.spec.whatwg.org/#url-code-points). Does this mean that URLs containing such character in path/query components are considered invalid, despite being commonly accepted and parsing successfully?

Cheers,
Mika

**Comment by mgiuca** [comment]
Hi Mika,

For the first part of your question, I've thought pretty deeply about this. I think it *would* be much clearer to express query using the same encoding method as the rest of the logic, but it's more complex because the query (and only the query) can have arbitrary encoding selected.

Here's a WIP PR I've been working on:
https://github.com/mgiuca/url/tree/query-uses-normal-encode-set

**Comment by annevk** [comment]
Indeed, ideally something like https://checker.html5.org/ would check URL validity, but, e.g., browsers are not expected to check for it as it would likely impact performance too much.

**Comment by mkgl** [comment]
Matt, Your PR does look promising. :)

Re: validity, I would think—in spite of the goal to align with/obsolete the RFCs—why not reinstate these characters as valid then, in specific components, since it's what browsers happen to do? 🤔

Processors are increasingly becoming aware about _this_ spec, because most clients are the browsers implementing it. Cat and mouse. :)

Thank you both,

**Comment by annevk** [comment]
#508 has a PR for the refactoring of query state. I think it turned out quite well so I think we should do that. Let me know what you think.

I don't really want to fiddle with validity at this point, but if you feel strongly we should consider expanding the set of URLs that are valid let's discuss that in a new issue.

**Comment by annevk** [comment]
Unfortunately that refactoring was wrong. I wish I had realized a little sooner, but it is how it is. See #517.

**Comment by annevk** [comment]
@mgiuca surprised you never submitted that branch as it looks really good. Was there anything wrong with it? I'll put up a PR inspired by your work later.

**Comment by mgiuca** [comment]
Hi @annevk, do you mean the non-pull-request in this branch https://github.com/mgiuca/url/tree/query-uses-normal-encode-set ?

I probably uploaded it but then intended to do a proper submission but never got around to it. Sorry 😞 . I've lost the mental state on it, but if you think it looks good, I can merge it forward and submit a PR.

I just had a quick go at git merging it forward. As expected, there were pretty big merge conflicts, so I'll have to dedicate some time to doing it. If you get time, feel free to take my branch and work with it.

**Comment by annevk** [comment]
@mgiuca please don't, I'm nearly ready with my variant. I mainly wanted to know if you had any concerns that hold you back. Losing energy to work on something is totally understandable.

**Comment by mgiuca** [comment]
Ack, and thanks for understanding.

**Comment by mgiuca** [comment]
Yay! Good work @annevk !
