### ISSUE TITLE
Make combining a URL (string) with a query easier

### ISSUE THREAD

**Issue by annevk** [whatwg/url#413]
In particular if you have a URL, either as a string (inc. a relative URL) or an object, and some kind of structure that could be passed to `URLSearchParams`'s constructor, it should be easier to get a new URL out of that (either a string or object).

What you can currently do is something like (substitution):
```js
const url = new URL(input, location);
url.query = new URLSearchParams(params);
```
or (additive):
```js
const url = new URL(input, location);
Object.keys(params).forEach(key => url.searchParams.append(key, params[key]))
```
Both are quite verbose. Perhaps something like
```
URL.withQuery(input, params)
```
though note you'd lose the base argument (we'd grab that from the global) and flexibility on substitution or additive (gotta pick).

**Comment by phistuck** [comment]
What about making `URLSearchParams.prototype.append` take an object? Or maybe add `URLSearchParams.prototype.appendAll(objectOrArrayOfPairs)`?

**Comment by annevk** [comment]
If libraries identify a popular pattern here I'm sure it'll be suggested here long term (or using libraries is deemed adequate, which is also acceptable).
