### ISSUE TITLE
How are hosts in custom schemes to be handled?

### ISSUE THREAD

**Issue by felixfbecker** [whatwg/url#418]
Currently all JS engines behave differently when it comes to hosts with custom protocols: https://felixfbecker.github.io/whatwg-url-custom-host-repro/

What is the correct behavior?

**Comment by annevk** [comment]
whatwg-url and Node generally match the standard (at least the tests). Safari is close.

**Comment by annevk** [comment]
I know Chrome, Edge, and Firefox at least have a general "implement the URL standard" bug. It might be worth filing more specific bugs though.

I'm pretty sure this is tested, e.g., `sc://faß.ExAmPlE/` in https://github.com/web-platform-tests/wpt/blob/master/url/resources/urltestdata.json.
