### ISSUE TITLE
Define "lowercased"

### ISSUE THREAD

**Issue by cvrebert** [whatwg/url#42]
The spec makes a couple references to "*X*, lowercased". Lowercasing should be formally defined.
The HTML spec defines such an algorithm: https://html.spec.whatwg.org/multipage/infrastructure.html#converted-to-ascii-lowercase

**Comment by annevk** [comment]
It only does so when the input is already ASCII, no? But I guess we can define it more formally even then.

**Comment by cvrebert** [comment]
> It only does so when the input is already ASCII, no?

Indeed. I'm suggesting this to further decrease ambiguity.

**Comment by cvrebert** [comment]
So would you prefer to copy the definition into this spec, or to cite the definition from one of the other specs?

**Comment by annevk** [comment]
I would probably include a definition in this specification, written analogous to https://fetch.spec.whatwg.org/#byte-lowercase.

At some point I'd like to create a dictionary document of sorts, that includes all these things. So they're only defined once.
