### ISSUE TITLE
Remove "optional" for the init in URLSearchParams constructor?

### ISSUE THREAD

**Issue by CYBAI** [whatwg/url#424]
As the algorithm of constructor has been updated to make URLSearchParams constructor always have an init parameter at #334, should we also update the `WebIDL` of it to not have `optional`?

```diff
- [Constructor(optional (sequence<sequence<USVString>> or record<USVString, USVString> or USVString) init = ""),
+ [Constructor((sequence<sequence<USVString>> or record<USVString, USVString> or USVString) init = ""), 
```

**Comment by domenic** [comment]
No. Then `new URLSearchParams()` would be required to throw.

`optional` is what _allows_ the algorithm to assume that the _init_ parameter exists. It's an instruction to the IDL preprocessor steps that say "if no value was passed, or if undefined was passed, then set _init_ to the default value" (in this case indicated by `= ""`).

In other words it's syntactically invalid to have `= ""` without having `optional`.

**Comment by CYBAI** [comment]
Ah, I see! Thanks for the very clear explanation :)

Let me close this issue then.
