### ISSUE TITLE
searchParams.set("param", undefined) should not stringify as param=undefined

### ISSUE THREAD

**Issue by LeaVerou** [whatwg/url#427]
This is a followup from [this Twitter poll](https://twitter.com/LeaVerou/status/1089634098430267398) since @annevk said there may be hope for change.
It appears that most people expect special behavior for `undefined` that in some way clears the value of the parameter. Only one in four expect the current behavior of having it cast to the string `"undefined"`.

@annevk said it might be possible to make the second argument optional, and have it default to the empty string, which would solve this.
Defaulting to deleting the parameter would also be reasonable. As far as I'm concerned, any of these options is reasonable, and better than the current behavior.

Anecdotal backstory: The reason I posted that poll in the first place was that on that day I had struggled for a while to debug why a Github API call was producing a 404 error even though the file definitely existed. It turned out that my code was using `searchParams.set("ref", this.branch)` to set the branch of the request. `this.branch` was undefined (in order to use the default branch, which was the API call default), so the API call ended up requesting a branch called "undefined", which of course didn't exist!

cc @domenic

**Comment by annevk** [comment]
I think if Chrome was willing to make this change (and also for `get()`, it should not diverge) and they don't get reports that's probably evidence enough. It seems rather unlikely it becoming "`undefined`" is something a server relies on, but as you say, it's hard to prove.

cc @domenic (sorry, not sure who from Chrome deals with this API)

**Comment by domenic** [comment]
I was hoping to have more discussion on this; that's why I encouraged opening the issue.

I don't think the poll doesn't clearly points any particular behavior as favored; the results are fairly evenly split. The OP advocates for some kind of clearing, but in the poll only a very slight minority (57%) seem to expect that, and among that camp folks have diverging opinions on what "clearing" means. Whereas the folks that expect the status quo are 43%. So it seems like any clearing change we make would be moving from expected-by-43% to either expected-by-30% or expected-by-27%. If anything, the poll points toward keeping the status quo!

As for my personal take, I think `"undefined"` makes the most sense because that's how normal `Map`s work. Setting to `undefined` doesn't delete an entry from the `Map`; it also doesn't convert the `undefined` into an empty string. It instead adds an entry to the Map with the given key, and `undefined` as the value. Then, when you go to stringify all entries in the Map and concatenate them into a query string, the simpler implementation would _not_ ignore `"foo"` / `undefined`, or treat that as `"foo"` / `""`. It would just treat such a pair like it does all other pairs. The OP seems to be asking for some special-casing of key/value pairs where the value is `undefined`, which to me seems more complex.

**Comment by LeaVerou** [comment]
@domenic 

> The OP advocates for some kind of clearing, but in the poll only a very slight minority (57%) seem to expect that

I'm not sure how 57% is "a very slight minority". It's a majority by definition. 🤔

> Whereas the folks that expect the status quo are 43%.

How is 43% favoring the status quo? I see 26%. Are you adding it with the 17% which knows what the answer is? That doesn't make the answer intuitive to them, it just means they're exposed to it already, so their vote would not be useful. Ideally, the percentages should be calculated with that 17% ignored (i.e. 26/83, 30/83, 27/83).

> So it seems like any clearing change we make would be moving from expected-by-43% to either expected-by-30% or expected-by-27%. If anything, the poll points toward keeping the status quo!

You are assuming that for those who expect clearing, all other options are equivalently against their expectations. I'd argue that all clearing options are much closer to their expectations than the current behavior. I'd also argue that all clearing options would trigger fewer bugs in their code, since `""` or `null` are all expected values for a query parameter, whereas `"undefined"` is pretty much always the result of a bug.

> As for my personal take, I think "undefined" makes the most sense because that's how normal Maps work.

Regarding internal consistency, `JSON.stringify()` is just as relevant as `Map`, if not more:
```js
> JSON.stringify({a: 1, a: undefined})
< "{}"
```

>  The OP seems to be asking for some special-casing of key/value pairs where the value is undefined, which to me seems more complex.

Javascript *in general* special-cases `undefined` in a number of places. It's not that unheard of. But I like the way Anne put it better: it's not special casing `undefined`, it's making the value argument optional. Then, special-casing `undefined` just naturally follows.

**Comment by domenic** [comment]
Apologies for the typo.

I don't think JSON.stringify is a relevant precedent, as it operates on object literals, not set() method calls.

**Comment by mieszko4** [comment]
My problem is somehow related.
For me `searchParams.set("param", undefined)` should stringify to `param` (without `=` sign)

## Reasoning
Take a look at example `?param1=&param2` (note only one `=`)
For me these two params have different values:
* value of `param1` is empty string
* value of `param2` is `undefined`

Currently I am not able to render url search query without `=` using `URLSearchParams` which makes the url look ugly.

Any thoughts? Am I missing something?

## Another approach
Another approach for solving my problem would be having something like `.toString({ skipRenderingEqualSingForParamsWithEmptyValue: true })`

**Comment by annevk** [comment]
@mieszko4 that's not supported by https://url.spec.whatwg.org/#application/x-www-form-urlencoded. Missing `=` is equal to value being the empty string.

**Comment by mieszko4** [comment]
thnx @annevk !
you mean this part, right?

> 2. If bytes contains a 0x3D (=), then let name be the bytes from the start of bytes up to but excluding its first 0x3D (=), and let value be the bytes, if any, after the first 0x3D (=) up to the end of bytes. If 0x3D (=) is the first byte, then name will be the empty byte sequence. **If it is the last, then value will be the empty byte sequence.**
> 3. Otherwise, let name have the value of bytes and **let value be the empty byte sequence**.

Since it is in spec and any change there would be breaking I I then propose to have a formatting option like:
`.toString({ concise: true })`

I added a new proposal here: https://github.com/whatwg/url/issues/469

**Comment by karlhorky** [comment]
For anyone looking for a userland solution for this, this is what we ended up with:

```ts
function setQueryParam(queryParamName: string, queryParamValue: number | undefined) {
  let queryString;

  const newSearchParams = new URLSearchParams(window.location.search);

  if (typeof queryParamValue === 'undefined') {
    newSearchParams.set(queryParamName, '');
    queryString = newSearchParams.toString().replace(
      new RegExp(`${queryParamName}=`),
      queryParamName,
    );
  } else {
    newSearchParams.set(queryParamName, String(queryParamValue));
    queryString = newSearchParams.toString();
  }

  const newUrl = `${window.location.origin}${window.location.pathname}?${queryString}`;

  return newUrl;
}
```

Usage:

```ts
setQueryParam('a', 'b'); // 'https://github.com/whatwg/url/issues/469?a=b'
setQueryParam('a', undefined); // 'https://github.com/whatwg/url/issues/469?a'
```

**Comment by Tal-OXS** [comment]
another suggestion:

searchParams.set("ref", this.branch || '')
