### ISSUE TITLE
Define domain label

### ISSUE THREAD

**Issue by annevk** [whatwg/url#435]
As identified in #434 we need to talk about domain labels from first principles somehow. There's various RFCs:

* https://tools.ietf.org/html/rfc1034#section-3.1 and https://tools.ietf.org/html/rfc8499, but these are problematic as they are byte-based.
* https://tools.ietf.org/html/rfc5890#section-2.3.2.1 is probably closest, but has some talk about validity that I'm not sure apply given we use different validation rules from IDNA2008...

Perhaps split domain on "." is best, since any relevant normalization will have already happened at that point (where we have determined it's a domain). And then reference some RFCs non-normatively.

See also #396.

**Comment by TimothyGu** [comment]
The definition by [UTS #46](https://www.unicode.org/reports/tr46/#Notation) seems quite relevant:

> In this document, a <em>label</em> is a substring of a domain name. That substring is bounded on both sides by either the start or the end of the string, or any of the following characters, called <em>label-separators</em>:
>
> 1. U+002E ( . ) FULL STOP
> 2. U+FF0E ( ． ) FULLWIDTH FULL STOP
> 3. U+3002 ( 。 ) IDEOGRAPHIC FULL STOP
> 4. U+FF61 ( ｡ ) HALFWIDTH IDEOGRAPHIC FULL STOP

**Comment by annevk** [comment]
I think that definition is only relevant pre-parsing. The non-U+002E separators are all normalized by the time the URL standard holds something it calls a "domain".

**Comment by annevk** [comment]
This is what I wrote down:

> `The <dfn export id=concept-domain-label>domain labels</dfn> of a <a>domain</a> <var>domain</var> are the result of <a>strictly splitting</a> <var>domain</var> on U+002E (.).`

However, our domains are ASCII and the rendering section wants to talk about their Unicode counterparts so this probably needs more work to be fully proper.
