### ISSUE TITLE
Definition of "valid opaque-host string" contradicts parser

### ISSUE THREAD

**Issue by ExplodingCabbage** [whatwg/url#437]
Per the definitions in https://url.spec.whatwg.org/#urls, I believe that the following is a [*valid URL string*](https://url.spec.whatwg.org/#valid-url-string)

```
qwe://foobar/baz
```

with a [*valid opaque-host string*](https://url.spec.whatwg.org/#valid-opaque-host-string) of `foobar`, whereas

```
qwe://foo^bar/baz
```

is *not* a valid URL string because `^` is not a ["URL unit"](https://url.spec.whatwg.org/#url-units) and therefore `foo^bar` is not a valid opaque-host string (which is defined to be made up of URL units).

However, the parser disagrees. If I step through the [parsing algorithm](https://url.spec.whatwg.org/#concept-basic-url-parser) with `qwe://foo^bar/baz` as input, then `foo^baz` ultimately gets passed to the [opaque-host parser](https://url.spec.whatwg.org/#concept-opaque-host-parser) without any validation error being triggered, and then the opaque-host parser in turn returns `foo^bar` without a validation error.

I believe this is a spec bug; as I understand https://url.spec.whatwg.org/#urls, a string is meant to be a "valid URL string" if and only if it does not trigger an error from the URL parser. But `qwe://foo^bar/baz`, which is not a "valid URL string" per the definition at https://url.spec.whatwg.org/#valid-url-string, does not trigger an error.

**Comment by annevk** [comment]
Yeah, this looks like a mess, thanks for pointing it out! There's also overlap between the sets of "URL code points" and "forbidden host code points" (e.g., "`:`" and "`?`"), which is problematic.

The fix here would be a stricter definition of valid opaque-host string, I'm pretty sure we don't want to alter the parser.

**Comment by domenic** [comment]
FWIW I think in general it is quite unlikely that the valid URL string definitions correspond precisely to the parse errors in the parser algorithm. There's no mechanism for enforcing that and it's too easy for them to get out of sync.

A to-do I've had for some time is to write an implementation that checks URLs via the parser and its parse error steps, a separate implementation that checks them via the valid URL string definitions, and then a fuzzer that generates tons of input in order to find where they differ.

**Comment by ExplodingCabbage** [comment]
@domenic Heh - I'd been thinking _precisely_ the same thing, and was considering taking it on just for the experience of writing a fuzzer, which I've never done before. No promises, though, so don't hold off on my account.

**Comment by annevk** [comment]
I have tried to tackle this in #494, but I would welcome the help of a fuzzer. 😊
