### ISSUE TITLE
"Otherwise, init is a string, then set ..." in list of steps for how to create a URLSearchParams object

### ISSUE THREAD

**Issue by amn** [whatwg/url#439]
In the [section 6.2](http://url.spec.whatwg.org/#interface-urlsearchparams), there is a list of steps an implementation must take as part of creating a `URLSearchParams` object. After defining some steps that apply depending on what kind of object `init` is, the 4th step is defined:

> 4. Otherwise, *init* is a string, then set *query*’s list to the result of parsing *init*.

How is one to interpret this sentence? Its first part seems... *assertive*, as opposed to being speculative, with regard to the type of object `init` is? Should there be an "if" between "Otherwise, " and "*init*"?

Or does the specification intentionally assert that if `init` isn't any kind of object as defined by earlier steps in the list, then it *is to be considered* a string (possibly co-ercing the value, which would support how Firefox and Chrome behave here) and the implementation is then to parse it?

Because there isn't otherwise any mention of coercion/cast of *init* to a string, or is this left up to implementations, by intent?

**Comment by annevk** [comment]
Due to the way IDL works, _init_ can only be a sequence, a record, or a string, as any necessary coercion will have already happened in the IDL layer.

I'd be open to reword this, e.g., to create a nested set of steps where the first is an assert and the second step is the set operation.

**Comment by GPHemsley** [comment]
I think even without the assertion, the `then` is problematic. My suggestion would be to change it to `so` or replace `, then` with `;`.
