### ISSUE TITLE
Implement URL.from helper

### ISSUE THREAD

**Issue by viktor-ku** [whatwg/url#443]
Hello, everyone!
 
I've implemented `URL.from` over in Node.js project ([PR](https://github.com/nodejs/node/pull/28482)), but we have a discussion there on to should we extend `URL` object or not. Good points are made for not doing so.

However, it feels like it would be convenient to have an option of creating a url object not only from string that should represent a url, but also from an object (or any other alternative according to any language) allowing builder pattern.Also it can be much faster than parsing the string.

I guess it would be a nice option in the browsers as well since making a url from an object-config is as common as making a url from string.

**Comment by annevk** [comment]
This is discussed in #354. Looking at your implementation, where does it perform input validation?

**Comment by viktor-ku** [comment]
@annevk input validation is an open question, but please note that input is not as complicated as I see in the #354. I would like to get focus on performance leaving most of the validation for the users. You should  *know* what you put there (also make writing 3rd party libraries easier). I'd like to do things like:

```js
const input = {}
// ...
input.protocol = 'https'
// ...
input.host = 'localhost'
// ...
input.query = querystring.stringify({ a: 1, b: 2 })
// ...
input.path = ['a', 'b']
// ...
input.path.pop()
// ...
const myURL = URL.from(input)
```

If you did mistake you should get punished - sure. But what to do with users that are using typescript and checking things before using them in libraries? Punish them with double checks hurting performance?

Anyway, if we can agree on the matter I am fine with strict checks (maybe with an option for `unsafe` for those who know what they are doing?).

I'd love to see it in Node.js.

**Comment by viktor-ku** [comment]
Move over to #354 to keep things together.

**Comment by annevk** [comment]
Currently if you're handed a URL object you can be assured it conforms to a set of rules. Allowing someone to create a URL object that bypasses those rules would result in a security issue.

**Comment by viktor-ku** [comment]
@annevk I understand that. But there will be a 3rd party library for doing such things which won't be controlled by the spec making this situation even worse. If spec defines strict rules on how to build a url from object then at least you can control it *and* you don't get 5 different ways of solving this exact problem after N years/months.

**Comment by annevk** [comment]
To some extent such a situation is good as we then get to "pick a winner" to standardize the ecosystem around. Otherwise we might end up designing something that nobody really wants to use at scale.
