### ISSUE TITLE
Url parser's buffer has wrong type appended to it

### ISSUE THREAD

**Issue by TRowbotham** [whatwg/url#451]
In the Path state, step 2.3 states:
> UTF-8 percent encode c using the path percent-encode set, and append the result to buffer. 

From what I can tell, buffer is a sequence of decoded code points. I don't think we can append percent encoded bytes to buffer, unless everything else is implicitly encoding everything that is being appended to buffer.

**Comment by annevk** [comment]
But https://url.spec.whatwg.org/#utf-8-percent-encode returns a string, no?

**Comment by TRowbotham** [comment]
Ah, yes, you're right. Sorry, following the the encode/decode dance sometimes trips me up when reading the spec. Thanks for the clarification.
