### ISSUE TITLE
application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by reschke** [whatwg/url#452]
Apparently this spec has taken over the definition of this media type.

If this is the case, please update the IANA registry (which still points to the HTML spec).

**Comment by annevk** [comment]
So the last time I went through the effort of emailing IANA to get something on a list it didn't work out (`Refresh` header) and it was quite a lot of work to figure out all the steps. What are my chances this time around?

**Comment by reschke** [comment]
AFAIU, the only thing that needs to be done is to update the documention link. Just send an email.

**Comment by annevk** [comment]
I tried filling out https://www.iana.org/form/media-types. I suspect we'll run into all kinds of issues though due to the change in controller/standards body.

> Your application has been sent to iana-mime@icann.org, and a copy of the application has been sent to your email account for your records.
>
> Your application has been added to the processing queue. Processing typically takes about one week.

**Comment by annevk** [comment]
Finally: https://www.iana.org/assignments/media-types/application/x-www-form-urlencoded.

I tried to correct the address for whatwg.org at https://www.iana.org/assignments/media-types/media-types.xhtml#WHATWG to be without www but did not succeed, but they did add an s to the scheme at least.

If only this could be done via a pull request.
