### ISSUE TITLE
Canonicalised IPv4 concept allows for obfuscating real dest IP in URL

### ISSUE THREAD

**Issue by wesinator** [whatwg/url#456]
**Example:** 
`http://10.0.514`
redirects to 
`http://10.0.2.2`
in Firefox and Chrome browsers 

(as you can see in my profile)

`http://0177.0.0.01` to `127.0.0.1`
![image](https://user-images.githubusercontent.com/5124946/67234510-4de63800-f413-11e9-830f-0d0bbba310c8.png)

**Issue:** This is a security risk (albeit low) because it allows the real destination IP host to be obfuscated in a URL. 

Firefox implementation - https://bugzilla.mozilla.org/show_bug.cgi?id=1288049

**Bringing up security considerations:**
https://bugzilla.mozilla.org/show_bug.cgi?id=1381139
https://bugzilla.mozilla.org/show_bug.cgi?id=67730 (related issue from 19 years ago, still open)

**p.s.** Also, what is the actual use case for this ? 
I'm not intimate with the WhatWG specs, but frankly, this seems really silly in general.

**Comment by annevk** [comment]
Some OS-level resolvers have this kind of behavior so it's better if the browser canonicalizes and makes the actual destination clear to the user than let that depend on the underlying network stack.

**Comment by wesinator** [comment]
> Some OS-level resolvers have this kind of behavior so it's better if the browser canonicalizes and makes the actual destination clear to the user than let that depend on the underlying network stack.

yes, but this means static URLs can obfuscate the actual destination. It only becomes clear when the request is made, which may not be visible to the user.

Also, I don't understand the translation from three digits to a four octet IPv4 
What is actually happening with `10.0.514` -> `10.0.2.2` ?

**Comment by valenting** [comment]
> yes, but this means static URLs can obfuscate the actual destination. It only becomes clear when the request is made, which may not be visible to the user.

A link that says [http://example.com](http://example.org) may take you to example.org instead. In the same way if you hover over or click this link [http://10.0.514](http://10.0.514) you'll see final canonicalized IP. So there is no confusion.

**Comment by sleevi** [comment]
> Also, I don't understand the translation from three digits to a four octet IPv4
> What is actually happening with `10.0.514` -> `10.0.2.2` ?

https://linux.die.net/man/3/inet_aton

**Comment by annevk** [comment]
And also described in a normative manner in the standard at https://url.spec.whatwg.org/#concept-ipv4-parser (note that validation error does not terminate the algorithm).

**Comment by wesinator** [comment]
> > yes, but this means static URLs can obfuscate the actual destination. It only becomes clear when the request is made, which may not be visible to the user.
> 
> A link that says [http://example.com](http://example.org) may take you to example.org instead. In the same way if you hover over or click this link http://10.0.514 you'll see final canonicalized IP. So there is no confusion.

Fair point.

Although that is not completely equivalent since the different domain link is done through the DOM, while the IP translation is done in the browser layer.
