### ISSUE TITLE
Bug in methods - entries() and forEach()

### ISSUE THREAD

**Issue by TilgalisToms** [whatwg/url#462]
Today encountered issue that methods entries() and forEach() are not working as expected.
JS Fiddle - https://jsfiddle.net/q70vhod4/1/
```
let link = 'http://demo.com?a=1&b=2&c=3';
let url = new URL(link);
url.searchParams.forEach(function(value, key, parent){
	parent.delete(key);
});
console.log(url.toString());

let link2 = "a=1&b=2&c=3";
let url2 = new URLSearchParams(link2);
for (let entry in url2.entries()) {
	console.log(entry[0] + ' : ' + entry[1]);
}
```

Tested on these browsers:
FireFox Developer Edition - 73.0b12
FireFox - 72.0.2
Chrome - 79.0.3945.130
Edge - 44.17763.831.0

**Comment by annevk** [comment]
Shouldn't you use `for x of y` with iterators? The first one also seems problematic as you're mutating a live collection.

**Comment by TilgalisToms** [comment]
> 
> 
> Shouldn't you use `for x of y` with iterators? The first one also seems problematic as you're mutating a live collection.

Actually the second one worked as You proposed. But about first one. Is that considered a  bad practice for emptying collection?

**Comment by annevk** [comment]
Yeah, first you delete the 0th item and then you delete the then-1st item (which is the 2nd item in the original list). That leaves the original 1st item, "b".

I recommend asking on https://stackoverflow.com/ first next time.
