### ISSUE TITLE
What should resolveRelativeUrl(base=..., relative="10.0.0.7:8080/foo.html") return?

### ISSUE THREAD

**Issue by anforowicz** [whatwg/url#464]
What should be the result of resolving a relative URL if:
- base url = `file:///some/dir/ip-relative.html`
- relative string = `10.0.0.7:8080/foo.html`

It seems that Firefox resolves this as `file:///some/dir/10.0.0.7:8080/foo.html`, but Chrome fails the resolution and returns an invalid URL, because it thinks that the `10.0.0.7` is a scheme and therefore the "relative string" represents an absolute URL.  FWIW, according to https://url.spec.whatwg.org/#scheme-state `10.0.0.7` does seem like a valid scheme.

This is a follow-up to https://crbug.com/530123

**Comment by TimothyGu** [comment]
See https://jsdom.github.io/whatwg-url/#url=MTAuMC4wLjc6ODA4MC9mb28uaHRtbA==&base=ZmlsZTovLy9zb21lL2Rpci9pcC1yZWxhdGl2ZS5odG1s. It appears that the Firefox behavior is correct per spec.

To see why this is, look instead at [scheme start state](https://url.spec.whatwg.org/#scheme-start-state). That state restricts all schemes to start with an ASCII letter, and only switches to scheme state after that is ascertained. See also the informative description of [URL-scheme string](https://url.spec.whatwg.org/#url-scheme-string).

**Comment by anforowicz** [comment]
Thank you very much @TimothyGu!  I did indeed miss that the earlier "scheme start state" only allows ASCII letters.  Let me resolve this issue - the spec explicitly covers this case / there is no spec bug here.

When fixing this issue in Chromium, I'll try to also add coverage to wpt/url/resources/urltestdata.json (and possibly to look into why other WPT tests in this file are failing).

**Comment by annevk** [comment]
Thanks for taking that on @anforowicz! I'd be happy to help if you need any assistance with review or some such and I suspect @domenic would be too.

**Comment by anforowicz** [comment]
Thanks @annevk!  FWIW, I've opened https://crbug.com/1058053 to track wpt/url failures in Chromium - feel free to star the bug and follow along.
