### ISSUE TITLE
Proposal of .toString({ concise: true }) for nicer output with empty values

### ISSUE THREAD

**Issue by mieszko4** [whatwg/url#469]
Consider the following example:
```js
const p = new URLSearchParams([['a', ''], ['b', 'non-empty', ['c', '']]);
p.toString();
```

It will output:
`a=&b=non-empty&c=`

I propose we introduce
```js
.toString({ concise: true });
```

That would output a pretty and concise query string without unnecessary `=`:
`a&b=non-empty&c`

Note that based on https://url.spec.whatwg.org/#urlencoded-parsing both outputs are semantically equalivent

**Comment by annevk** [comment]
We could consider changing the behavior here to be concise by default. That might well be web/Node.js-compatible and it does seem somewhat nicer.

**Comment by domenic** [comment]
I like the uniformity of equal signs everywhere. I don't see a need for adding this formatting nicety to the spec.

**Comment by jayaddison** [comment]
I'd like to record an argument in support of concise query-string values.

There is currently an [impedence mismatch](https://en.wikipedia.org/wiki/Object-relational_impedance_mismatch) between many applications that communicate using URIs and the programming languages and data stores that they use.

Most databases (relational and NoSQL) support the concept of NULL values, as do most programming languages.  We use `null` in C#, Java and JavaScript (distinct from `undefined`), `None` in Python and Rust, `nil` in GoLang, and so forth).

Most query-string serialization and deserialization _currently_ do not reliably distinguish between `?a=&b=1` and `?a&b=1` - there's ambiguity in the treatment of empty values vs empty strings.

To put this argument another way - it's less than ideal that both of the JavaScript objects `{"a": null}` and `{"a": ""}` -- which developers would generally agree have different behaviours and 'mean' different things -- have a tendency to collide into the same `?a=` representation when we put them into a URI.

Similarly, when an application receives and deserializes a query-string, it would be excellent if nulls and empty strings could be distinguished easily.  Storing empty strings in a database column can have unintended consequences when database developers are writing queries on those columns and/or are attempting to assess whether values are present.

There's an opportunity here to select a behaviour that will increase communication compatibility between systems over and reduce ambiguity over a long timescale.  Please balance that against other considerations including consistency, parsing complexity, and backwards compatibility.

Related issues:
- [jQuery bug 8653](https://bugs.jquery.com/ticket/8653#comment:3) (and related issue https://github.com/jquery/jquery/issues/4707 )
- [Python Issue 18857](https://bugs.python.org/issue18857) (and related PRs https://github.com/python/cpython/pull/19949, https://github.com/python/cpython/pull/19945)

**Comment by domenic** [comment]
I think if you're trying to encode non-string JS values (in your case it sounds like string-or-null-or-undefined) into the URL query params value space, you're going to need explicit buy-in from both the consumer and producer side to understand your serialization format.

**Comment by annevk** [comment]
@jayaddison wouldn't the most compatibility between systems naturally be attained by everyone aligning on https://url.spec.whatwg.org/#application/x-www-form-urlencoded?

**Comment by jayaddison** [comment]
> I think if you're trying to encode non-string JS values (in your case it sounds like string-or-null-or-undefined) ...

Given that `undefined`'s a relatively language-specific concept (in JavaScript and derived languages), whereas `null`-like values are present in most languages, I'm currently only suggesting null-or-string.

> ... you're going to need explicit buy-in from both the consumer and producer side to understand your serialization format.

That's a good argument in favour of making the change optional.  Essentially, if an application environment wants/needs to serialize the empty string and null as distinct values, then they could opt-in by setting `concise:true` (aka. `standaloneKeys:true` in the pull requests referenced).

**Comment by jayaddison** [comment]
> wouldn't the most compatibility between systems naturally be attained by everyone aligning on https://url.spec.whatwg.org/#application/x-www-form-urlencoded?

Thanks for the reference.  Under these encoding rules, it sounds like a name-value pair terminated by a `=` character (e.g. `a=`) and a standalone name (e.g. `a`) both parse to an empty byte sequence (e.g. empty string), according to the rules in section 5.1, steps 3.2 and 3.3.

That would raise a similar concern, making it challenging for developers and applications to unambiguously distinguish between null and empty string values during serialization and deserialization operations.

Although any decision made here could arguably *also* apply to `x-www-form-urlencoded`, perhaps it'd be easiest (in terms of minimizing fragmentation of discussion) to focus on one area of the standard to begin with, and then later discuss whether any changes should also apply elsewhere?

**Comment by annevk** [comment]
Well, `URLSearchParams` uses `x-www-form-urlencoded` underneath. They're not really separate. I was initially somewhat supportive, but now I'm more concerned as I would not want folks to write different parsers to be able to distinguish omitted from the empty string. That's just not a part of this format. I'd recommend omitting the name entirely to represent the null state.

**Comment by jayaddison** [comment]
@annevk Good point.  I'll admit I was uncertain whether to suggest keeping the conversations separate was a good idea - and now I share your concern, especially now that I'm looking into [rust-url](https://github.com/servo/rust-url/), where the implementation is (sensibly, as you mention) shared.

Omitting the name to represent null values is an interesting idea, but it means that the recipient / reader of the serialized query-string cannot know for certain which names the writer intended to be null.  If both reader and writer agree on the exact set of names -- and never update them -- then nulls can be implied from their absence, but if the writer introduces a new name, then readers who are unaware of the name would not pick up on that.

If and when I have a proposed Rust implementation I'll attach that here too.

**Comment by jayaddison** [comment]
This is potentially a bit of a ramble, but I'm trying to find ways to further explain and elaborate the ideas here.

Imagine that clients and servers communicate by passing boxes to each other.  The boxes are each labeled with a `name`, and inside each box can be found the `value` -- or nothing at all.

**Current state-of-the-world**
All boxes are made from cardboard.

When the server receives an empty cardboard box, they know that client considered that name to either be null, or to be the empty-string.

**Proposed changes**
The changes proposed here provide clients with a supply of glass boxes (nb: the glass is safe enough to be flung across the internet without damage).

When a conciseness-aware client wishes to indicate that they know about a name, and they consider it to be `null` -- have no value -- then they send the server an empty glass box labeled with that name.

A conciseness-aware server can see the client intentionally sent a glass box with no contents; they are aware that the client made this decision intentionally.

If a conciseness-aware client wishes to tell the server that a name has an empty-string value, then they pick a cardboard box instead, and they send it empty to the server.

Servers that are unaware of the meaning of a glass box will continue to do what they did previously - they'll open the box and inspect the contents and choose to interpret them in whatever way they usually do (perhaps frustration that they have been sent an empty box, and/or at least some comfort that someone was thinking about them).

In practical implementation terms, the client uses the presence of the `=` in a name-value pair to deliver a standard cardboard box, and the absence of `=` to deliver a transparent glass box.  The opt-in `concise` / `standaloneKeys` parameter controls whether the server is aware of the distinction.

**Comment by domenic** [comment]
Again, trying to hijack a formatting quirk to convey semantic meaning (like "glass or cardboard") is a misuse of the format. Consumer and producer need to agree on a domain-specific serialization of that information.

**Comment by jayaddison** [comment]
At some point, the base-10 decimal number `40` was elected as a standard value to represent the semantic notion of a single typed space character in ASCII, in a non-domain-specific fashion.

The concept of distinct `null` and empty-string values have, by this point, become domain-generic across most software languages.

That's a semantic distinction that'd be beneficial to apply -- regardless of the analogies used to explain the situation -- as long as it can be introduced in a safe and backwards-compatible fashion.

**Comment by jayaddison** [comment]
When you have time it'd be useful to hear further constructive criticism regarding the proposed changes @domenic - it's good to have your participation in the discussion.

**Comment by domenic** [comment]
I don't think I have much further to add. I think the proposal is a bad idea for the reasons I've already stated.

**Comment by annevk** [comment]
Yeah, I don't think we should change the parser and it seems that changing the serializer might encourage people to change the parser, so all in all it seems best to close this. This does not prevent clients and servers that can cooperate to do something else of course.

**Comment by mieszko4** [comment]
So to sum up, this proposal is closed because we want to discourage people to use a concise version of url, e.g. `a&b=non-empty&c` (although semantically correct and equivalent as per spec) and enforce them to always use e.g. `a=&b=non-empty&c=`?

I am asking because my proposal was just a non breaking extension and there is no alternative proposal.
I understand that changing spec to support distinction of "nullable" values may be tricky or undesirable
However, I am not clear why we want users to enforce using one url style only if the other style is semantically correct.

**Comment by annevk** [comment]
I think there are at least two reasons:

1. The aesthetic difference might give people the impression there is a meaningful difference.
2. We basically never offer aesthetic settings for serializers in the web platform. E.g., there's only one way to serialize markup.

**Comment by jayaddison** [comment]
Although this issue is resolved, for the record - related work-in-progress Rust implementation(s) (including `rust-url`) in case anyone would like to subscribe/investigate include:

- https://github.com/rustless/queryst/pull/14
- https://github.com/servo/rust-url/pull/547
- https://github.com/servo/rust-url/pull/591

**Comment by jayaddison** [comment]
NB: although this felt _extremely important_ for me to argue for earlier this year, my analogies and responses could've been more carefully chosen and I'm not sure they contributed effectively.  Apologies @mieszko4 in particular if they seemed to sidetrack useful discussion.

There's still value and improvement to be made in the query string format by changes like conciseness, IMO.

**Comment by verhovsky** [comment]
Distinguishing between `null` and `''` in `URLSearchParams` would allow losslessly converting arbitrary queryparam strings between `URLSearchParams` and back. This could matter if the resulting URL is hashed somewhere outside your control or if you care about correctness. The UR**I** RFC says that the query string can contain basically any characters:

          query       = *( pchar / "/" / "?" )

          pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
          unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"
          sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="

https://tools.ietf.org/html/rfc3986#section-3.4

**Comment by caub** [comment]
Regarding sub-delims, as pointed in comment above, since they don't require percent encoding (apart from `&` and `=` obviously), a search string like `x=foo:1,bar:2` is valid

So it'd be really good to have an option to not encode them, to make search params more user-friendly

I had to resort to do this:

```js
history.push(`${location.pathname}?${Object.entries({ ...query, ...q }).map(([k, v]) => `${k}=${v}`).join('&')}`); // new URLSearchParams() encodes , and : which is not necessary https://tools.ietf.org/html/rfc3986#appendix-A
```

**Comment by karlhorky** [comment]
For anyone looking for a userland solution for this, this is what we ended up with:

```ts
function setQueryParam(queryParamName: string, queryParamValue: number | undefined) {
  let queryString;

  const newSearchParams = new URLSearchParams(window.location.search);

  if (typeof queryParamValue === 'undefined') {
    newSearchParams.set(queryParamName, '');
    queryString = newSearchParams.toString().replace(
      new RegExp(`${queryParamName}=`),
      queryParamName,
    );
  } else {
    newSearchParams.set(queryParamName, String(queryParamValue));
    queryString = newSearchParams.toString();
  }

  const newUrl = `${window.location.origin}${window.location.pathname}?${queryString}`;

  return newUrl;
}
```

Usage:

```ts
setQueryParam('a', 'b'); // 'https://github.com/whatwg/url/issues/469?a=b'
setQueryParam('a', undefined); // 'https://github.com/whatwg/url/issues/469?a'
```
