### ISSUE TITLE
Creating a valid URL object and then changing the href to an invalid URL should not work 

### ISSUE THREAD

**Issue by aditya-giri** [whatwg/url#470]
When I create a URL object, this works:
`new URL("https://google.com")`
but this doesn't:
`new URL("google.com")`
because it throws a **TypeError** `Failed to construct URL: Invalid URL`
I presume this is because of the missing protocol.

But, if I create a URL object with a valid URL: `urlObj = new URL("https://google.com")`
And then modify the internal URL string: `urlObj.href = "abcd"`
It succeeds and I now have a URL object with a string that is definitely not a valid URL.

Is this by design, or can it be fixed?

**Comment by annevk** [comment]
Firefox throws in that case (as does the standard). I recommend filing a bug against the user agent.

**Comment by aditya-giri** [comment]
Oh, you're right. I'll do that, thanks!
