### ISSUE TITLE
IDNA hostnames end up using emdash instead of -- for ACE-encoded labels

### ISSUE THREAD

**Issue by sleevi** [whatwg/url#471]
https://url.spec.whatwg.org/commit-snapshots/0ce82da2b6734cdfa55652954ecc9dee9ed9b951/#example-host-psl

The public suffix renders as `xn-kgbechtv` when it should be `xn--kgbechtv`

**Comment by annevk** [comment]
This happened in #391 and nobody noticed at the time.

**Comment by annevk** [comment]
See #472.
