### ISSUE TITLE
Path setter jumps off the leading edge of input

### ISSUE THREAD

**Issue by alercah** [whatwg/url#480]
When the path setter is called, the basic parser is overridden to the *path start state*. But per either 1.3 or 4.2 for that state, the pointer can be decremented:

> If c is neither U+002F (/) nor U+005C (\), then decrease pointer by one.

> If c is not U+002F (/), then decrease pointer by one.

This is ill-defined when the pointer is to the start of the input.

**Comment by annevk** [comment]
Thanks, this seems very similar to #373. You'll get the correct result if you allow the pointer to go negative, but it's very weird.
