### ISSUE TITLE
web-platform-tests expect null in hostname getter

### ISSUE THREAD

**Issue by Sebmaster** [whatwg/url#49]
Seems like either the tests are wrong again, or the spec is:

The hostname getter can't return null (always returns empty string), but the tests expect it to return null.

**Comment by annevk** [comment]
What kind of wrapper do you use for the tests? https://github.com/w3c/web-platform-tests/blob/master/url/urltestparser.js normalizes the expected null result for the hostname getter. You might have missed that change?

**Comment by Sebmaster** [comment]
Woops, sorry, that was my fault too, I was comparing `myHostname` with `yourHost`. Comparing both hostnames seems to match.

However, when comparing `host`, this problem persists. Spec says to also return empty string on null, however `urltestparser.js` doesn't normalize it the same way.

**Comment by annevk** [comment]
Yeah, but the test files are not testing host. If they need to you're right, but that should just change in the harness then. From a specification perspective the internal host can be null, and that's all that's represented here.

**Comment by Sebmaster** [comment]
Oh, I see. If the internal host prop isn't meant to be tested then that's fine.

Thanks.
