### ISSUE TITLE
IPv4 number parser doesn't handle zeros well

### ISSUE THREAD

**Issue by Sebmaster** [whatwg/url#50]
If the [IPv4 number parser](https://url.spec.whatwg.org/#ipv4-number-parser) is given just a `"0"` (like when parsing the IP 127.0.0.1):

1. Set `R` to 10
2. `input` has at least 1 code point, so: remove 1 code point from `input`, set `R` to 8

`input` is now empty, so number parsing `input` later on should lead to an error since there's no number to parse.

I quickfixed with https://github.com/jsdom/whatwg-url/commit/590d1fa4fd9e4270c3fd8f8cdb08d7f94a65eb31, by just re-interpreting "at least" to mean "greater than" :stuck_out_tongue_closed_eyes:

**Comment by Sebmaster** [comment]
How does this handle (invalid) URLs? For example: 127.0x.0.1?

Seems like parsing the number would error out again, should that just implicitly bubble the error?

**Comment by annevk** [comment]
Hmm you're right. It seems '0x' should be treated as 0 too.

If I add a step after 2 that says to return 0 if input is the empty string, am I still missing something?

**Comment by Sebmaster** [comment]
No, I think that'd just work.

Interesting that browsers interpret 0x as just 0, I'd have thrown an error. Although I guess it's good for compatibility.
