### ISSUE TITLE
Serialization of file URLs is wrong

### ISSUE THREAD

**Issue by domenic** [whatwg/url#52]
https://url.spec.whatwg.org/#concept-url-serializer serializes file URLs as `file:<path>`, e.g. `file:/foo/bar`. They should be serialized as `file:///foo/bar`.

Related: https://github.com/jsdom/whatwg-url/issues/22 https://github.com/w3c/web-platform-tests/issues/2038

**Comment by domenic** [comment]
The patch that gives the expected results is

```js
  if (url.scheme === "file" && url.host === null) {
    output += "//";
  }
```

after the current step 2 of https://url.spec.whatwg.org/#concept-url-serializer

**Comment by domenic** [comment]
Note: browser are inconsistent on the *parsing* of file URLs. Some parse `file:/foo/bar` as having `foo` as the host.

However, the spec does not (it puts `foo` in the path, making the path `/foo/bar`).

*And*, all implementations agree that file URLs with no host should be serialized with three slashes.

**Comment by annevk** [comment]
Thanks, I totally neglected file URLs when adding support for everything-can-be-a-relative-URL-scheme. Hopefully soon there is some time to fix the remaining file URL issues.

**Comment by annevk** [comment]
This should be fixed now.
