### ISSUE TITLE
Does URLSearchParams.prototype.keys() return an Iterator or IterableIterator?

### ISSUE THREAD

**Issue by felixfbecker** [whatwg/url#521]
I tried to answer this by looking at the spec, which just says `URLSearchParams` itself is iterable: https://url.spec.whatwg.org/#interface-urlsearchparams

I then looked at [the definition `iterable` in the IDL spec](https://heycam.github.io/webidl/#idl-iterable), but it's still not clear to me  whether the return value of `keys()` itself is iterable.

I also checked the [webplatform tests](https://github.com/web-platform-tests/wpt/tree/master/url) and couldn't find any test for this.

I noticed that Chrome and Safari return an iterable, meaning you can do this:
```ts
const params = new URLSearchParams('?foo=bar')
for (const param of params.keys()) {
  console.log(param)
}
```
The same code in Firefox (77.0b6) throws a `TypeError: searchParams.keys() is not iterable`, so this is a web compat issue, but I don't know who is behaving correctly here.

As a consumer I have a use case for iterating `keys()` with `for of` so I'd prefer it to be iterable, and `Map`, `Set`, `Array` etc all behave this way.

**Comment by TimothyGu** [comment]
The prototype of the returned iterator object is the [iterator prototype object](https://heycam.github.io/webidl/#dfn-iterator-prototype-object) of the interface, which has as prototype [%IteratorPrototype%](https://tc39.github.io/ecma262/#sec-%iteratorprototype%-object) defined in ECMAScript. There, you'll find that %IteratorPrototype% has a single method defined: `@@iterator`. So the result of `keys()` should indeed be iterable.

The code you posted works in Firefox for me here (76.0.1):
![image](https://user-images.githubusercontent.com/1538624/82282427-cb4e3880-9961-11ea-8cc9-55d5d4332517.png)

In any case, any issue would be an implementation one as the spec is clear.
