### ISSUE TITLE
What should `new URL("#")` return?

### ISSUE THREAD

**Issue by azu** [whatwg/url#539]
What should be the result of `new URL("#")`?
Browsers return different results.

In my understanding is that `new URL("#")` should throw a validation error.

1. [scheme start state](https://url.spec.whatwg.org/#scheme-start-state) 
    1. [skip] If c is an ASCII alpha, append c, lowercased, to buffer, and set state to scheme state. 
    2. [match] Otherwise, if state override is not given, set state to no scheme state and decrease pointer by 1. → go to [no schema state](https://url.spec.whatwg.org/#no-scheme-state)
2.  [no schema state](https://url.spec.whatwg.org/#no-scheme-state)
    1. [match] If base is null, or base’s cannot-be-a-base-URL flag is set and c is not U+0023 (#), validation error, return failure. → throw validation error

```js
if ( base === null || (cannot-be-a-base-URL && c !== "#")){
  throw validation error
}
```

state value

- `base` is `null` (initial value)
- cannot-be-a-base-URL flag is not set
- `c` is `#`

---

Test results:

- Firefox 80.0 → throw TypeError: URL constructor: # is not a valid URL.
- Chrome 85 → return `URL {href: "about:blank#", origin: "null", protocol: "about:", username: "", password: "", …}`
- Safari 13.1.2 → return `URL {href: "about:blank#", origin: "null", protocol: "about:", username: "", password: "", …}`
- Node.js 14.5 → throw TypeError [ERR_INVALID_URL]: Invalid URL: #
- [whatwg-url](https://github.com/jsdom/whatwg-url) → throw Error 

I can not found this test in [wpt/url](https://github.com/web-platform-tests/wpt/tree/master/url).

📝 Memo: 
I've noticed this different result when comparing `aTag.href` with `URL` object.
Some `<a>` element starts with fragment like `<a href="#fragment">` and `new URL(a.href)` got different results.
However, `new URL(a.href, location.href)` is not problem.

**Comment by annevk** [comment]
We should add a test for this. Chrome and Safari are wrong, but they might have matched an earlier version of the standard that mistakenly used about:blank as the default base URL: c2980ee398de9621b0c313e5cc522895227db24c. Although that would not explain `new URL("?")` throwing and `new URL("about:blank?")` not throwing, so they are probably just buggy.

**Comment by azu** [comment]
Thanks to confirm!

**Comment by annevk** [comment]
To close this issue two things will need to be done that are relatively straightforward:

1. New tests will need to be contributed to web-platform-tests (see README) for parsing `#` without base URL.
2. Bugs will need to be filed against Chrome and Safari (see https://github.com/whatwg/meta/blob/master/MAINTAINERS.md#handling-pull-requests for where exactly) for getting not throwing a TypeError as expected.

**Comment by achristensen07** [comment]
https://bugs.webkit.org/show_bug.cgi?id=216115

**Comment by domenic** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1227126
