### ISSUE TITLE
Changes in the base are not reflected often enough

### ISSUE THREAD

**Issue by domenic** [whatwg/url#54]
I may have missed a crucial spec, but I cannot find any part of either the HTML or URL standards that explains the behavior [shown in this jsbin](https://jsbin.com/yagadu/4/edit?html,console,output):

```
console.log(document.querySelector("a").href); // http://example.com/foo.html
document.querySelector("base").href = "http://otherexample.org";
console.log(document.querySelector("a").href); // http://otherexample.org/foo.html
```

HTML's [set the frozen base URL](https://html.spec.whatwg.org/multipage/semantics.html#set-the-frozen-base-url) does not update `a` elements (or other URLUtils instances).

URL's [href getter](https://url.spec.whatwg.org/#dom-urlutils-href) (and other getters) just returns the input, without first doing set the input or any other type of reparse.

So as far as I can tell from reading the specs, updating a `<base>` element (or otherwise updating the document's base URL, if it's possible to do so) will not update URLUtils instances. But browers definitely do this, at least for `<a>`.

I'm unsure where the appropriate fix is. In particular HTML could certainly update all the `<a>`s, but could it properly update all the URLUtils in play? Either URLUtils needs some way of not only getting the base, but knowing when it is changed (in which case all the base-setters need to push such a notification to all relevant URLUtils); or, URLUtils needs to re-consult get-the-base before every getter invocation. I think.

**Comment by annevk** [comment]
This would be an issue with HTML, not URL.

https://html.spec.whatwg.org/multipage/infrastructure.html#dynamic-changes-to-base-urls has some of this, but some of that is wrong too, now xml:base is being removed. Also, I don't think DOM specifies any hooks yet.

**Comment by domenic** [comment]
Dang, I missed that section. I wish it were cross-referenced from other related ones. Thanks.

HTML says that DOM defines

> The concept of base URL change steps and the definition of what happens when an element is affected by a base URL change

so I guess those are the missing hooks. Otherwise everything seems fine on the HTML side. I guess this should be a bug against DOM?

**Comment by annevk** [comment]
HTML only says to change it when it affects display. `href` does not affect display so it has an issue. https://www.w3.org/Bugs/Public/show_bug.cgi?id=20976 is the DOM bug for specifying the new reality for base URLs (where `xml:base` doesn't exist anymore).

**Comment by annevk** [comment]
https://github.com/whatwg/dom/issues/61 is now for specifying the base URL change notification system.

**Comment by annevk** [comment]
Per https://github.com/whatwg/dom/issues/61#issuecomment-127624917 we need to make changes to URL after all. URL getters need to grab the latest base URL and use that to parse the input (again).

**Comment by annevk** [comment]
Still need to address any actions on `URLSearchParams` associated with a URL as those also need to be aware of base URL changes.

**Comment by annevk** [comment]
Thank you!
