### ISSUE TITLE
Is userinfo in URL deprecated?

### ISSUE THREAD

**Issue by aameen951** [whatwg/url#540]
Sorry if this question is already answered, I searched in the standard and I could find the answer.

In the [`authority state`](https://url.spec.whatwg.org/#authority-state) it says the following:
```
1. If c is U+0040 (@), then:

    1. Validation error.
    ...
```
Why does the `@` symbol in `authority` produce a validation error? Since it is not a failure, the only interpretation I can think of is that it is deprecated. But I did not find in the standard anything that says it's deprecated.

Am I correct?

**Comment by annevk** [comment]
That is correct, the rules for writing URLs do not include it either: https://url.spec.whatwg.org/#url-writing.

**Comment by aameen951** [comment]
Thanks you.
