### ISSUE TITLE
URLSearchParams.sort appends equal sign to params inside search property

### ISSUE THREAD

**Issue by muuvmuuv** [whatwg/url#541]
Turning `http://example.com/?b&a` into an url and sorting its search params append an equal sign to every param in the search property. So `url.search` with `?a` becomes `?a=`.

According to [the spec](https://url.spec.whatwg.org/#concept-urlencoded-serializer) this is by design but I wonder if we could this optional?

Repl: https://repl.it/@muuvmuuv/issue-url-searchparams

Related to: https://github.com/sindresorhus/normalize-url/issues/112

**Comment by annevk** [comment]
See the discussion in #469 and in particular https://github.com/whatwg/url/issues/469#issuecomment-627773030.
