### ISSUE TITLE
origin tuple doesn't serialize host

### ISSUE THREAD

**Issue by Sebmaster** [whatwg/url#55]
While retrieving the origin with the attribute getter, no step in the specification(s) says to serialize the host (as it does when executing the host attribute getter). I think that should actually be specified in the [origin section](https://url.spec.whatwg.org/#concept-url-origin).

This leads to the domain-to-unicode algorithm receiving an IPv4 address directly as a 32bit identifier (which doesn't handle that case either).

**Comment by annevk** [comment]
Origin serialization is defined in HTML, no?

**Comment by Sebmaster** [comment]
Yes, but it applies the unicode serialization directly to the host, without converting it to a string first. I'm guessing they define host as string only, but I can't find an exact definition in the HTML spec for it.

**Comment by annevk** [comment]
Ah right. So there's a bug in HTML. Should be easy to fix soonish.

**Comment by domenic** [comment]
Are you sure this is a HTML bug? From what I understand jsdom/whatwg-url implemented the URL spec exactly (without involving any of HTML) and ran into this issue. You can see the proposed fix at https://github.com/jsdom/whatwg-url/commit/3ebac9c3001d098ed276be011e030b49b97257fc

**Comment by Sebmaster** [comment]
@domenic origin serialization is defined in the HTML spec. whatwg-url implements the algorithm from over there.

**Comment by domenic** [comment]
Oh, I see. Maybe whatwg-url should include a comment ;)

**Comment by annevk** [comment]
Thank you @Sebmaster for reporting this. I filed https://www.w3.org/Bugs/Public/show_bug.cgi?id=29056 on the HTML Standard. Earlier I also filed https://www.w3.org/Bugs/Public/show_bug.cgi?id=28788 against the HTML Standard on this subject.

(I briefly considered defining origin serialization as part of the URL Standard since it's mostly URL concepts, but decided against it.)
