### ISSUE TITLE
Add details to host and path setters

### ISSUE THREAD

**Issue by achristensen07** [whatwg/url#551]
When setting host (or hostname), remove everything after '/', '?', and '#' in all schemes and '\' in special URL schemes.  This matches the behavior of Firefox and WebKit after https://bugs.webkit.org/show_bug.cgi?id=217366 and is already expected by web platform tests.

When setting path, remove the first '/' and in special schemes also remove the first '\'.  This matches the behavior of Chrome and WebKit after https://bugs.webkit.org/show_bug.cgi?id=217366 and is already expected by web platform tests.

**Comment by annevk** [comment]
Can you explain how this is not already mandated? An example that shows where the specification goes wrong would help.

**Comment by achristensen07** [comment]
Maybe this is a case of me reading too late at night, but now it seems obvious. This issue is invalid.
