### ISSUE TITLE
When to generate unique identifiers?

### ISSUE THREAD

**Issue by SimonSapin** [whatwg/url#56]
In some cases, https://url.spec.whatwg.org/#origin says to "return a new globally unique identifier". The "new" part seems to indicate that a different identifier should be returned every time the origin of a given URL is obtained. As a result, some URLs are not [same-origin](https://html.spec.whatwg.org/multipage/browsers.html#same-origin) as themselves, which seem undesirable.

Should unique identifiers be generated when an URL is "instantiated" instead? (That concept would need to be properly defined.)

**Comment by masinter** [comment]
That origin is a function of the URL is a fiction just for this reason. "Origin" should be an attribute of content (like content-type) and an output of Fetch.

**Comment by annevk** [comment]
@SimonSapin actually, not being same-origin to themselves is exactly the semantics we want to properly handle data URLs and such.

**Comment by SimonSapin** [comment]
@annevk Perhaps this is worth an note in the spec, then?

**Comment by annevk** [comment]
What would you like it to say? "Note: This does indeed mean that these URLs cannot be same-origin with themselves."

**Comment by SimonSapin** [comment]
Yes, noting that this is intentional would be useful. When first reading this I assumed it was an oversight.

**Comment by annevk** [comment]
@masinter to be clear, we often need the origin of a URL for various upfront security checks and while handling redirects, etc.

**Comment by masinter** [comment]
this is an old issue

http://www.ietf.org/mail-archive/web/websec/current/msg00859.html
