### ISSUE TITLE
Clarify handling of \0\r\n\t

### ISSUE THREAD

**Issue by valenting** [whatwg/url#57]
The presence of certain characters (\r\n\t) is not specified for some of the setters. It's a similar case for \0.
As noted in https://bugzilla.mozilla.org/show_bug.cgi?id=1190027#c0 the handling of these characters by UAs varies greatly.
Clarifying the handling of these characters in a consistent way would be preferable.

**Comment by annevk** [comment]
Thank for reporting this, but having analyzed the behavior I think browsers are just buggy here. The specification is much more consistent here and it would be preferable if implementations aligned. I commented on the bug with details.
