### ISSUE TITLE
Valid IPv4 address string

### ISSUE THREAD

**Issue by alwinb** [whatwg/url#583]
There is a minor issue with the definition of a **valid IPv4-address string** in the [Host Writing][1] section. 

> A **valid IPv4-address string** must be four sequences of up to three ASCII digits per sequence, each representing a decimal number no greater than 255, and separated from each other by U+002E (.).

From this is is not clear if e.g. `127.0.0.001` is a valid IPv4-address string.
The parsing section suggests that it is not; the [IPv4 number parser][2] records a validationError for e.g. `001` in Step 4. 

[1]: https://url.spec.whatwg.org/#valid-ipv4-address-string
[2]: https://url.spec.whatwg.org/#ipv4-number-parser

**Comment by annevk** [comment]
Thanks! We should exclude leading 0s there. Are you interested in fixing this?

**Comment by alwinb** [comment]
I wouldn't mind, but maybe I can leave it for later? I'm working on some tests for the encode sets (hopefully done today), and there are some other issues that I'd like to address first.

**Comment by annevk** [comment]
Of course!
