### ISSUE TITLE
Add a note that `searchParams` is not unicode-aware

### ISSUE THREAD

**Issue by karwa** [whatwg/url#596]
For example, in the URL:

```
http://example.com?ab\u006E\u0303cd=123
```

The key of the first query parameter is the string "abñcd", where the "ñ" is written as U+006E (LATIN LOWERCASE N) followed by U+0303 (COMBINING TILDE). If you search for exactly those unicode code-points, you will find the value:

```
> url.searchParams.get("ab\u006E\u0303cd")
"123"
```

However, if you search for the canonically-equivalent U+00F1 (LATIN SMALL LETTER N WITH TILDE), you won't find anything:

```
> url.searchParams.get("ab\u00F1cd")
null
```

This means that the sender and receiver of the request need to co-ordinate about how they normalise their unicode code-points before interacting with the URL APIs, otherwise they may get surprising results on platforms whose native string types do unicode-aware comparison by default: `searchParams.get()` will say that no key matching "ab\u00F1cd" exists, but if they iterate all key-value pairs and check manually using the platform's native string type, there will indeed be a matching key.

Would an editorial note be welcome? If so, I'd be happy to add one.

Alternatively, we could canonicalise the keys and values when constructing the `searchParams`, and also the key given to the `get` function, to make the APIs unicode-aware.

**Comment by TimothyGu** [comment]
At least in JavaScript, this type of behavior is pretty standard and expected, so I think we can do without a note. If you are adapting the JavaScript URL API to other platforms/languages, whose idiomatic/customary behavior is inconsistent with JavaScript, the choice is yours to either follow convention or stick with JavaScript, or provide both types of APIs. In either case, I'd encourage you to document the limitations clearly.

**Comment by karwa** [comment]
@TimothyGu Hmm OK.

That is actually what I'm doing for Swift - offering both the JS model defined in the standard and one which I think better suits the expectations of Swift developers (for instance, the setters in the JS model allow extra data which gets silently dropped, filters tabs and newlines, etc. It's rare that strings in Swift contain extra content that is not deliberate, so that behaviour is only exposed via the JS model).

I am a bit worried about possibly having too much divergence; URLs are complex enough, and having every URL library invent new behaviours will increase the cognitive burden for developers, open the door for bugs when the differences are subtle (like this), and generally is not good for developers wanting to write portable code or compose a system from components written in multiple languages. I agree that documentation is vital (I actually noticed this issue while improving the docs, wondering what it means for a key to "match").

There are broader issues with this, anyway. I recently helped a developer who was frustrated that requests to a Hungarian dictionary website wouldn't recognise the word encoded in his URL's query (in the _value_ part of a key-value pair), and thought the language/library was to blame. As it turns out, the website wasn't NFC-normalising the string before looking it up in its database - so this isn't limited to keys, or even to URLs. I suppose in a perfect world, everything from your URL libraries to your databases would use Unicode-aware comparisons across the board. Maybe one day...

**Comment by annevk** [comment]
I think the other thing is that ultimately URLs only contain ASCII or if you decode percent-encoding a byte sequence. Sometimes that can decoded as UTF-8, but it really depends on the recipient what they want to do with it. They might want to treat it as a byte sequence for some reason.
