### ISSUE TITLE
Use different percent-encode sets for simple/non-simple scheme fragment encoding

### ISSUE THREAD

**Issue by achristensen07** [whatwg/url#597]
This is similar to issue #348

I've noticed some odd things about fragment encoding in different browsers.  All browsers agree `new URL("http://example.com/# <>")` should parse to `http://example.com/#%20%3C%3E ` but no two browsers agree on what `new URL("data://example.com/# <>")`

In Firefox 88 it becomes `data://example.com/#%20<>`
In Chrome 90 it becomes `data://example.com/# <>`
In Safari 14.1 it becomes `data://example.com/#%20%3C%3E`

Safari's adoption of the behavior of the current specification caused at least one compatibility issue in https://bugs.webkit.org/show_bug.cgi?id=225340 and we are now convinced that we need a different set of characters to be encoded in special and non-special URL fragments, depending on the scheme.  Once my bug is fixed in WebKit all browsers will have different encode sets for special and non-special URL fragments so the specification should reflect this reality.

I propose we use `fragment percent-encode set` if url is special, otherwise the `C0 control percent-encode set` in https://url.spec.whatwg.org/#fragment-state step 1.3.

**Comment by annevk** [comment]
The example in that bug also seems to fail in Firefox though?

And per https://fetch.spec.whatwg.org/#data-urls you don't include the fragment part of a `data:` URL when processing the body.

cc @valenting

**Comment by TimothyGu** [comment]
I tested some other non-browser URL parsers and here's what I found:

* Node.js's [legacy URL parser](https://nodejs.org/docs/latest-v16.x/api/url.html#url_legacy_url_api) follows the current spec
* Ruby's [URI](https://ruby-doc.org/stdlib-2.7.2/libdoc/uri/rdoc/URI.html) follows the current spec; in fact it doesn't even parse `# <>` or `#%20<>`
* Go's [net/url](https://golang.org/pkg/net/url/) follows the current spec
* curl's [URL API](https://everything.curl.dev/libcurl/url) always encodes the space in the fragment, but leaves `<>` or `%3C%3E` in the original encoding untouched (exactly same as Firefox)

Notably, none of these parsers distinguish between special and non-special schemes.

Here's the relevant places in Firefox and Chrome that encode the fragment (I think):

- Firefox: https://searchfox.org/mozilla-central/rev/6371054f6260a5f8844846439297547f7cfeeedd/netwerk/base/nsSimpleURI.cpp#444-445
- Chrome: https://source.chromium.org/chromium/chromium/src/+/main:url/url_canon_pathurl.cc;l=65-75;drc=b0dcfd9b5f7d30aaa9b4789e4b4bb15750eca264

**Comment by TimothyGu** [comment]
Regarding the original issue of https://bugs.webkit.org/show_bug.cgi?id=225340, it doesn't look like a web compat issue to me. The author seemed to want to report a "deviation from the previous version of Safari" in their own application, rather than some established website that stopped working due to that change

On the other hand, the notion that some URLs canonicalized by Firefox and Chrome don't even parse with an established piece of software (Ruby) is alarming.

Given all this, I'm a fan of keeping the spec the way it is and try to get implementations to change. But failing to align all three browsers, I think Chrome should at least start escaping spaces. There is no indication that the current Chrome behavior around non-special fragments is intentional: it was introduced in https://codereview.chromium.org/23835019 / https://crbug.com/291747, which first started separating out fragments for non-special URLs.

**Comment by valenting** [comment]
> The example in that bug also seems to fail in Firefox though?
> And per https://fetch.spec.whatwg.org/#data-urls you don't include the fragment part of a `data:` URL when processing the body.

We ignore the ref when processing the data URL in a channel [[ref]](https://searchfox.org/mozilla-central/rev/6371054f6260a5f8844846439297547f7cfeeedd/netwerk/protocol/data/nsDataHandler.cpp#249-253)

**Comment by achristensen07** [comment]
This isn't just about data URLs; the same applies to `asdf://example.com/# <>`
If other browsers are willing to actually make changes then I'm ok with keeping the spec as it is.  I'll keep an eye out for any more compatibility problems.  I'll admit my example wasn't the best since it is also broken in Firefox, but the fact that old Safari and Chrome used to support it made me think it was worth considering changing the spec.

**Comment by masinter** [comment]
Besides,
data://example.com/
isn't a valid data: URL.

**Comment by TimothyGu** [comment]
I'm going to try to change the Chrome behavior to align with Safari's in https://crbug.com/1208104.

**Comment by achristensen07** [comment]
I think the consensus was to not change the spec here.  I'll let you know if I find anything else
