### ISSUE TITLE
Double-encoded IDNA labels don't roundtrip

### ISSUE THREAD

**Issue by TimothyGu** [whatwg/url#603]
Consider `xn--xn---epa`. It appears that using the current **domain to Unicode** algorithm (as implemented by Node.js), this would get converted to `xn--é`. But applying **domain to ASCII** on `xn--é` would produce a Punycode decoding failure. It sounds like domain to Unicode (or even UTS 46) should return failure on such labels.

This is somewhat important because Firefox can create such double-encoded labels:

```js
» new URL('http://xn--é').hostname
❮ "xn--xn---epa"
```

**Comment by rmisev** [comment]
I think double-encoded labels must be considered invalid. I see two ways to achieve this:
1. Set *CheckHyphens* to true
2. Or modify [UTS 46 validity criteria](https://www.unicode.org/reports/tr46/#Validity_Criteria): add following criteria (suppose after 3):
   "If *CheckHyphens* = false, the label must not begin with `xn--`"

**Comment by sleevi** [comment]
Setting `CheckHyphens` to true sounds like a good solution if we're saying "hosts are DNS" (#397 ). RFC 5890 sets aside the Reserved LDH labels, which not only includes `xn--`, but all DNS labels with `--` in the third/fourth characters.

Note that this would also seem to impact #438 depending on where things land.

**Comment by TimothyGu** [comment]
@rmisev Indeed! As evident in UTS 46, the _CheckHyphens_ boolean was first introduced to allow YouTube labels of form "r3---sn-apo3qvuoxuxbt-j5pe". (Previously it was always "true".) But I suppose the Unicode folks didn't consider the possibility of `xn--`, which now needs to be forbidden explicitly.

**Comment by dnsguru** [comment]
Domains (in GTLD) are generally restricted from dashes in the 3rd and 4th
positions /^[A-z0-9][A-z0-9]--/ if this helps.  IDNA takes advantage of
this and was the catalyst.

**Comment by annevk** [comment]
@macchiati not sure what we should do here, but wanted to bring this to your attention.

**Comment by valenting** [comment]
> This is somewhat important because Firefox can create such double-encoded labels:
> 
> ```js
> » new URL('http://xn--é').hostname
> ❮ "xn--xn---epa"
> ```

That is no longer the case. Firefox now throws for `new URL('http://xn--é')`

**Comment by annevk** [comment]
@valenting does that follow from the specification in any way though?

**Comment by macchiati** [comment]
From the bug report, it looks like this was just not following the spec

**Comment by annevk** [comment]
I think @macchiati is correct.

1. https://www.unicode.org/reports/tr46/#ToASCII is where we start as that is what the URL Standard invokes.
2. https://www.unicode.org/reports/tr46/#Processing is what gets invoked first.
3. Step 4 there is the interesting one. In our case the input starts with `xn--`.
4. So we enter https://www.rfc-editor.org/rfc/rfc3492.html#section-6.2. Pseudo-code, great.
5. The fifth step there reads as follows:
   > consume all code points before the last delimiter (if there is one)
     and copy them to output, fail on any non-basic code point
6. Now https://www.rfc-editor.org/rfc/rfc3492.html#section-5 explains what "basic" means here (not the greatest of terms), which suggests that `é` leads to an error here.
7. Now we go back and read https://www.unicode.org/reports/tr46/#ToASCII again and notice:
   > If an error was recorded in steps 1-4, then the operation has failed and a failure value is returned. No DNS lookup should be done.

We should add a WPT for this, but I think this case is adequately covered by the specification and CheckHyphens doesn't impact it one way or another.

**Comment by annevk** [comment]
There is test coverage for this already in `resources/toascii.json`:
```json
  {
    "comment": "Invalid Punycode (contains non-ASCII character)",
    "input": "xn--tešla",
    "output": null
  }
```
Per https://wpt.fyi/results/url/toascii.window.html Chromium-based browsers have some issues there for `<a>` and `<area>`, but otherwise things seem to be in order.

Closing this therefore, but please comment if my analysis was lacking somehow.

**Comment by annevk** [comment]
I'd prefer a new issue. Both of those result in failure in WebKit so I'd appreciate it if you could go through the steps as I did in https://github.com/whatwg/url/issues/603#issuecomment-1377190876 to find out if this is an actual bug in the specification or if we should add these as tests.
