### ISSUE TITLE
Should protocol setter remove tabs and newline?

### ISSUE THREAD

**Issue by TimothyGu** [whatwg/url#609]
Consider the following test:

```js
u = new URL("https://github.com/whatwg/url/issues/new");
u.protocol = "ht\ntp";
u.href
```

On Chrome, Firefox, and Safari, `u.href` retains the original `https` protocol. This behavior as it relates to the Location object is in fact tested by WPT(!): search for `\x0A` in [html/browsers/history/the-location-interface/location-protocol-setter.html](https://github.com/web-platform-tests/wpt/blob/master/html/browsers/history/the-location-interface/location-protocol-setter.html#L48).

**Comment by domenic** [comment]
I don't have a strong feeling here, but I lean toward keeping protocol consistent with all other invocations of the URL parser and getting all browsers to update. It seems pretty gross to have a special carve-out for one particular state override.

On the other hand, when all three browsers do something, probably the spec should be updated to match it, even if that thing is really weird.

I'm curious what @achristensen07 thinks...

**Comment by achristensen07** [comment]
Given that all browsers agree on behavior, I think we should change the spec to match behavior in this case

**Comment by achristensen07** [comment]
I guess I don't have a strong opinion here.  I don't think there will be a lot of compatibility issues if we change this.

**Comment by achristensen07** [comment]
Should we at least update the tests to be consistent with the current specs?  I also found that http://wpt.live/html/browsers/history/the-location-interface/location-protocol-setter-non-broken-weird.html and http://wpt.live/url/url-setters-a-area.window.html also contradict each other.

**Comment by domenic** [comment]
Yeah, we should definitely update the tests to be self-consistent, and probably it's best to align them with the current spec. (Unless we want to update the spec, which I think everyone is OK with, but nobody is insisting on...)

**Comment by annevk** [comment]
#61 added the tests in OP, but #101 was fixed before that and somehow not taken into account. So it seem this was an oversight.

I don't think there is an inconsistency between the tests @achristensen07 points towards. There are different requirements for `Location`'s `protocol` setter after all. In particular, the resulting scheme has to be an HTTP(S) scheme as nothing else really gives sensible results there.

I created https://github.com/web-platform-tests/wpt/pull/38032 to update the incorrect tests and add some missing scenarios. Suggestions welcome.

Once those are reviewed I'll file implementation bugs and then we can close this issue in my opinion.

**Comment by annevk** [comment]
Bugs:

* https://bugs.webkit.org/show_bug.cgi?id=251087
* https://bugzilla.mozilla.org/show_bug.cgi?id=1812060
* https://bugs.chromium.org/p/chromium/issues/detail?id=1409867
* https://github.com/denoland/deno/issues/17513
* https://github.com/nodejs/node/issues/46332
