### ISSUE TITLE
URLUtils is wrong for Location object

### ISSUE THREAD

**Issue by annevk** [whatwg/url#61]
The `Location` object probably requires special treatment since setting its setters do not actually change the underlying URL directly. They just cause navigation. And the last navigation seems to win, too:

``` js
location.pathname = "x"
location.protocol = "https"
```

Navigates to a URL with a new scheme, not a new path.

**Comment by annevk** [comment]
`Location.prototype.protocol` is also special in that it throws for invalid schemes. But it also ignores schemes that are not compatible. Effectively only `https`, `http`, and `ftp` seem to function. See this older bug report https://www.w3.org/Bugs/Public/show_bug.cgi?id=23523 by @arv which I'll close in favor of this issue.

**Comment by domenic** [comment]
This has been fixed in HTML.

**Comment by annevk** [comment]
I think the invalid protocols still needs to be fixed unfortunately. Requires some further study.

**Comment by annevk** [comment]
Looking at the setter in https://html.spec.whatwg.org/multipage/browsers.html#dom-location-protocol it seems to anticipate a change in the URL Standard where we sometimes return failure for bogus schemes. That will then result in an exception.

I've also noticed that browsers will change the scheme of data URLs and attempt to navigate, which would go against the HTML Standard. They also appear to use DOMException "SyntaxError" rather than TypeError. The exception we should probably change in the HTML Standard, but browsers might want to update to change the scheme less overall.

**Comment by annevk** [comment]
Once those tests lands this can be closed once bugs have been filed against browsers.

**Comment by annevk** [comment]
Bugs filed thus far:

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10422816/
https://bugzilla.mozilla.org/show_bug.cgi?id=1328843

**Comment by annevk** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1328894
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10426237/
https://bugs.webkit.org/show_bug.cgi?id=166729
https://bugs.chromium.org/p/chromium/issues/detail?id=678633
