### ISSUE TITLE
URL parsing with raw ip like "127.0.0.1"

### ISSUE THREAD

**Issue by scw00** [whatwg/url#622]
https://url.spec.whatwg.org/commit-snapshots/0672f2e2ef43aca18b59d90abb6dac21712399bb/#scheme-start-state

It seems it should fall through into Scheme state if i use "127.0.0.1/a/b/c" as url string. Since NoScheme state will direct to File State.

**Comment by TimothyGu** [comment]
What would you expect the scheme to be for a "URL" like 127.0.0.1? The URL Standard only deals with actual URL parsing as observed programmatically (think `new URL(…)` or `<a href="…">`), not the browser address bar (which automatically prepends `https:` or `http:` as needed).

Also, if we have `<a href="…">` being served on a page https://example.com/, we would actually expect the resolved URL to be https://example.com/127.0.0.1. So the current spec appears to be correct.
