### ISSUE TITLE
URL dumb behavior

### ISSUE THREAD

**Issue by alesmenzel** [whatwg/url#623]
Could you please explain to me why are there special schemas for whatwg URL and why we cannot change from one protocol to another without a silent error?

Example
```
const url = new URL('es://localhost:9200')
url.protocol = 'http'
// outputs es://localhost:9200
```

Workaround
```
const url = new URL('es://localhost:9200')
url.protocol = 'httpx'
url.toString().replace(/httpx/, 'http')
// outputs http://localhost:9200
```

Why? I am really annoyed.

**Comment by achristensen07** [comment]
This has to do with idempotence and the parsing differences between parsing special and non-special schemes.  Consider this example:
```
x = new URL("asdf://host")
x.pathname // "" in Safari and the spec, "//host" in Chrome and Firefox
x.protocol = "https"
x.pathname // "/"
```
Changing the protocol has changed the pathname value.  This is undesirable.
