### ISSUE TITLE
[proposal] Enhanced the ability for multiple same-name-parameters to the URLSearchParams: .has() and .delete()

### ISSUE THREAD

**Issue by LIXiangChen** [whatwg/url#680]
The proposal is fully compatible with the existing scheme.
There has a similar idea https://github.com/whatwg/url/issues/335, but not exactly same.

---

### Syntax
```
URLSearchParams.has(name, [value])
```

> ### The changes
1. Added optional second parameter

### Syntax
```
URLSearchParams.delete(name, [value])
```
**_Return value_**
Number of parameters deleted, greater than or equal to _0_.

> ### The changes
1. Added optional second parameter
2. Added return value, this is very useful

**Comment by annevk** [comment]
https://github.com/whatwg/url/issues/335#issuecomment-623477090 applies here as well:

> What would help in driving this forward is some indication that this is a common need (e.g., StackOverflow questions) and is being addressed in libraries (with the proposed semantics). That might make this a more compelling case to implementers.

**Comment by TimothyGu** [comment]
Not sure if we need a `.has(key, value)`, since it's equivalent to `.getAll(key).include(value)`. The possibility of adding a return value to `delete` is interesting though, since `Map.prototype.delete` returns a boolean for whether an entry was deleted.

**Comment by annevk** [comment]
@LIXiangChen can you elaborate on when you would use the return value?
