### ISSUE TITLE
File state => Otherwise is written really confusingly

### ISSUE THREAD

**Issue by Sebmaster** [whatwg/url#69]
https://url.spec.whatwg.org/#file-state => Otherwise => step 1

From what I gathered: we have 3 conditions, they are all ORed, so:
Making one case "remaining consists of one code point" and another case "remaining’s second code point is not one of "/", "\", "?", and "#"" is unnecessary. The latter will never be true without the former also being true, so we don't have to check for it explicitly, which leads me to believe that something about these conditions is wrong.

**Comment by annevk** [comment]
How can we check for the second code point if there's not at least two code points?

**Comment by Sebmaster** [comment]
Oh wait I think I constantly misread the first part. I was always under the impression that it waas _at least_ 1 codepoint. We're good then :confused:
