### ISSUE TITLE
PSL references broken

### ISSUE THREAD

**Issue by annevk** [whatwg/url#692]
It seems that https://publicsuffix.org/list/ got updated to remove the algorithm that was present there...

cc @dnsguru

**Comment by domenic** [comment]
https://github.com/publicsuffix/list/wiki/Format#format seems to be the new home

**Comment by dnsguru** [comment]
Hi y'all - yeah we moved it - was hard to track "parallel evolution"

**Comment by dnsguru** [comment]
The PSL Algorithm can be found here: https://github.com/publicsuffix/list/wiki/Format#formal-algorithm
