### ISSUE TITLE
Public Suffix List (PSL) is not ASCII

### ISSUE THREAD

**Issue by alevesely** [whatwg/url#695]
Section [3.2 "Host miscellaneous"](https://url.spec.whatwg.org/#host-miscellaneous) specifies a host's public suffix.  Bullet 3 says:

    3. Assert: publicSuffix is an ASCII string.

How come?  Since the list is UTF-8 encoded and the algorithm provides no conversions, the resulting *publicSuffix* must be UTF-8.

**Comment by annevk** [comment]
Apologies for dropping the ball here. The Public Suffix List (I assume you meant to write that) is a list of public suffixes, informally speaking. When that list is processed for practical usage, the U-labels will have been converted to ASCII, which is what the URL Standard is asserting.

I don't think there's any problem here so closing this, but do let me know if I got it wrong somehow and there is a problem.
