### ISSUE TITLE
| in windows file paths needs to be handled specially

### ISSUE THREAD

**Issue by Sebmaster** [whatwg/url#70]
Web Platform Tests contains the test `Parsing: <//C|/foo/bar> against <file:///tmp/mock/path>`

1. [file host state](https://url.spec.whatwg.org/#file-host-state) has "C|" in its buffer, current pointer points to "/" => set state to path state
2. [path state](https://url.spec.whatwg.org/#path-state) receives buffer, and pointer pointing to f => appends f, o, o
3. path state's | to : conversion isn't invoked anymore, since c is never "/" and then buffer never exactly matches the drive letter definition anymore (buffer instead equals C|foo)

I think there should be a "decrement pointer by 1" in the file host state before redirecting to path state, so path state tries to match windows drive letter immediately.

**Comment by annevk** [comment]
This is what "file host state" does, no? "If c is one of EOF code point, "/", "\", "?", and "#", decrease pointer by one, ..."

**Comment by Sebmaster** [comment]
Ohman, I'm misreading this stuff way too much, sorry about that. :confounded: 

This is great, I should be able to match latest spec tonight then :tada:
