### ISSUE TITLE
"Align RFC 3986 and RFC 3987 with contemporary i..."

### ISSUE THREAD

**Issue by gatesray** [whatwg/url#712]
https://url.spec.whatwg.org/commit-snapshots/6827fbe62fa492cb69c4622b664cd864b43e49f8/#goals

> Align RFC 3986 and RFC 3987 with contemporary implementations and obsolete them in the process\.

The use of "them" is ambiguous. Does it refer to the RFCs or the contemporary implementations?

**Comment by annevk** [comment]
Fair.

Tagging as a "good first issue" to replace "them" with "the RFCs" for anyone that is both willing to do that and can sign https://participate.whatwg.org/agreement.
