### ISSUE TITLE
Proposal: Functional chaining on URLSearchParams

### ISSUE THREAD

**Issue by JamiesonRoberts** [whatwg/url#756]
It would be good to allow functional chaining of methods on URLSearchParams

Today to chain operations like sort() and toString() we have to do the following

```
const url = new URLSearchParams('?b=23&c=12&a=asdf');
url.sort();
console.log(url.toString());
```

The ideal state would be to be able to do the following in various scenarios:

```
console.log(new URLSearchParams('?b=23&c=12&a=asdf').sort().toString());

-- or --

const url = new URLSearchParams('?b=23&c=12&a=asdf');
console.log(url.sort().toString());
```

**Comment by JamiesonRoberts** [comment]
@annevk interesting, I hadn't thought about that. What are the possible use cases for listing mutations of something like a sort? Also, aren't there other prototypes that do that with a map like syntax where you then consume it with multiple parameters?

**Comment by annevk** [comment]
Closing as per https://github.com/w3ctag/design-principles/issues/286.
