### ISSUE TITLE
Let [=UTF-8 percent-encode=] take an extra optional boolean parameter spaceAsPlus (default false)

### ISSUE THREAD

**Issue by qingxinwu** [whatwg/url#765]
Is it possible to add an extra boolean parameter `spaceAsPlus` which defaults to false to [UTF-8 percent-encode algorithm](https://url.spec.whatwg.org/#utf-8-percent-encode)? It calls the not exported [percent-encode after encoding algorithm](https://url.spec.whatwg.org/#string-percent-encode-after-encoding) which has the `spaceAsPlus` parameter. For our use case, we want to set `spaceAsPlus` to true when using [=UTF-8 percent-encode=] algorithm, which is not supported for the algorithm's current defination.

**Comment by annevk** [comment]
What is your use case? And why doesn't it use `application/x-www-form-urlencoded`?

**Comment by qingxinwu** [comment]
In our code, we encode query params using [EscapeQueryParamValue](https://crsrc.org/c/base/strings/escape.cc;drc=b4bc946c63b2b95e1f05dec4e84adcadd10499c6;l=471) with its use_plus parameter set to true to encode space as "+". It does use `application/x-www-form-urlencoded`.

**Comment by annevk** [comment]
I guess what I'm wondering is if you can use https://url.spec.whatwg.org/#concept-urlencoded-serializer as entry point, similar to HTML.

Looking at the callers of what you point to it seems to be inventing its own key/value format with commas instead of ampersands. That's precisely the kind of thing we'd like to avoid.

**Comment by qingxinwu** [comment]
Sorry, after a closing look, I was wrong about our code using `application/x-www-form-urlencoded`. It seems it uses [component percent-encode set](https://url.spec.whatwg.org/#component-percent-encode-set), since [EscapeQueryParamValue](https://crsrc.org/c/base/strings/escape.h;drc=b4bc946c63b2b95e1f05dec4e84adcadd10499c6;l=29) does not encode `!'()~`. So I think we cannot use urlencoded-serializer.
I think we didn't invent a key/value format. It's still `&key=value`, but different values of a key are concatenated using commas, e.g., "https://a.com?&key1=value1,value11&key2=value2,value22...".

I think our use case needs an entry point which allows setting `percentEncodeSet` to "component percent-encode set" and `percentEncodeSet` to true.

**Comment by annevk** [comment]
I mean, that is a new format. Multiple values are encoded by repeating the key in `application/x-www-form-urlencoded`.

Since it seems like this is a new technology, it seems like there would still be time to adapt.

**Comment by qingxinwu** [comment]
Ah I see. Thanks for the clarification!
1. Are you suggesting that instead of `&key1=value1,value2`, it should (or better to) be `&key1=value1&key1=value2` by standard? Sorry I'm not familiar with this, so not sure how strict the requirement is to follow the latter format.
2. Besides that, any suggestion on how to spec [EscapeQueryParamValue](https://crsrc.org/c/base/strings/escape.h;drc=b4bc946c63b2b95e1f05dec4e84adcadd10499c6;l=29) with its `percentEncodeSet` set to true? [This](https://crsrc.org/c/content/services/auction_worklet/trusted_signals.cc;drc=d80a12e889e628c560d36a7346dc6934eadc07f1;l=41) is our code, if that's helpful. It is the part that I'm wondering how to document in our spec.

**Comment by domenic** [comment]
I'd suggest using platform infrastructure as much as you can. This means: (1) yes, use `&key1=value1&key1=value2`, since that's the standard format; (2) use `%20`, not `+`, since that's what the standard does.

**Comment by MattMenke2** [comment]
Hrm...  Using "+" is consistent with what the Javascript URL class does when adding search parameters.  Guess that class is over 10 years old, so may not be up to date with the latest best practices.  :(

**Comment by domenic** [comment]
See https://github.com/whatwg/url/issues/491 for that issue :(

**Comment by annevk** [comment]
I think using https://url.spec.whatwg.org/#concept-urlencoded-serializer and assigning that to URL's query is fine. That gives you `+`.

(I think #491 is still inaccurate in that it assumes the key-value format is somehow larger than `application/x-www-form-urlencoded`. It's not clear we should do that.)

**Comment by qingxinwu** [comment]
Thanks everyone! We're thinking about changing how we escape our URL query params, and application/x-www-form-urlencoded serializer should work then.
