### ISSUE TITLE
All instances of %2e in the path should be decoded into `.`

### ISSUE THREAD

**Issue by valenting** [whatwg/url#77]
Currently Chrome, Edge and Firefox decode instances of %2e in the path to . regardless if it is a path segment or not. (Safari doesn't decode it at all).
As noted in [1], I believe this is the correct behaviour, as to access a file named %2eX one actually has to navigate to path/%252eX.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1042347#c4

**Comment by annevk** [comment]
Proposal:

Between "path state"'s 3.2 and 3.3 we insert a new step that reads:

* If c is "%" and remaining, ASCII lowercased, starts with "2e", append "." to buffer and increase pointer by two.

Then we change step 3.3 (the old one) to become an Otherwise clause.

**Comment by valenting** [comment]
Looks good to me.

**Comment by SimonSapin** [comment]
I was surprised that `.` was such a special case. It is indeed in Firefox 44, but in Chromium 48 other characters are also percent-decoded: `-`, `_`, `~`, and ASCII alpha-numerics. (I don’t have other browsers to test right now.)

http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=3878
