### ISSUE TITLE
Confused about the constructor argument types

### ISSUE THREAD

**Issue by onlywei** [whatwg/url#80]
So, the spec's constructor interface says:

```
Constructor(USVString url, optional USVString base)
```

However, right below that it says that both the `url` and `base` param will be run through the [basic-url-parser](https://url.spec.whatwg.org/#concept-basic-url-parser), which claims it can accept both `string input` and `URL url`.

Does this mean that the `URL()` constructor is also supposed to accept `URL` objects for its first and second arguments, in addition to `USVString`?

**Comment by annevk** [comment]
If you pass a `URL` object it will be stringified and end up working fine. We decided it was not worth it to also directly accept objects in the JavaScript API. Especially as in JavaScript URLs are typically passed around as strings.

The reason the URL parser takes an actual URL is because that is used by many other specifications.

Does that help?

**Comment by onlywei** [comment]
@annevk thanks for your response, but I'm still confused.

The following two sentences seem contradictory:
"If you pass a URL object it will be stringified and end up working fine."
"We decided it was not worth it to also directly accept objects in the JavaScript API."

Right now, [MDN](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) is giving examples with URL objects being passed in as the second argument of the constructor. However, the [JSDom polyfill implementation](https://github.com/jsdom/whatwg-url) explicitly errors when you do that. Which one is wrong?

**Comment by domenic** [comment]
@onlywei can you file a bug on jsdom/whatwg-url? Preferably tested against master. I think we might just be missing a working toString().

**Comment by annevk** [comment]
I'll leave this open to add another example to https://url.spec.whatwg.org/#constructors where we explicitly use an object (that will get stringified) as a base URL.

**Comment by annevk** [comment]
@onlywei thank you for the report!
