### ISSUE TITLE
Let's strip leading '?' if present in `URLSearchParams` init string param

### ISSUE THREAD

**Issue by jakub-g** [whatwg/url#81]
(not sure if this is the best place to put this)

Regarding `URLSearchParams` constructor string param:
IMO it would be good to skip leading `?` if present, before starting to do the real parsing.

The reason is that `window.location.search` returns `?a=1&b=2` with leading `?`.
For consistency the URLSearchParams constructor should allow the leading `?` thus.

Looking at the spec and test they don't explicitly mention anything about leading `?`

https://url.spec.whatwg.org/#interface-urlsearchparams
https://github.com/w3c/web-platform-tests/blob/0ae07c6dec055b416e91a8e0e431eec8c2b2552b/url/urlsearchparams-get.html (master as of today)

In the current Firefox stable 44 and Chrome Canary 50 implementations this happens:

`new URLSearchParams('a=1&b=2').get('a') == 1`
`new URLSearchParams('?a=1&b=2').get('a') == null`
`new URLSearchParams('?a=1&b=2').get('?a') == 1`

what if instead we skipped leading `?` if present and return this:

`new URLSearchParams('?a=1&b=2').get('a') == 1`
`new URLSearchParams('?a=1&b=2').get('?a') == null`

What do you think?

**Comment by annevk** [comment]
I remember discussing this with @bakulf and thinking there would be some kind of problem. @mikewest, does this ring a bell?

**Comment by mikewest** [comment]
I wouldn't have a problem with updating Chrome's implementation in this way, but we also just shipped it, so we have less built-up usage than Firefox might.

**Comment by jakub-g** [comment]
Firefox implementation landed in Fx29, since it's Firefox-only the usage is probably very low for now

https://bugzilla.mozilla.org/show_bug.cgi?id=887836
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

Regarding polyfills of `window.URL` I only found two (excluding discontinued ones from @annevk and @arv):

https://github.com/inexorabletash/polyfill#url-api implements the same behavior as Firefox and Chrome Canary now
https://github.com/Polymer/URL/blob/master/url.js doesn't support `URLSearchParams` at all

**Comment by jakearchibald** [comment]
The way `.search` adds the `?` is very weird and catches me out a lot, but I'm not sure what this magic buys us.

Sure, it works around `new URLSearchParams(location.search)`, but when would you do that vs `location.searchParams`?

If this is being driven by Chrome having shipped `URLSearchParams` but not yet `url.searchParams`, it seems like a short term bandaid.

**Comment by annevk** [comment]
@jakearchibald so the main problem is that we don't have a good way of supporting this on `Location` due to the extremely weird nature of that object. https://www.w3.org/Bugs/Public/show_bug.cgi?id=27596 has details.

So if we're stuck with only having `searchParams` exposed on `URL` objects, is it more reasonable to do this? I'm leaning towards yes at this point, but happy to be swayed otherwise.

**Comment by jakearchibald** [comment]
Ah, I wasn't aware of the location behaviour. Hm, if location cannot have searchParams, then I guess this magic is useful.

**Comment by annevk** [comment]
@jakub-g, how would you like to appear in the acknowledgments section? See https://url.spec.whatwg.org/#acknowledgments.

**Comment by jakub-g** [comment]
@jakearchibald the use case could be as follows: 

perhaps someone will have a need to serialize the query string into localstorage or whatever else, and then read it back; in such case they may want to store `location.search` which has a leading `?`; then the `new URLSearchParams(location.search)` having the feature of stripping the leading `?` may save themselves some bugs.

@annevk My full name is `Jakub Gieryluk`

Thanks guys for the discussion!
