### ISSUE TITLE
Explain why valid domain needs to run ToUnicode

### ISSUE THREAD

**Issue by hsivonen** [whatwg/url#817]
### What is the issue with the URL Standard?

https://url.spec.whatwg.org/#valid-domain could use an informative note that states the implications of the two-step (both ToASCII and ToUnicode) check. Given the how both use UTS 46 "Processing" and "ToASCII" does more stuff after "Processing", it would be helpful to call out what the second run of "Processing" (as part of "ToUnicode") catches still.

**Comment by hsivonen** [comment]
FWIW, after more progressi with writing code, I'm even more puzzled about what the second run of "Processing" is meant to catch here.

**Comment by annevk** [comment]
I wonder if the difference has disappeared over time. It does seem weird that ToUnicode can now fail apparently, but there's no explicit mention of this.

**Comment by annevk** [comment]
I've put up #840 to fix this. I'm somewhat curious why you all implemented the "valid domain" definition. At least within the web platform there's no known caller for it and it's really meant to be more of a syntax explanation as to how to write a domain name.

**Comment by hsivonen** [comment]
> I'm somewhat curious why you all implemented the "valid domain" definition.

1. The `idna` crate had configurability on the points that _beStrict_ affects before my time.
2. Being able to flip options closer to _beStrict_=true is useful for being able to use the upstream IdnaTestV2.txt test suite fully. (I say "closer", because prior to Unicode 16.0, the test suite assumed _verifyDnsLength_=true with the quirk of allowing the trailing dot.)
