### ISSUE TITLE
CheckHyphens isn't set to beStrict

### ISSUE THREAD

**Issue by hsivonen** [whatwg/url#820]
### What is the issue with the URL Standard?

https://url.spec.whatwg.org/#concept-domain-to-ascii has a _beStrict_ flag to validation. This flag affects the _UseSTD3ASCIIRules_ and _VerifyDnsLength_ flags for UTS 46 processing, but don't affect the _CheckHyphens_ flag. AFAICT, STD3 conformance requires setting all three to true, because _UseSTD3ASCIIRules_ enables a non-positional deny list, but _CheckHyphens_ also denies the hyphen as the first or last character of a label.

To the extent validation tries to check for STD3 conformance, it's strange not to also set _CheckHyphens_ to _beStrict_.

**Comment by foolip** [comment]
Was this change made in some implementation? Chrome skips this check with a link to https://github.com/whatwg/url/issues/267, but it changed in this issue.
