### ISSUE TITLE
`URLSearchParams.set()` accepts an array as value in Firefox & Chrome but this is nowhere documented

### ISSUE THREAD

**Issue by codethief** [whatwg/url#833]
### What is the issue with the URL Standard?

As the title says, Firefox 129 and Chrome 124 seem to support set()ting a query parameter to a list of values:

```
const url = new URL('https://www.example.com');
url.searchParams.set('param', ['foo', 'bar', 'baz']);
console.log(url.toString()); // https://www.example.com/?param=foo%2Cbar%2Cbaz
```

However, I can't find anything about this feature – neither on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/set) nor on the [Chrome Developer blog](https://developer.chrome.com/blog/urlsearchparams/), nor in the [spec](https://url.spec.whatwg.org/#dom-urlsearchparams-set). Moreover, TypeScript's lib.dom.d.ts [defines the signature of set() as](https://github.com/microsoft/TypeScript/blob/main/src/lib/dom.generated.d.ts#L22410)

```
set(name: string, value: string): void;
```

How come this is not documented anywhere? I suppose this is not an official feature? What other browsers support this (and if so, which versions)? Would it make sense to add it to the spec?

**Comment by domenic** [comment]
They do not accept strings. JavaScript just converts `["foo", "bar", "baz"]` to the string `foo,bar,baz` which percent-encodes to `foo%2Cbar%2Cbaz`.

**Comment by annevk** [comment]
This is documented although not in the sense you would expect.

The second argument of `set()` is of type `USVString` as per https://url.spec.whatwg.org/#interface-urlsearchparams which per step 1 of https://webidl.spec.whatwg.org/#js-USVString means that through some indirection https://tc39.es/ecma262/multipage/abstract-operations.html#sec-tostring gets invoked on the value passed as second argument. Which is what you are observing.

**Comment by codethief** [comment]
Ahh, looks like I got bitten by JavaScript's weak typing. Thanks!
