### ISSUE TITLE
Suggestion to Add Translated Link for url (Simplified Chinese 简体中文)

### ISSUE THREAD

**Issue by JinDX** [whatwg/url#834]
### What is the issue with the URL Standard?

I have completed the translation of the URL specification into Simplified Chinese (简体中文). Here is the link to the translated document:

- [Translated version of the specification in Simplified Chinese](https://htmlspecs.com/url)

It would be helpful for international users if this link could be added to the official documentation or the README.

Thank you for considering this request!

**Comment by annevk** [comment]
Thank you for creating that translation! It's now linked from the top of https://url.spec.whatwg.org
