### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by stevenvachon** [whatwg/url#88]
Has this gained any traction in the industry or is it another proposal that could just get ignored?

**Comment by annevk** [comment]
This standard defines how browsers implement URLs. And defines some new APIs  that have been adopted by browsers. I'm not sure I understand your question though, could you elaborate?

**Comment by stevenvachon** [comment]
Hmm, I thought that it was with the intent of having a standard `URL` library available in all browsers.

**Comment by annevk** [comment]
There's a JavaScript API sure, and that's implemented by several browsers as you should be able to observe, but there's also URL parsing in general that needs to be defined and is by this document. It's still not entirely clear to me what the concern is, though.

**Comment by stevenvachon** [comment]
What JavaScript API do several browsers have? https://developer.mozilla.org/en/docs/Web/API/URL ?

**Comment by stevenvachon** [comment]
I guess that I'm just generally confused. Is this a spec for https://developer.mozilla.org/en/docs/Web/API/URL ?

**Comment by annevk** [comment]
It is, yes.

**Comment by stevenvachon** [comment]
Ok, thanks.
