### ISSUE TITLE
URL spec change on host setter.

### ISSUE THREAD

**Issue by m4h3** [whatwg/url#93]
Following discussion here : https://code.google.com/p/chromium/issues/detail?id=551901

Note that clarification has been made here https://github.com/whatwg/url/issues/75.

Bug as been filled https://bugs.webkit.org/show_bug.cgi?id=151613 to change Safari "correct intuitive" behavior.

Host setter is barely usable today as it is not much different from hostname. Host is a composite value o hostname+port, setter on this composite attribute should call setters on underlying URL parts.
The host setter should reset to the scheme default port.

current spec (and current FF/Chrome impl.):
var a = new URL("http://www.google.com:8888")
var b = new URL("http://www.wikipedia.org")
a.host = b.host
"www.wikipedia.org"
a.host == b.host
false

Modifying the spec would lead to return true here.

**Comment by annevk** [comment]
What does Edge do?

**Comment by domenic** [comment]
Edge doesn't implement the URL constructor.

**Comment by domenic** [comment]
But for `<a>` elements it behaves the same as Chrome and Firefox: http://jsbin.com/xocefeqeya/edit?html,console,output

**Comment by annevk** [comment]
Thank you, I don't see a reason to change this then. Sorry @m4h3!
