### ISSUE TITLE
Rename the non-relative flag to non-hierarchical?

### ISSUE THREAD

**Issue by SimonSapin** [whatwg/url#94]
The term *relative* has a different meaning in *a relative URL* (a string that needs a base URL to be parsed successfully) and *an URL’s non-relative flag* (which indicates it can not meaningfully be used as a base URL). For example, `http://whatwg.org` is not a relative URL, but it is not non-relative either (its non-relative flag is unset).

To reduce term overloading, the non-relative flag (and non-relative path state) could be renamed to something else. Maybe *non-hierarchical*? Or just *hierarchical* and flip the logic. It’s annoying to type and pronounce, but RFC 3986 seems to be using hierarchical for roughly this concept.

**Comment by domenic** [comment]
See #89.

**Comment by SimonSapin** [comment]
Ah! Glad I’m not the only one to think this is a problem (if a minor one). I’ll close this in favor of #89.
