### ISSUE TITLE
"A query must be zero or more URL units.  "

### ISSUE THREAD

**Issue by zcorpan** [whatwg/url#95]
https://url.spec.whatwg.org/#url-syntax

> A query must be zero or more URL units\.
> 

This should probably say something about encodings. Maybe make unescaped non-ASCII characters invalid in the query when the encoding isn't utf-8 (or utf-16?). And add a note/example explaining this.

Related https://github.com/htacg/tidy-html5/issues/378

**Comment by annevk** [comment]
URLs don't have an encoding associated with them though. This only applies to HTML and I think it already says something about this, no?

**Comment by annevk** [comment]
And also, although HTML allows other encodings, the Encoding Standard does not...

**Comment by zcorpan** [comment]
HTML says 

> A URL is a valid URL if it conforms to the authoring conformance requirements in the WHATWG URL standard. [URL]

I think it used to have normative authoring restrictions based on the document's encoding, but I don't see it anymore. Though I could live with this being done in the HTML spec.

I think it's still a good idea to have multiple levels of conformance requirements. Not mentioning the issues because we ban non-utf-8 means that more people will be aware that the issues exist at all. In practical terms, I want validators to whine both about the wrong document encoding and pin-point the places where it is a problem.

**Comment by annevk** [comment]
What about we just add a note here? I don't see how we can make a conformance requirement unless we go really convoluted and basically step into HTML's territory.

**Comment by zcorpan** [comment]
A note+example seems OK.
